# Overall Score Metrics Construction

- Non-Submit has already been accounted for during the judging process. 
- NaN -> participants app are not compiling and that they are getting a zero as their scores. Hence we replace NaN with a zero.

## Bogota 0 Scores Dataframe

In [1]:
import pandas as pd 

bogota0 = pd.read_csv("Bogota-0-Scores.csv")
bogota0

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,...,tech-phase2,user-requirement-phase2,infovis-phase2,novelty-phase2,total-phase2,tech-phase1,user-requirement-phase1,infovis-phase1,novelty-phase1,total-phase1
0,0,fffeelipe,0,20,29.17,50.00,199.17,100.0,100.0,20.0,...,75.0,60.0,37.50,0.0,172.50,50.0,20.0,29.17,0.0,99.17
1,1,mnguzmanc,0,60,75.00,67.50,290.00,87.5,87.5,20.0,...,87.5,20.0,37.50,75.0,220.00,87.5,0.0,0.00,0.0,87.50
2,2,jmcuestasb,0,100,54.17,25.00,254.17,75.0,62.5,100.0,...,62.5,20.0,33.33,25.0,140.83,50.0,NaN,NaN,NaN,50.00
3,3,katherinsb,0,20,37.50,16.67,136.67,62.5,37.5,20.0,...,12.5,NaN,NaN,NaN,12.50,0.0,0.0,0.00,0.0,0.00
4,4,jjrodriguezn,0,60,58.33,87.50,255.83,50.0,37.5,40.0,...,62.5,20.0,29.17,0.0,111.67,0.0,NaN,NaN,NaN,0.00
5,5,DglyP,0,20,25.00,50.00,195.00,100.0,87.5,0.0,...,37.5,40.0,45.83,0.0,123.33,NaN,NaN,NaN,NaN,0.00
6,6,cap182,0,20,29.17,0.00,49.17,0.0,0.0,20.0,...,12.5,0.0,20.83,0.0,33.33,NaN,40.0,33.33,75.0,148.33
7,7,annumumozme,0,40,37.50,60.00,237.50,100.0,75.0,0.0,...,37.5,20.0,45.83,0.0,103.33,37.5,NaN,NaN,NaN,37.50
8,8,Judgarciani,0,100,58.33,66.67,325.00,100.0,75.0,80.0,...,37.5,20.0,29.17,0.0,86.67,NaN,NaN,NaN,NaN,0.00
9,9,sacastroc,0,20,50.00,68.75,226.25,87.5,87.5,20.0,...,87.5,20.0,33.33,62.5,203.33,50.0,0.0,25.00,0.0,75.00
10,10,pcberriop,0,20,37.50,62.50,195.00,75.0,50.0,20.0,...,50.0,20.0,33.33,62.5,165.83,12.5,40.0,25.00,0.0,77.50
11,11,hsmartineza,0,20,33.33,52.50,180.83,75.0,62.5,20.0,...,37.5,20.0,29.17,0.0,86.67,NaN,NaN,NaN,NaN,0.00
12,12,Moimolcp,0,100,62.50,66.67,304.17,75.0,62.5,0.0,...,62.5,0.0,33.33,25.0,120.83,25.0,0.0,0.00,0.0,25.00
13,13,CamiloRueda,0,0,29.17,0.00,54.17,25.0,25.0,20.0,...,37.5,0.0,25.00,0.0,62.50,0.0,0.0,0.00,0.0,0.00
14,14,juanescai,0,0,25.00,25.00,50.00,0.0,0.0,0.0,...,12.5,0.0,25.00,25.0,62.50,25.0,0.0,25.00,62.5,112.50
15,15,JoseMolano,0,60,66.67,75.00,276.67,75.0,87.5,0.0,...,87.5,0.0,33.33,25.0,145.83,87.5,20.0,50.00,37.5,195.00
16,16,maikellPardoA,0,0,37.50,25.00,87.50,25.0,25.0,NaN,...,37.5,0.0,25.00,25.0,87.50,37.5,0.0,25.00,25.0,87.50
17,17,NicolasZon,0,0,25.00,25.00,87.50,37.5,37.5,0.0,...,50.0,0.0,25.00,25.0,100.00,12.5,0.0,0.00,0.0,12.50
18,18,camilo654,0,20,29.17,75.00,199.17,75.0,75.0,60.0,...,62.5,20.0,25.00,87.5,195.00,25.0,20.0,29.17,0.0,74.17
19,19,CristianLozano,0,20,33.33,0.00,90.83,37.5,37.5,60.0,...,50.0,20.0,33.33,0.0,103.33,50.0,20.0,29.17,0.0,99.17
20,20,jdsuarezj,0,60,50.00,87.50,272.50,75.0,75.0,60.0,...,75.0,0.0,25.00,25.0,125.00,62.5,0.0,25.00,75.0,162.50
21,21,pipemax85,0,20,33.33,0.00,115.83,62.5,50.0,20.0,...,50.0,20.0,33.33,0.0,103.33,50.0,20.0,25.00,0.0,95.00
22,22,juandavidro,0,20,58.33,25.00,153.33,50.0,37.5,20.0,...,50.0,20.0,33.33,25.0,128.33,87.5,80.0,58.33,75.0,300.83
23,23,UNhcrodriguezl,0,80,33.33,75.00,263.33,75.0,75.0,20.0,...,75.0,20.0,33.33,62.5,190.83,37.5,20.0,33.33,0.0,90.83
24,24,camilo13152,0,60,50.00,37.50,222.50,75.0,62.5,60.0,...,50.0,20.0,33.33,0.0,103.33,0.0,0.0,29.17,0.0,29.17
25,25,leavendanoro,0,40,66.67,25.00,206.67,75.0,75.0,0.0,...,62.5,0.0,25.00,25.0,112.50,37.5,0.0,0.00,0.0,37.50
26,26,cdcordobaa,0,20,33.33,62.50,190.83,75.0,75.0,20.0,...,75.0,20.0,33.33,62.5,190.83,37.5,20.0,33.33,0.0,90.83
27,27,capinillab,0,60,54.17,75.00,264.17,75.0,62.5,60.0,...,62.5,60.0,37.50,87.5,247.50,62.5,20.0,33.33,0.0,115.83
28,28,Januguerab,0,20,29.17,0.00,111.67,62.5,50.0,20.0,...,37.5,20.0,29.17,0.0,86.67,NaN,NaN,NaN,NaN,0.00
29,29,lfvalderrama,0,80,66.67,106.25,352.92,100.0,87.5,20.0,...,75.0,0.0,41.67,25.0,141.67,75.0,0.0,0.00,0.0,75.00
30,30,bsgarciac,0,100,70.83,75.00,320.83,100.0,75.0,80.0,...,62.5,40.0,41.67,87.5,231.67,50.0,20.0,37.50,0.0,107.50
31,31,gabi04,0,20,29.17,58.33,157.50,50.0,25.0,20.0,...,37.5,0.0,25.00,0.0,62.50,NaN,NaN,NaN,NaN,0.00
32,32,annipi,0,0,0.00,0.00,0.00,0.0,NaN,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00
33,33,jdsolanos,0,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,62.5,NaN,NaN,NaN,62.50
34,34,jcneivaa,0,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00
35,35,fmbernalb,0,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00
36,36,MogGy94,0,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,12.5,0.0,0.00,0.0,12.50
37,37,yocuervoc,0,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,0.0,0.00,0.0,0.00
38,38,odprietoh,0,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,0.0,25.00,25.0,62.50,0.0,0.0,25.00,0.0,25.00

## Bogota 1 Scores Dataframe

In [2]:
bogota1 = pd.read_csv("Bogota-1-Scores.csv")
bogota1

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,tech-phase5,total-phase5,tech-phase4,user-requirement-phase4,...,tech-phase2,user-requirement-phase2,infovis-phase2,novelty-phase2,total-phase2,tech-phase1,user-requirement-phase1,infovis-phase1,novelty-phase1,total-phase1
0,0,gasierram,1,40,62.50,25.00,62.5,190.00,62.5,40.0,...,62.5,20.0,33.33,25.00,140.83,62.5,20.0,50.00,62.50,195.00
1,1,adamantwharf,1,20,25.00,0.00,62.5,107.50,50.0,20.0,...,50.0,20.0,25.00,0.00,95.00,37.5,20.0,25.00,0.00,82.50
2,2,bdcajicam,1,40,29.17,62.50,75.0,206.67,62.5,20.0,...,50.0,20.0,25.00,0.00,95.00,25.0,0.0,0.00,0.00,25.00
3,3,andfsanchezlem,1,20,25.00,0.00,0.0,45.00,0.0,20.0,...,12.5,20.0,25.00,0.00,57.50,25.0,20.0,25.00,0.00,70.00
4,4,dfhincapiem,1,20,25.00,25.00,37.5,107.50,37.5,20.0,...,50.0,20.0,58.33,0.00,128.33,0.0,NaN,NaN,NaN,0.00
5,5,helmeraac,1,0,25.00,0.00,62.5,87.50,37.5,20.0,...,37.5,0.0,25.00,87.50,150.00,25.0,20.0,25.00,0.00,70.00
6,6,dasalgadob,1,0,25.00,25.00,50.0,100.00,50.0,100.0,...,50.0,0.0,25.00,0.00,75.00,50.0,0.0,25.00,25.00,100.00
7,7,falperezgo,1,20,45.83,62.50,100.0,228.33,100.0,40.0,...,100.0,80.0,62.50,87.50,330.00,75.0,40.0,66.67,75.00,256.67
8,8,djguzmanc,1,80,79.17,100.00,75.0,334.17,62.5,60.0,...,62.5,60.0,62.50,81.25,266.25,62.5,60.0,70.83,87.50,280.83
9,9,gsuarezc04,1,0,25.00,0.00,25.0,50.00,25.0,0.0,...,37.5,0.0,20.83,75.00,133.33,0.0,NaN,NaN,NaN,0.00
10,10,oeroaq,1,100,87.50,82.50,87.5,357.50,75.0,100.0,...,75.0,80.0,58.33,75.00,288.33,37.5,60.0,58.33,75.00,230.83
11,11,gcantem,1,100,70.83,87.50,25.0,283.33,100.0,60.0,...,62.5,60.0,41.67,87.50,251.67,62.5,100.0,79.17,87.50,329.17
12,12,Semoralesga,1,20,33.33,62.50,50.0,165.83,62.5,20.0,...,75.0,20.0,33.33,62.50,190.83,12.5,20.0,33.33,0.00,65.83
13,13,jonatan360,1,100,75.00,77.50,100.0,352.50,100.0,60.0,...,87.5,40.0,37.50,62.50,227.50,100.0,60.0,70.83,55.00,285.83
14,14,jesusfchavarro,1,100,62.50,82.50,100.0,345.00,75.0,100.0,...,75.0,60.0,66.67,87.50,289.17,100.0,40.0,33.33,75.00,248.33
15,15,stevenbustos,1,20,33.33,70.00,75.0,198.33,62.5,20.0,...,50.0,20.0,33.33,0.00,103.33,12.5,20.0,37.50,62.50,132.50
16,16,jufcontrerasco,1,60,79.17,50.00,75.0,264.17,75.0,20.0,...,50.0,0.0,33.33,25.00,108.33,0.0,0.0,29.17,62.50,91.67
17,17,dsbarrerag,1,80,70.83,91.67,87.5,330.00,87.5,60.0,...,75.0,100.0,70.83,87.50,333.33,50.0,80.0,70.83,25.00,225.83
18,18,wolfstain,1,20,33.33,56.25,87.5,197.08,87.5,20.0,...,75.0,20.0,33.33,62.50,190.83,25.0,20.0,29.17,0.00,74.17
19,19,miaborjaac,1,80,70.83,85.00,87.5,323.33,75.0,80.0,...,62.5,20.0,33.33,0.00,115.83,62.5,20.0,37.50,0.00,120.00
20,20,ivdgonzalezco,1,100,50.00,87.50,75.0,312.50,75.0,40.0,...,75.0,20.0,33.33,0.00,128.33,0.0,NaN,NaN,NaN,0.00
21,21,maikellPardo,1,0,37.50,25.00,0.0,62.50,25.0,0.0,...,12.5,0.0,25.00,25.00,62.50,37.5,0.0,25.00,25.00,87.50
22,22,Christian7sr,1,20,29.17,0.00,75.0,124.17,75.0,20.0,...,62.5,20.0,29.17,0.00,111.67,25.0,20.0,29.17,0.00,74.17
23,23,jsnarvaezb,1,20,54.17,50.00,87.5,211.67,75.0,40.0,...,62.5,20.0,50.00,75.00,207.50,50.0,20.0,41.67,62.50,174.17
24,24,gfalbarracinr,1,0,25.00,0.00,75.0,100.00,50.0,NaN,...,37.5,0.0,25.00,0.00,62.50,12.5,0.0,25.00,25.00,62.50
25,25,aldiazve,1,20,54.17,75.00,87.5,236.67,87.5,60.0,...,75.0,40.0,45.83,50.00,210.83,37.5,20.0,25.00,37.50,120.00
26,26,diegoaguevarar,1,80,62.50,87.50,87.5,317.50,75.0,100.0,...,75.0,40.0,54.17,50.00,219.17,50.0,0.0,25.00,12.50,87.50
27,27,fevargasmo,1,40,50.00,75.00,75.0,240.00,75.0,40.0,...,75.0,0.0,29.17,25.00,129.17,50.0,40.0,75.00,0.00,165.00
28,28,jmhurtadoc,1,0,33.33,25.00,62.5,120.83,62.5,0.0,...,62.5,0.0,25.00,0.00,87.50,100.0,0.0,25.00,37.50,162.50
29,29,anfmorenoso,1,40,37.50,52.50,87.5,217.50,75.0,20.0,...,62.5,20.0,33.33,0.00,115.83,0.0,20.0,37.50,40.00,97.50
30,30,nabautistal,1,20,50.00,62.50,62.5,195.00,37.5,20.0,...,50.0,20.0,29.17,0.00,99.17,12.5,20.0,25.00,0.00,57.50
31,31,crigar,1,20,25.00,0.00,37.5,82.50,62.5,20.0,...,50.0,20.0,25.00,0.00,95.00,25.0,20.0,25.00,0.00,70.00
32,32,jiapulidoar,1,60,83.33,66.67,100.0,310.00,100.0,40.0,...,100.0,40.0,41.67,75.00,256.67,87.5,40.0,50.00,41.67,219.17
33,33,jsviveroj,1,80,79.17,72.50,100.0,331.67,87.5,60.0,...,75.0,20.0,33.33,25.00,153.33,50.0,20.0,33.33,0.00,103.33
34,34,daandradec,1,100,66.67,95.00,75.0,336.67,75.0,100.0,...,87.5,80.0,58.33,87.50,313.33,50.0,0.0,25.00,62.50,137.50
35,35,jcrubioa,1,40,50.00,81.25,75.0,246.25,75.0,20.0,...,75.0,0.0,25.00,87.50,187.50,75.0,20.0,41.67,0.00,136.67
36,36,joahernandezca,1,20,54.17,25.00,62.5,161.67,50.0,20.0,...,50.0,0.0,25.00,0.00,75.00,50.0,0.0,37.50,62.50,150.00
37,37,ItsNavi,1,0,0.00,0.00,0.0,0.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00
38,38,Zeugmax,1,0,0.00,0.00,0.0,0.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,0.0,0.00,0.00,0.00
39,39,kastellanos,1,0,0.00,0.00,0.0,0.00,0.0,NaN,...,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,0.00
40,40,JairVillalba,1,0,0.00,0.00,75.0,75.00,62.5,NaN,...,62.5,NaN,NaN,NaN,62.50,62.5,NaN,NaN,NaN,62.50

## Bogota 2 Scores Dataframe

In [3]:
bogota2 = pd.read_csv("Bogota-2-Scores.csv")
bogota2

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,tech-phase5,total-phase5,tech-phase4,user-requirement-phase4,...,tech-phase2,user-requirement-phase2,infovis-phase2,novelty-phase2,total-phase2,tech-phase1,user-requirement-phase1,infovis-phase1,novelty-phase1,total-phase1
0,0,jusherrerama,2,20,25.00,0.00,75.0,120.00,62.5,20.0,...,62.5,20.0,29.17,50.0,161.67,25.0,20.0,37.50,0.00,82.50
1,1,bdvegat,2,20,25.00,0.00,62.5,107.50,50.0,20.0,...,50.0,20.0,25.00,0.0,95.00,0.0,0.0,0.00,0.00,0.00
2,2,Phoenixest,2,0,25.00,25.00,25.0,75.00,25.0,20.0,...,37.5,20.0,29.17,25.0,111.67,0.0,20.0,29.17,25.00,74.17
3,3,HashNick,2,40,50.00,25.00,37.5,152.50,37.5,40.0,...,50.0,0.0,33.33,25.0,108.33,0.0,NaN,NaN,NaN,0.00
4,4,ccvacad,2,80,66.67,80.00,87.5,314.17,NaN,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,0.0,0.00,0.00,0.00
5,5,joaortizro,2,100,50.00,87.50,87.5,325.00,87.5,80.0,...,87.5,60.0,33.33,87.5,268.33,62.5,20.0,25.00,0.00,107.50
6,6,juasmartinezbel,2,100,75.00,75.00,87.5,337.50,75.0,100.0,...,75.0,80.0,54.17,87.5,296.67,75.0,60.0,54.17,62.50,251.67
7,7,mdbelloc,2,0,37.50,25.00,75.0,137.50,75.0,0.0,...,75.0,0.0,25.00,25.0,125.00,37.5,0.0,29.17,25.00,91.67
8,8,diegocruz10,2,20,45.83,25.00,37.5,128.33,37.5,40.0,...,50.0,20.0,58.33,0.0,128.33,25.0,20.0,45.83,0.00,90.83
9,9,crarojasca,2,20,25.00,0.00,0.0,45.00,0.0,20.0,...,12.5,20.0,25.00,0.0,57.50,0.0,20.0,25.00,0.00,45.00
10,10,sagilm,2,20,33.33,62.50,62.5,178.33,50.0,0.0,...,37.5,0.0,33.33,0.0,70.83,25.0,0.0,25.00,0.00,50.00
11,11,idrojasf,2,20,50.00,25.00,75.0,170.00,75.0,20.0,...,37.5,60.0,45.83,25.0,168.33,62.5,20.0,62.50,62.50,207.50
12,12,raulramirezp,2,60,45.83,66.67,100.0,272.50,75.0,40.0,...,75.0,40.0,29.17,75.0,219.17,0.0,0.0,0.00,0.00,0.00
13,13,fabianr23,2,80,58.33,87.50,100.0,325.83,100.0,100.0,...,100.0,80.0,62.50,87.5,330.00,50.0,80.0,75.00,0.00,205.00
14,14,jhriverasa,2,100,58.33,60.00,100.0,318.33,75.0,100.0,...,87.5,20.0,29.17,87.5,224.17,50.0,20.0,29.17,43.75,142.92
15,15,jhonsd1996,2,20,54.17,25.00,75.0,174.17,75.0,20.0,...,75.0,NaN,NaN,NaN,75.00,50.0,0.0,25.00,25.00,100.00
16,16,JuanitoAli,2,80,58.33,65.00,62.5,265.83,62.5,100.0,...,62.5,80.0,54.17,87.5,284.17,75.0,0.0,25.00,0.00,100.00
17,17,Davsatu313,2,80,70.83,84.38,87.5,322.71,87.5,80.0,...,87.5,20.0,54.17,75.0,236.67,62.5,20.0,50.00,75.00,207.50
18,18,cesarochoa2006,2,100,66.67,72.50,87.5,326.67,87.5,60.0,...,62.5,60.0,45.83,87.5,255.83,37.5,20.0,29.17,0.00,86.67
19,19,jjmuesesq,2,20,25.00,0.00,75.0,120.00,62.5,20.0,...,50.0,20.0,29.17,87.5,186.67,37.5,20.0,25.00,0.00,82.50
20,20,jucjimenezmo,2,0,25.00,62.50,100.0,187.50,75.0,20.0,...,50.0,20.0,29.17,0.0,99.17,12.5,NaN,NaN,NaN,12.50
21,21,kancas,2,20,25.00,62.50,75.0,182.50,62.5,40.0,...,62.5,60.0,33.33,87.5,243.33,37.5,20.0,29.17,0.00,37.50
22,22,Gantiva,2,100,70.83,100.00,75.0,345.83,62.5,100.0,...,75.0,0.0,33.33,25.0,133.33,50.0,20.0,45.83,0.00,115.83
23,23,Dandarprox,2,80,58.33,37.50,100.0,275.83,75.0,80.0,...,62.5,40.0,33.33,0.0,135.83,12.5,20.0,29.17,43.75,105.42
24,24,debeltranc,2,0,25.00,25.00,75.0,125.00,50.0,0.0,...,50.0,0.0,25.00,0.0,75.00,75.0,0.0,25.00,62.50,162.50
25,25,ykchautai,2,20,41.67,75.00,75.0,211.67,75.0,20.0,...,62.5,20.0,37.50,0.0,120.00,50.0,20.0,29.17,62.50,161.67
26,26,ligibrial,2,0,33.33,25.00,87.5,145.83,62.5,0.0,...,50.0,0.0,33.33,25.0,108.33,37.5,0.0,33.33,62.50,133.33
27,27,davidrh195,2,20,25.00,0.00,50.0,95.00,62.5,20.0,...,75.0,20.0,25.00,0.0,120.00,0.0,NaN,NaN,NaN,0.00
28,28,JulianaNino,2,20,41.67,75.00,87.5,224.17,75.0,20.0,...,62.5,0.0,29.17,0.0,91.67,25.0,0.0,29.17,0.00,54.17
29,29,luegilca,2,0,37.50,0.00,62.5,100.00,62.5,0.0,...,62.5,0.0,25.00,25.0,112.50,37.5,0.0,29.17,62.50,129.17
30,30,Yelis3,2,80,66.67,62.50,100.0,309.17,87.5,80.0,...,87.5,20.0,41.67,62.5,211.67,87.5,40.0,41.67,62.50,231.67
31,31,begarzonf,2,40,25.00,75.00,87.5,227.50,75.0,40.0,...,62.5,20.0,25.00,0.0,107.50,37.5,20.0,25.00,75.00,157.50
32,32,kmendezp96,2,60,79.17,65.63,100.0,304.79,62.5,40.0,...,75.0,40.0,33.33,62.5,210.83,50.0,40.0,33.33,62.50,185.83
33,33,leguzman,2,60,79.17,100.00,100.0,339.17,100.0,40.0,...,87.5,40.0,41.67,75.0,244.17,25.0,20.0,45.83,62.50,153.33
34,34,luealfonsoru,2,0,45.83,25.00,87.5,158.33,87.5,0.0,...,87.5,0.0,25.00,25.0,137.50,62.5,0.0,29.17,62.50,154.17
35,35,oserasoa,2,0,33.33,33.33,87.5,154.17,37.5,20.0,...,37.5,0.0,33.33,25.0,95.83,25.0,0.0,29.17,0.00,54.17
36,36,lsfinite,2,0,25.00,12.50,87.5,125.00,NaN,NaN,...,50.0,0.0,25.00,25.0,100.00,12.5,0.0,25.00,25.00,62.50
37,37,xdanielsb,2,100,87.50,70.00,100.0,357.50,50.0,0.0,...,62.5,0.0,25.00,0.0,87.50,87.5,60.0,37.50,75.00,260.00
38,38,CSebasGomez,2,0,0.00,0.00,0.0,0.00,NaN,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,0.0,0.00,0.00,0.00
39,39,jhcardenasa,2,0,0.00,0.00,0.0,0.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00
40,40,tres-iqus,2,0,0.00,0.00,0.0,0.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,0.0,0.00,0.00,0.00
41,41,jscontrerasp,2,0,0.00,0.00,0.0,0.00,0.0,0.0,...,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00

## Bogota 3 Scores Dataframe

In [4]:
bogota3 = pd.read_csv("Bogota-3-Scores.csv")
bogota3

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,tech-phase5,total-phase5,tech-phase4,user-requirement-phase4,...,tech-phase2,user-requirement-phase2,infovis-phase2,novelty-phase2,total-phase2,tech-phase1,user-requirement-phase1,infovis-phase1,novelty-phase1,total-phase1
0,0,lemartinp,3,100,54.17,87.50,87.5,329.17,87.5,80.0,...,62.5,40.0,29.17,0.00,131.67,25.0,0.0,33.33,0.00,58.33
1,1,juligarji,3,100,75.00,92.50,87.5,355.00,100.0,100.0,...,87.5,40.0,45.83,68.75,242.08,50.0,20.0,29.17,62.50,161.67
2,2,nfmorenog,3,0,37.50,15.00,75.0,127.50,75.0,0.0,...,75.0,0.0,33.33,25.00,133.33,50.0,0.0,29.17,25.00,104.17
3,3,AFelipeGA,3,40,37.50,56.25,87.5,221.25,75.0,40.0,...,75.0,40.0,37.50,0.00,152.50,12.5,0.0,25.00,0.00,37.50
4,4,mballeng91,3,0,25.00,25.00,62.5,112.50,62.5,0.0,...,50.0,0.0,25.00,25.00,100.00,0.0,0.0,0.00,0.00,0.00
5,5,dduartec,3,80,83.33,95.00,87.5,345.83,87.5,0.0,...,87.5,100.0,70.83,75.00,333.33,NaN,0.0,41.67,0.00,41.67
6,6,srmedinac,3,20,33.33,0.00,75.0,128.33,62.5,20.0,...,62.5,20.0,33.33,0.00,115.83,25.0,0.0,0.00,0.00,25.00
7,7,wilson911013,3,0,25.00,0.00,50.0,75.00,37.5,20.0,...,37.5,20.0,33.33,0.00,90.83,12.5,20.0,45.83,0.00,78.33
8,8,wapiravaguens,3,80,75.00,72.50,100.0,327.50,62.5,80.0,...,62.5,80.0,50.00,0.00,192.50,62.5,60.0,54.17,62.50,239.17
9,9,davidh17,3,20,45.83,56.25,87.5,209.58,75.0,0.0,...,62.5,100.0,58.33,25.00,245.83,37.5,60.0,58.33,0.00,155.83
10,10,DianaNavarrete,3,20,62.50,25.00,37.5,145.00,37.5,20.0,...,50.0,20.0,58.33,0.00,128.33,37.5,0.0,62.50,0.00,100.00
11,11,jdmonroyg,3,0,25.00,25.00,25.0,75.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00
12,12,jorge52an,3,100,50.00,60.00,100.0,310.00,75.0,60.0,...,75.0,0.0,25.00,87.50,187.50,50.0,20.0,29.17,0.00,99.17
13,13,jscastelblancoh,3,100,83.33,100.00,75.0,358.33,75.0,100.0,...,75.0,60.0,41.67,87.50,264.17,50.0,60.0,29.17,62.50,201.67
14,14,juclopezso,3,60,50.00,81.25,87.5,278.75,62.5,60.0,...,62.5,20.0,29.17,0.00,111.67,25.0,20.0,25.00,0.00,70.00
15,15,afforeroc,3,20,29.17,50.00,62.5,161.67,50.0,20.0,...,50.0,20.0,33.33,0.00,103.33,12.5,20.0,33.33,0.00,65.83
16,16,dagofonseca,3,40,37.50,66.67,87.5,231.67,87.5,40.0,...,50.0,40.0,25.00,75.00,190.00,12.5,20.0,25.00,0.00,57.50
17,17,lacardenasv,3,100,75.00,75.00,100.0,350.00,87.5,60.0,...,62.5,60.0,54.17,87.50,264.17,62.5,20.0,29.17,75.00,186.67
18,18,oacastillol,3,60,62.50,37.50,75.0,235.00,62.5,0.0,...,62.5,0.0,29.17,25.00,116.67,NaN,0.0,29.17,62.50,91.67
19,19,ncampuzano,3,20,45.83,50.00,87.5,203.33,62.5,20.0,...,50.0,20.0,29.17,25.00,124.17,0.0,0.0,29.17,62.50,91.67
20,20,adriel62,3,80,66.67,67.50,87.5,301.67,87.5,40.0,...,87.5,20.0,33.33,62.50,203.33,25.0,20.0,33.33,25.00,103.33
21,21,capinzor,3,20,25.00,58.33,100.0,203.33,87.5,20.0,...,75.0,20.0,25.00,0.00,120.00,25.0,20.0,25.00,37.50,107.50
22,22,ofnanezn,3,40,58.33,25.00,75.0,198.33,50.0,20.0,...,50.0,20.0,37.50,25.00,132.50,12.5,0.0,0.00,0.00,12.50
23,23,macuestap,3,40,50.00,25.00,62.5,177.50,62.5,20.0,...,62.5,20.0,37.50,25.00,145.00,100.0,0.0,25.00,43.75,168.75
24,24,spenas,3,20,33.33,0.00,62.5,115.83,62.5,20.0,...,62.5,20.0,33.33,0.00,115.83,50.0,20.0,58.33,0.00,128.33
25,25,kgbayala528,3,80,50.00,81.25,87.5,298.75,62.5,60.0,...,50.0,40.0,33.33,0.00,123.33,50.0,20.0,37.50,0.00,107.50
26,26,lgmoralesa,3,100,70.83,87.50,87.5,345.83,87.5,100.0,...,87.5,60.0,58.33,62.50,268.33,62.5,20.0,29.17,25.00,136.67
27,27,ronaldsg20,3,20,45.83,12.50,100.0,178.33,100.0,20.0,...,87.5,20.0,29.17,25.00,161.67,87.5,20.0,29.17,45.83,182.50
28,28,cccristanchoc,3,20,33.33,56.25,87.5,197.08,62.5,20.0,...,50.0,20.0,33.33,0.00,103.33,25.0,20.0,29.17,0.00,74.17
29,29,jmalvarezd,3,80,75.00,93.75,100.0,348.75,87.5,60.0,...,87.5,40.0,45.83,25.00,198.33,62.5,100.0,79.17,87.50,329.17
30,30,smarquezo,3,20,33.33,57.50,75.0,185.83,62.5,20.0,...,62.5,20.0,29.17,0.00,111.67,50.0,20.0,29.17,0.00,99.17
31,31,sarizag,3,20,33.33,56.25,100.0,209.58,75.0,20.0,...,87.5,20.0,33.33,0.00,140.83,50.0,20.0,25.00,12.50,107.50
32,32,Chranium,3,20,25.00,0.00,50.0,95.00,50.0,20.0,...,62.5,20.0,25.00,0.00,107.50,0.0,20.0,25.00,0.00,45.00
33,33,DavidQP,3,80,70.83,83.33,50.0,284.17,50.0,80.0,...,50.0,20.0,50.00,0.00,120.00,37.5,20.0,54.17,0.00,111.67
34,34,afceballosr,3,80,45.83,57.50,87.5,270.83,87.5,40.0,...,50.0,20.0,33.33,0.00,103.33,50.0,20.0,25.00,25.00,120.00
35,35,lizzyt10h,3,20,54.17,81.25,100.0,255.42,100.0,0.0,...,75.0,0.0,0.00,0.00,75.00,100.0,0.0,29.17,25.00,154.17
36,36,NicolasPrr,3,100,83.33,90.00,87.5,360.83,62.5,0.0,...,50.0,0.0,25.00,25.00,100.00,62.5,0.0,25.00,25.00,112.50
37,37,jumcorredorro,3,100,62.50,75.00,87.5,325.00,87.5,80.0,...,87.5,80.0,54.17,87.50,309.17,62.5,40.0,33.33,50.00,185.83
38,38,feartheGru,3,0,0.00,0.00,0.0,0.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,12.5,NaN,NaN,NaN,12.50
39,39,Danielsv9207,3,0,0.00,0.00,0.0,0.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,50.0,NaN,NaN,NaN,50.00
40,40,JhonEmmanuelTorres,3,0,0.00,0.00,0.0,0.00,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00

In [5]:
temp1 = bogota0.append(bogota1)

In [6]:
temp2 = temp1.append(bogota2)

In [7]:
merged = temp2.append(bogota3)

## Merged Scores Dataframe - Bogota 0, 1, 2, 3

In [8]:
merged

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,...,tech-phase2,user-requirement-phase2,infovis-phase2,novelty-phase2,total-phase2,tech-phase1,user-requirement-phase1,infovis-phase1,novelty-phase1,total-phase1
0,0,fffeelipe,0,20,29.17,50.00,199.17,100.0,100.0,20.0,...,75.0,60.0,37.50,0.0,172.50,50.0,20.0,29.17,0.0,99.17
1,1,mnguzmanc,0,60,75.00,67.50,290.00,87.5,87.5,20.0,...,87.5,20.0,37.50,75.0,220.00,87.5,0.0,0.00,0.0,87.50
2,2,jmcuestasb,0,100,54.17,25.00,254.17,75.0,62.5,100.0,...,62.5,20.0,33.33,25.0,140.83,50.0,NaN,NaN,NaN,50.00
3,3,katherinsb,0,20,37.50,16.67,136.67,62.5,37.5,20.0,...,12.5,NaN,NaN,NaN,12.50,0.0,0.0,0.00,0.0,0.00
4,4,jjrodriguezn,0,60,58.33,87.50,255.83,50.0,37.5,40.0,...,62.5,20.0,29.17,0.0,111.67,0.0,NaN,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,36,NicolasPrr,3,100,83.33,90.00,360.83,87.5,62.5,0.0,...,50.0,0.0,25.00,25.0,100.00,62.5,0.0,25.00,25.0,112.50
37,37,jumcorredorro,3,100,62.50,75.00,325.00,87.5,87.5,80.0,...,87.5,80.0,54.17,87.5,309.17,62.5,40.0,33.33,50.0,185.83
38,38,feartheGru,3,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,12.5,NaN,NaN,NaN,12.50
39,39,Danielsv9207,3,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,50.0,NaN,NaN,NaN,50.00
40,40,JhonEmmanuelTorres,3,0,0.00,0.00,0.00,0.0,0.0,NaN,...,12.5,NaN,NaN,NaN,12.50,0.0,NaN,NaN,NaN,0.00

In [9]:
overall_scores = merged.fillna(0)
overall_scores

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,...,tech-phase2,user-requirement-phase2,infovis-phase2,novelty-phase2,total-phase2,tech-phase1,user-requirement-phase1,infovis-phase1,novelty-phase1,total-phase1
0,0,fffeelipe,0,20,29.17,50.00,199.17,100.0,100.0,20.0,...,75.0,60.0,37.50,0.0,172.50,50.0,20.0,29.17,0.0,99.17
1,1,mnguzmanc,0,60,75.00,67.50,290.00,87.5,87.5,20.0,...,87.5,20.0,37.50,75.0,220.00,87.5,0.0,0.00,0.0,87.50
2,2,jmcuestasb,0,100,54.17,25.00,254.17,75.0,62.5,100.0,...,62.5,20.0,33.33,25.0,140.83,50.0,0.0,0.00,0.0,50.00
3,3,katherinsb,0,20,37.50,16.67,136.67,62.5,37.5,20.0,...,12.5,0.0,0.00,0.0,12.50,0.0,0.0,0.00,0.0,0.00
4,4,jjrodriguezn,0,60,58.33,87.50,255.83,50.0,37.5,40.0,...,62.5,20.0,29.17,0.0,111.67,0.0,0.0,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,36,NicolasPrr,3,100,83.33,90.00,360.83,87.5,62.5,0.0,...,50.0,0.0,25.00,25.0,100.00,62.5,0.0,25.00,25.0,112.50
37,37,jumcorredorro,3,100,62.50,75.00,325.00,87.5,87.5,80.0,...,87.5,80.0,54.17,87.5,309.17,62.5,40.0,33.33,50.0,185.83
38,38,feartheGru,3,0,0.00,0.00,0.00,0.0,0.0,0.0,...,12.5,0.0,0.00,0.0,12.50,12.5,0.0,0.00,0.0,12.50
39,39,Danielsv9207,3,0,0.00,0.00,0.00,0.0,0.0,0.0,...,12.5,0.0,0.00,0.0,12.50,50.0,0.0,0.00,0.0,50.00
40,40,JhonEmmanuelTorres,3,0,0.00,0.00,0.00,0.0,0.0,0.0,...,12.5,0.0,0.00,0.0,12.50,0.0,0.0,0.00,0.0,0.00

## Scores Dataframe with Improvement Scores

In [10]:
overall_scores['improve-ur-12'] = overall_scores['user-requirement-phase2'] - overall_scores['user-requirement-phase1']
overall_scores['improve-ur-23'] = overall_scores['user-requirement-phase3'] - overall_scores['user-requirement-phase2']
overall_scores['improve-ur-34'] = overall_scores['user-requirement-phase4'] - overall_scores['user-requirement-phase3']
overall_scores['improve-ur-45'] = overall_scores['user-requirement-phase5'] - overall_scores['user-requirement-phase4']
overall_scores['improve-ur-15'] = overall_scores['user-requirement-phase5'] - overall_scores['user-requirement-phase1']
overall_scores['improve-ur-25'] = overall_scores['user-requirement-phase5'] - overall_scores['user-requirement-phase2']
overall_scores['improve-vis-12'] = overall_scores['infovis-phase2'] - overall_scores['infovis-phase1']
overall_scores['improve-vis-23'] = overall_scores['infovis-phase3'] - overall_scores['infovis-phase2']
overall_scores['improve-vis-34'] = overall_scores['infovis-phase4'] - overall_scores['infovis-phase3']
overall_scores['improve-vis-45'] = overall_scores['infovis-phase5'] - overall_scores['infovis-phase4']
overall_scores['improve-vis-15'] = overall_scores['infovis-phase5'] - overall_scores['infovis-phase1']
overall_scores['improve-vis-25'] = overall_scores['infovis-phase5'] - overall_scores['infovis-phase2']
overall_scores['improve-novel-12'] = overall_scores['novelty-phase2'] - overall_scores['novelty-phase1']
overall_scores['improve-novel-23'] = overall_scores['novelty-phase3'] - overall_scores['novelty-phase2']
overall_scores['improve-novel-34'] = overall_scores['novelty-phase4'] - overall_scores['novelty-phase3']
overall_scores['improve-novel-45'] = overall_scores['novelty-phase5'] - overall_scores['novelty-phase4']
overall_scores['improve-novel-15'] = overall_scores['novelty-phase5'] - overall_scores['novelty-phase1']
overall_scores['improve-novel-25'] = overall_scores['novelty-phase5'] - overall_scores['novelty-phase2']
overall_scores['improve-tech-12'] = overall_scores['tech-phase2'] - overall_scores['tech-phase1']
overall_scores['improve-tech-23'] = overall_scores['tech-phase3'] - overall_scores['tech-phase2']
overall_scores['improve-tech-34'] = overall_scores['tech-phase4'] - overall_scores['tech-phase3']
overall_scores['improve-tech-45'] = overall_scores['tech-phase5'] - overall_scores['tech-phase4']
overall_scores['improve-tech-25'] = overall_scores['tech-phase5'] - overall_scores['tech-phase2']
overall_scores['improve-tech-15'] = overall_scores['tech-phase5'] - overall_scores['tech-phase1']
overall_scores['improve-total-12'] = overall_scores['total-phase2'] - overall_scores['total-phase1']
overall_scores['improve-total-23'] = overall_scores['total-phase3'] - overall_scores['total-phase2']
overall_scores['improve-total-34'] = overall_scores['total-phase4'] - overall_scores['total-phase3']
overall_scores['improve-total-45'] = overall_scores['total-phase5'] - overall_scores['total-phase4']
overall_scores['improve-total-15'] = overall_scores['total-phase5'] - overall_scores['total-phase1']
overall_scores['improve-total-25'] = overall_scores['total-phase5'] - overall_scores['total-phase2']

overall_scores

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,...,improve-tech-34,improve-tech-45,improve-tech-25,improve-tech-15,improve-total-12,improve-total-23,improve-total-34,improve-total-45,improve-total-15,improve-total-25
0,0,fffeelipe,0,20,29.17,50.00,199.17,100.0,100.0,20.0,...,25.0,0.0,25.0,50.0,73.33,0.00,20.42,6.25,100.00,26.67
1,1,mnguzmanc,0,60,75.00,67.50,290.00,87.5,87.5,20.0,...,-12.5,0.0,0.0,0.0,132.50,16.67,8.33,45.00,202.50,70.00
2,2,jmcuestasb,0,100,54.17,25.00,254.17,75.0,62.5,100.0,...,0.0,12.5,12.5,25.0,90.83,-8.33,88.33,33.34,204.17,113.34
3,3,katherinsb,0,20,37.50,16.67,136.67,62.5,37.5,20.0,...,37.5,25.0,50.0,62.5,12.50,-12.50,128.33,8.34,136.67,124.17
4,4,jjrodriguezn,0,60,58.33,87.50,255.83,50.0,37.5,40.0,...,0.0,12.5,-12.5,50.0,111.67,-8.34,28.34,124.16,255.83,144.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,36,NicolasPrr,3,100,83.33,90.00,360.83,87.5,62.5,0.0,...,12.5,25.0,37.5,25.0,-12.50,8.33,12.50,240.00,248.33,260.83
37,37,jumcorredorro,3,100,62.50,75.00,325.00,87.5,87.5,80.0,...,0.0,0.0,0.0,25.0,123.34,20.83,-25.00,20.00,139.17,15.83
38,38,feartheGru,3,0,0.00,0.00,0.00,0.0,0.0,0.0,...,0.0,0.0,-12.5,-12.5,0.00,-12.50,0.00,0.00,-12.50,-12.50
39,39,Danielsv9207,3,0,0.00,0.00,0.00,0.0,0.0,0.0,...,0.0,0.0,-12.5,-50.0,-37.50,-12.50,0.00,0.00,-50.00,-12.50
40,40,JhonEmmanuelTorres,3,0,0.00,0.00,0.00,0.0,0.0,0.0,...,0.0,0.0,-12.5,0.0,12.50,-12.50,0.00,0.00,0.00,-12.50

In [11]:
# Remove Unnamed Columns 
overall_scores = overall_scores.loc[:, ~overall_scores.columns.str.contains('^Unnamed')]
overall_scores

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,improve-tech-34,improve-tech-45,improve-tech-25,improve-tech-15,improve-total-12,improve-total-23,improve-total-34,improve-total-45,improve-total-15,improve-total-25
0,fffeelipe,0,20,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,25.0,0.0,25.0,50.0,73.33,0.00,20.42,6.25,100.00,26.67
1,mnguzmanc,0,60,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,-12.5,0.0,0.0,0.0,132.50,16.67,8.33,45.00,202.50,70.00
2,jmcuestasb,0,100,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,0.0,12.5,12.5,25.0,90.83,-8.33,88.33,33.34,204.17,113.34
3,katherinsb,0,20,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,37.5,25.0,50.0,62.5,12.50,-12.50,128.33,8.34,136.67,124.17
4,jjrodriguezn,0,60,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,0.0,12.5,-12.5,50.0,111.67,-8.34,28.34,124.16,255.83,144.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,NicolasPrr,3,100,83.33,90.00,360.83,87.5,62.5,0.0,33.33,...,12.5,25.0,37.5,25.0,-12.50,8.33,12.50,240.00,248.33,260.83
37,jumcorredorro,3,100,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,0.0,0.0,0.0,25.0,123.34,20.83,-25.00,20.00,139.17,15.83
38,feartheGru,3,0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,-12.5,-12.5,0.00,-12.50,0.00,0.00,-12.50,-12.50
39,Danielsv9207,3,0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,-12.5,-50.0,-37.50,-12.50,0.00,0.00,-50.00,-12.50
40,JhonEmmanuelTorres,3,0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,-12.5,0.0,12.50,-12.50,0.00,0.00,0.00,-12.50

## Phase 1 - 2 Lines of Codes for All Groups

In [12]:
phase12_loc = pd.read_csv('phase12-loc.csv')
phase12_loc

           Student  add-loc-12  delete-loc-12  change-files-12
0           annipi           0              0                0
1        bsgarciac          14              9                2
2        camilo654           0              0               20
3      camilo13152           0              0                7
4      CamiloRueda           0              0                0
..             ...         ...            ...              ...
155      smarquezo           5             74                1
156         spenas          83             59                5
157      srmedinac          48            228                6
158  wapiravaguens          26             58                2
159   wilson911013           0              0                1

[160 rows x 4 columns]

In [13]:
phase12_loc_merge = pd.merge(overall_scores, phase12_loc, on=['Student'], how='outer')
phase12_loc_merge

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,improve-tech-15,improve-total-12,improve-total-23,improve-total-34,improve-total-45,improve-total-15,improve-total-25,add-loc-12,delete-loc-12,change-files-12
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,50.0,73.33,0.00,20.42,6.25,100.00,26.67,0.0,0.0,0.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,0.0,132.50,16.67,8.33,45.00,202.50,70.00,6.0,14.0,2.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,25.0,90.83,-8.33,88.33,33.34,204.17,113.34,7.0,0.0,7.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,62.5,12.50,-12.50,128.33,8.34,136.67,124.17,0.0,0.0,0.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,50.0,111.67,-8.34,28.34,124.16,255.83,144.16,104.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,25.0,123.34,20.83,-25.00,20.00,139.17,15.83,0.0,0.0,0.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,-12.5,0.00,-12.50,0.00,0.00,-12.50,-12.50,6.0,79.0,2.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,-50.0,-37.50,-12.50,0.00,0.00,-50.00,-12.50,0.0,0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,12.50,-12.50,0.00,0.00,0.00,-12.50,0.0,0.0,1.0
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

## Phase 1 - 5 Lines of Codes for All Groups

In [14]:
phase15_loc = pd.read_csv('phase15-loc.csv')
phase15_loc

           Student  add-loc-15  delete-loc-15  change-files-15
0           annipi           0              0                0
1        bsgarciac           0              0                8
2        camilo654          55             77                5
3      camilo13152           0              0               21
4      CamiloRueda           0              0                7
..             ...         ...            ...              ...
155      smarquezo          27            610                1
156         spenas          83             59                5
157      srmedinac          48            228                6
158  wapiravaguens          33             77                2
159   wilson911013           0              0                3

[160 rows x 4 columns]

In [15]:
phase15_loc_merge = pd.merge(phase12_loc_merge, phase15_loc, on=['Student'], how = 'outer')
phase15_loc_merge

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,improve-total-34,improve-total-45,improve-total-15,improve-total-25,add-loc-12,delete-loc-12,change-files-12,add-loc-15,delete-loc-15,change-files-15
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,20.42,6.25,100.00,26.67,0.0,0.0,0.0,92.0,249.0,18.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,8.33,45.00,202.50,70.00,6.0,14.0,2.0,43.0,144.0,3.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,88.33,33.34,204.17,113.34,7.0,0.0,7.0,7.0,0.0,7.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,128.33,8.34,136.67,124.17,0.0,0.0,0.0,0.0,0.0,6.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,28.34,124.16,255.83,144.16,104.0,0.0,1.0,0.0,0.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,-25.00,20.00,139.17,15.83,0.0,0.0,0.0,29.0,35.0,1.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.00,0.00,-12.50,-12.50,6.0,79.0,2.0,0.0,0.0,0.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.00,0.00,-50.00,-12.50,0.0,0.0,0.0,0.0,0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.00,0.00,0.00,-12.50,0.0,0.0,1.0,0.0,0.0,0.0
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN

## Phase 2 - 3 Lines of Codes for All Groups

In [16]:
phase23_loc = pd.read_csv('phase23-loc.csv')
phase23_loc

           Student  add-loc-23  delete-loc-23  change-files-23
0           annipi           0              0                0
1        bsgarciac           0              0                7
2        camilo654           0              0                0
3      camilo13152          21             38                2
4      CamiloRueda           0              0                0
..             ...         ...            ...              ...
155      smarquezo           0              0                0
156         spenas           0              0                0
157      srmedinac           2              2                1
158  wapiravaguens          13             18                2
159   wilson911013           0              0                0

[160 rows x 4 columns]

In [17]:
phase23_loc_merge = pd.merge(phase15_loc_merge, phase23_loc, on=['Student'], how = 'outer')
phase23_loc_merge

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,improve-total-25,add-loc-12,delete-loc-12,change-files-12,add-loc-15,delete-loc-15,change-files-15,add-loc-23,delete-loc-23,change-files-23
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,26.67,0.0,0.0,0.0,92.0,249.0,18.0,0.0,0.0,0.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,70.00,6.0,14.0,2.0,43.0,144.0,3.0,31.0,95.0,1.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,113.34,7.0,0.0,7.0,7.0,0.0,7.0,6.0,9.0,1.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,124.17,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,144.16,104.0,0.0,1.0,0.0,0.0,9.0,57.0,98.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,15.83,0.0,0.0,0.0,29.0,35.0,1.0,29.0,34.0,1.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,-12.50,6.0,79.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,-12.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,-12.50,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

## Phase 3 - 4 Lines of Codes for All Groups

In [18]:
phase34_loc = pd.read_csv('phase34-loc.csv')
phase34_loc

           Student  add-loc-34  delete-loc-34  change-files-34
0           annipi           0              0                0
1        bsgarciac         121           1279                5
2        camilo654          60            115                6
3      camilo13152          12             21                3
4      CamiloRueda           0              0                0
..             ...         ...            ...              ...
155      smarquezo          94            263                1
156         spenas           0              0                0
157      srmedinac           1              1                1
158  wapiravaguens          12             16                2
159   wilson911013           0              0                2

[160 rows x 4 columns]

In [19]:
phase34_loc_merge = pd.merge(phase23_loc_merge, phase34_loc, on=['Student'], how = 'outer')
phase34_loc_merge

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,change-files-12,add-loc-15,delete-loc-15,change-files-15,add-loc-23,delete-loc-23,change-files-23,add-loc-34,delete-loc-34,change-files-34
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,0.0,92.0,249.0,18.0,0.0,0.0,0.0,87.0,202.0,17.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,2.0,43.0,144.0,3.0,31.0,95.0,1.0,65.0,39.0,2.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,7.0,7.0,0.0,7.0,6.0,9.0,1.0,9.0,0.0,1.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,4.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,1.0,0.0,0.0,9.0,57.0,98.0,1.0,67.0,13.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,0.0,29.0,35.0,1.0,29.0,34.0,1.0,1.0,0.0,1.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Phase 4 - 5 Lines of Codes for All Groups

In [20]:
phase45_loc = pd.read_csv('phase45-loc.csv')
phase45_loc

           Student  add-loc-45  delete-loc-45  change-files-45
0           annipi           0              0                0
1        bsgarciac          69            105                6
2        camilo654           2              2                2
3      camilo13152           5              1                1
4      CamiloRueda           0              0                0
..             ...         ...            ...              ...
155      smarquezo          26            371                1
156         spenas           0              0                0
157      srmedinac           0              0                0
158  wapiravaguens           1              4                2
159   wilson911013           0              0                0

[160 rows x 4 columns]

In [21]:
phase45_loc_merge = pd.merge(phase34_loc_merge, phase45_loc, on=['Student'], how = 'outer')
phase45_loc_merge

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,change-files-15,add-loc-23,delete-loc-23,change-files-23,add-loc-34,delete-loc-34,change-files-34,add-loc-45,delete-loc-45,change-files-45
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,18.0,0.0,0.0,0.0,87.0,202.0,17.0,78.0,168.0,6.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,3.0,31.0,95.0,1.0,65.0,39.0,2.0,81.0,136.0,2.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,7.0,6.0,9.0,1.0,9.0,0.0,1.0,9.0,26.0,1.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,6.0,0.0,0.0,0.0,0.0,0.0,4.0,259.0,371.0,3.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,9.0,57.0,98.0,1.0,67.0,13.0,2.0,4.0,7.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,1.0,29.0,34.0,1.0,1.0,0.0,1.0,2.0,2.0,1.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Phase 2 - 5 Lines of Codes for All Groups

In [22]:
phase25_loc = pd.read_csv('phase25-loc.csv')
phase25_loc

           Student  add-loc-25  delete-loc-25  change-files-25
0           annipi          39             26                4
1        bsgarciac          47             74                6
2        camilo654          28             50                3
3      camilo13152           0              0                0
4      CamiloRueda           0              0                0
..             ...         ...            ...              ...
155      smarquezo          94            608                1
156         spenas           0              0                0
157      srmedinac           3              3                1
158  wapiravaguens          21             33                2
159   wilson911013           0              0                2

[160 rows x 4 columns]

In [23]:
overall_loc_scores = pd.merge(phase45_loc_merge, phase25_loc, on=['Student'], how = 'outer')
overall_loc_scores

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,change-files-23,add-loc-34,delete-loc-34,change-files-34,add-loc-45,delete-loc-45,change-files-45,add-loc-25,delete-loc-25,change-files-25
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,0.0,87.0,202.0,17.0,78.0,168.0,6.0,0.0,0.0,0.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,1.0,65.0,39.0,2.0,81.0,136.0,2.0,51.0,144.0,2.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,1.0,9.0,0.0,1.0,9.0,26.0,1.0,5.0,34.0,1.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,0.0,0.0,0.0,4.0,259.0,371.0,3.0,0.0,0.0,6.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,1.0,67.0,13.0,2.0,4.0,7.0,4.0,59.0,49.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,1.0,1.0,0.0,1.0,2.0,2.0,1.0,29.0,35.0,1.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,234.0,2.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

## Phase 1 -2 D3 components for All Groups

In [24]:
d3_phase12 = pd.read_csv('../../d3-components/d3_phase12_final.csv')
d3_phase12 = d3_phase12.loc[:, ~d3_phase12.columns.str.contains('^Unnamed')]
d3_phase12

    d3-delete-12  d3-add-12       Student
0              0          0      Chranium
1              0          3     bsgarciac
2              0          3    dsbarrerag
3              0         52    falperezgo
4              0       1015   jiapulidoar
5              0          0   kgbayala528
6              0          0  lfvalderrama
7              0          1     nfmorenog
8              0          0        oeroaq
9              0          0    ronaldsg20
10             0         59     srmedinac
11             1          2     wolfstain
12             0          5     xdanielsb

## Phase 2 - 3 D3 components for All Groups

In [25]:
d3_phase23 = pd.read_csv('../../d3-components/d3_phase23_final.csv')
d3_phase23 = d3_phase23.loc[:, ~d3_phase23.columns.str.contains('^Unnamed')]
d3_phase23

    d3-delete-23  d3-add-23       Student
0              0          0      Chranium
1              0          1  Christian7sr
2              0          6     bsgarciac
3              0          0    dsbarrerag
4              0          0    falperezgo
5              0          0   jiapulidoar
6              0          0   kgbayala528
7              0          1  lfvalderrama
8              0          0     nfmorenog
9              0         38        oeroaq
10             0          0    ronaldsg20
11             0          0     srmedinac
12             0         45     wolfstain
13             1          6     xdanielsb

## Phase 3 - 4 D3 components for All Groups

In [26]:
d3_phase34 = pd.read_csv('../../d3-components/d3_phase34_final.csv')
d3_phase34 = d3_phase34.loc[:, ~d3_phase34.columns.str.contains('^Unnamed')]
d3_phase34

    d3-delete-34  d3-add-34       Student
0              0          0      Chranium
1              0          0  Christian7sr
2              0          2     bsgarciac
3              0          0    dsbarrerag
4              0          3    falperezgo
5              0          0   jiapulidoar
6              0          4  jucjimenezmo
7              0          0   kgbayala528
8              0          0  lfvalderrama
9              0          0     nfmorenog
10             4         20        oeroaq
11             0          0    ronaldsg20
12             0          0     srmedinac
13             0          0     wolfstain
14             0          1     xdanielsb

## Phase 4 - 5 D3 Components for All Groups

In [27]:
d3_phase45 = pd.read_csv('../../d3-components/d3_phase45_final.csv')
d3_phase45 = d3_phase45.loc[:, ~d3_phase45.columns.str.contains('^Unnamed')]
d3_phase45

    d3-delete-45  d3-add-45       Student
0              0          0      Chranium
1              0          3  Christian7sr
2              0          0     bsgarciac
3              0          1    dsbarrerag
4              0          0    falperezgo
5              0          0   jiapulidoar
6              0          0  jucjimenezmo
7              0          0   kgbayala528
8              0          0  lfvalderrama
9              0          8   nabautistal
10             0          0     nfmorenog
11             7          1        oeroaq
12             0          0    ronaldsg20
13             0          0     srmedinac
14             0          0     wolfstain
15             0         11     xdanielsb

## Phase 1 - 5 D3 Components for All Groups

In [28]:
d3_phase15 = pd.read_csv('../../d3-components/d3_phase15_final.csv')
d3_phase15 = d3_phase15.loc[:, ~d3_phase15.columns.str.contains('^Unnamed')]
d3_phase15

    d3-delete-15  d3-add-15       Student
0              0          0      Chranium
1              0          4  Christian7sr
2              0          8     bsgarciac
3              0          6    dsbarrerag
4              0         59    falperezgo
5              0       1017   jiapulidoar
6              0          4  jucjimenezmo
7              0          0   kgbayala528
8              0          1  lfvalderrama
9              0          8   nabautistal
10             0          1     nfmorenog
11             0         58        oeroaq
12             0          0    ronaldsg20
13             0         59     srmedinac
14             0         50     wolfstain
15             1         27     xdanielsb

## Load Survey Data

In [10]:
import pandas as pd

survey_read = pd.read_csv('survey_final.csv', encoding='iso-8859-1')
# survey_read["Q17"].replace({"Male": "0", "Female": "1"}, inplace=True)
# survey = survey_read.loc[:, ~survey_read.columns.str.contains('^Unnamed')]
# Apply the function
survey_na = survey_read.fillna(0)
survey_Q17 = survey_na.replace({"Q17": {"Male": "0", "Female": "1"}})
survey_Q24 = survey_Q17.replace({"Q24": {"NaN": 0, "Ingeniera de software II, Group 2, Camilo Delgado, Tuesdays and Thursdays": 1, "Ingeniera de software I, Group 2, Jairo Aponte, Tuesdays (454-403) and Thursdays (401-103)": 2, "Ingeniera de software II, Group 1, Camilo Delgado, Mondays and Wednesdays": 3, "Ingeniera de software I, Group 1, Yury Nio, Mondays and Wednesdays": 4}})
survey_Q18 = survey_Q24.replace({"Q18": {"African American/Black": 1, "Asian/Pacific Islander": 2, "Hispanic/Latino": 3, "Multiracial": 4, "Native American/American Indian": 5, "White": 6, "Not Listed (please specify)": 7, "Prefer not to respond": 8}})
survey_Q10 = survey_Q18.replace({"Q10.1": {"Top 3": 1, "Top 10": 2, "Average": 3, "Below average": 4, "Bottom of the contest": 5}})
survey_Q9 = survey_Q10.replace({"Have you participated in any programming competition before (e.g. Topcoder.com, local hacking events etc.)?": 0, "Yes": 1})
survey_Q9

,Q2_Q2_1,Q2_Q2_2,Q2_Q2_3,Q2_Q2_4,Q2_Q2_5,Q2_Q2_6,Q2_Q2_7,Q2_Q2_8,Q2_Q2_9,Q2_Q2_10,...,Student,Q11.1,Q12.1,Q13.1,Q14.1,Q24,Q17,Q18,Q9,Q10.1
0,3,5,5,3,4,3,5,5,3,3,...,AFelipeGA,10,0.0,0,3,1,0,8,0,3
1,2,5,2,2,3,3,5,4,3,4,...,hsmartineza,0,0.0,5,3,2,0,3,0,3
2,3,2,6,2,2,2,6,5,3,6,...,anfmorenoso,0,0.0,8,5,3,0,3,1,3
3,4,4,3,0,0,0,6,6,5,6,...,kancas,0,0.0,0,2,2,0,3,0,3
4,1,5,5,2,2,3,5,4,3,4,...,lacardenasv,8,3.0,20,5,1,1,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,3,3,3,3,3,3,3,3,3,3,...,Christian7sr,6,6.0,8,3,2,0,3,0,3
159,2,2,2,2,2,2,2,2,2,2,...,jucjimenezmo,1,1.0,0,2,3,0,3,0,3
160,3,4,4,2,2,2,5,5,5,4,...,ofnanezn,0,0.5,25,4,1,0,3,1,3
161,5,6,6,2,4,5,4,4,4,5,...,DglyP,5,2.0,30,2,1,0,6,0,2
162,0,0,5,4,6,0,6,6,6,6,...,kastellanos,2,10.0,0,4,0,0,3,1,2

## Merge DataFrame for Scores, Lines of Codes and Phase 1 - 2 D3 Components.

In [30]:
phase12_loc_d3 = pd.merge(overall_loc_scores, d3_phase12, on=['Student'], how = 'outer')
phase12_loc_d3

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,delete-loc-34,change-files-34,add-loc-45,delete-loc-45,change-files-45,add-loc-25,delete-loc-25,change-files-25,d3-delete-12,d3-add-12
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,202.0,17.0,78.0,168.0,6.0,0.0,0.0,0.0,NaN,NaN
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,39.0,2.0,81.0,136.0,2.0,51.0,144.0,2.0,NaN,NaN
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,0.0,1.0,9.0,26.0,1.0,5.0,34.0,1.0,NaN,NaN
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,0.0,4.0,259.0,371.0,3.0,0.0,0.0,6.0,NaN,NaN
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,13.0,2.0,4.0,7.0,4.0,59.0,49.0,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,0.0,1.0,2.0,2.0,1.0,29.0,35.0,1.0,NaN,NaN
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,6.0,234.0,2.0,NaN,NaN
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN

## Merge DataFrame for Scores, Lines of Codes and Phase 2 - 3 D3 Components

In [31]:
phase23_loc_d3 = pd.merge(phase12_loc_d3, d3_phase23, on=['Student'], how = 'outer')
phase23_loc_d3

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,add-loc-45,delete-loc-45,change-files-45,add-loc-25,delete-loc-25,change-files-25,d3-delete-12,d3-add-12,d3-delete-23,d3-add-23
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,78.0,168.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,81.0,136.0,2.0,51.0,144.0,2.0,NaN,NaN,NaN,NaN
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,9.0,26.0,1.0,5.0,34.0,1.0,NaN,NaN,NaN,NaN
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,259.0,371.0,3.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,4.0,7.0,4.0,59.0,49.0,5.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,2.0,2.0,1.0,29.0,35.0,1.0,NaN,NaN,NaN,NaN
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,6.0,234.0,2.0,NaN,NaN,NaN,NaN
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN

## Merge DataFrame for Scores, Lines of Codes and Phase 3 - 4 D3 Components

In [32]:
phase34_loc_d3 = pd.merge(phase23_loc_d3, d3_phase34, on=['Student'], how = 'outer')
phase34_loc_d3

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,change-files-45,add-loc-25,delete-loc-25,change-files-25,d3-delete-12,d3-add-12,d3-delete-23,d3-add-23,d3-delete-34,d3-add-34
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,2.0,51.0,144.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,1.0,5.0,34.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,3.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,4.0,59.0,49.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,1.0,29.0,35.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,6.0,234.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

## Merge DataFrame for Scores, Lines of Codes and Phase 4 - 5 D3 Components

In [33]:
phase45_loc_d3 = pd.merge(phase34_loc_d3, d3_phase45, on=['Student'], how = 'outer')
phase45_loc_d3

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,delete-loc-25,change-files-25,d3-delete-12,d3-add-12,d3-delete-23,d3-add-23,d3-delete-34,d3-add-34,d3-delete-45,d3-add-45
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,144.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,34.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,49.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,35.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,234.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Merge DataFrame for Scores, Lines of Codes and Phase 1 - 5 D3 Components

In [34]:
phase15_loc_d3 = pd.merge(phase45_loc_d3, d3_phase15, on=['Student'], how = 'outer')
phase15_loc_d3

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,d3-delete-12,d3-add-12,d3-delete-23,d3-add-23,d3-delete-34,d3-add-34,d3-delete-45,d3-add-45,d3-delete-15,d3-add-15
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,janoguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
survey_merge = pd.merge(phase15_loc_d3, survey, on=['Student'], how = 'outer')
survey_merge

NameError: name 'survey' is not defined

In [ ]:
overall_loc_scores_final = survey_merge.fillna(0)
overall_loc_scores_final

## Calculate Effort Score for Scores and D3 Components

In [ ]:
# LOC Effort 

overall_loc_scores_final['improve-effort-12'] = overall_loc_scores_final['add-loc-12'] - 0.5 * overall_loc_scores_final['delete-loc-12']
overall_loc_scores_final['improve-effort-23'] = overall_loc_scores_final['add-loc-23'] - 0.5 * overall_loc_scores_final['delete-loc-23']
overall_loc_scores_final['improve-effort-34'] = overall_loc_scores_final['add-loc-34'] - 0.5 * overall_loc_scores_final['delete-loc-34']
overall_loc_scores_final['improve-effort-45'] = overall_loc_scores_final['add-loc-45'] - 0.5 * overall_loc_scores_final['delete-loc-45']
overall_loc_scores_final['improve-effort-15'] = overall_loc_scores_final['add-loc-15'] - 0.5 * overall_loc_scores_final['delete-loc-15']
overall_loc_scores_final['improve-effort-25'] = overall_loc_scores_final['add-loc-25'] - 0.5 * overall_loc_scores_final['delete-loc-25']

# D3 Effort

overall_loc_scores_final['d3-effort-12'] = overall_loc_scores_final['d3-add-12'] - 0.5 * overall_loc_scores_final['d3-delete-12']
overall_loc_scores_final['d3-effort-23'] = overall_loc_scores_final['d3-add-23'] - 0.5 * overall_loc_scores_final['d3-delete-23']
overall_loc_scores_final['d3-effort-34'] = overall_loc_scores_final['d3-add-34'] - 0.5 * overall_loc_scores_final['d3-delete-34']
overall_loc_scores_final['d3-effort-45'] = overall_loc_scores_final['d3-add-45'] - 0.5 * overall_loc_scores_final['d3-delete-45']
overall_loc_scores_final['d3-effort-15'] = overall_loc_scores_final['d3-add-15'] - 0.5 * overall_loc_scores_final['d3-delete-15']

## Overall DataFrame for Scores, Lines of Codes and D3 Components

In [ ]:
overall_loc_scores_final

## Descriptive Exploratory Analysis ( DEA )

>> Run correlation on overall improvement scores (Spearman Correlation)

>> Run the correlations per subgroup - to see if the picture changes there.

>> Examining the distribution of each metrics using histogram and normality test

In [ ]:
improve_d3 = overall_loc_scores_final[['d3-add-12', 'd3-delete-12', 'improve-vis-12', 'improve-novel-12','d3-add-23', 'd3-delete-23', 'improve-vis-23', 'improve-novel-23', 'd3-add-34', 'd3-delete-34', 'improve-vis-34', 'improve-novel-34','d3-add-45', 'd3-delete-45', 'improve-vis-45', 'improve-novel-45', 'd3-add-15', 'd3-delete-15', 'improve-vis-15', 'improve-novel-15']]

In [ ]:
survey = overall_loc_scores_final[['Q2_Q2_1', 'Q2_Q2_2', 'Q2_Q2_3', 
                                   'Q2_Q2_4', 'Q2_Q2_5', 'Q2_Q2_6', 
                                   'Q2_Q2_7', 'Q2_Q2_8', 'Q2_Q2_9', 
                                   'Q2_Q2_10', 'Q2_Q2_11', 'Q2_Q2_12', 
                                   'Q2_Q2_13', 'Q3_Q3_1', 'Q3_Q3_2', 'Q3_Q3_3', 'Q3_Q3_4', 'Q3_Q3_5','Q4_Q4_1', 'Q4_Q4_2', 'Q4_Q4_3', 'Q4_Q4_4', 'Q4_Q4_5', 'Q5_Q5_1', 'Q5_Q5_2', 'Q5_Q5_3', 'Q5_Q5_4', 'Q5_Q5_5', 'Q7_Q7_1',
                                   'Q7_Q7_2', 'Q7_Q7_3', 'Q7_Q7_4', 'Q8_Q8_1', 'Q8_Q8_2','Q10','improve-tech-15','improve-ur-15','improve-vis-15', 'improve-novel-15', 'improve-total-15', 'improve-tech-45','improve-ur-45','improve-vis-45', 'improve-novel-45', 'improve-total-45'
                                ]]


survey.head(5)

In [ ]:
bogota_0_survey = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([0])]
survey0 = bogota_0_survey[['Q2_Q2_1', 'Q2_Q2_2', 'Q2_Q2_3', 
                                   'Q2_Q2_4', 'Q2_Q2_5', 'Q2_Q2_6', 
                                   'Q2_Q2_7', 'Q2_Q2_8', 'Q2_Q2_9', 
                                   'Q2_Q2_10', 'Q2_Q2_11', 'Q2_Q2_12', 
                                   'Q2_Q2_13', 'Q3_Q3_1', 'Q3_Q3_2', 'Q3_Q3_3', 'Q3_Q3_4', 'Q3_Q3_5','Q4_Q4_1', 'Q4_Q4_2', 'Q4_Q4_3', 'Q4_Q4_4', 'Q4_Q4_5', 'Q5_Q5_1', 'Q5_Q5_2', 'Q5_Q5_3', 'Q5_Q5_4', 'Q5_Q5_5', 'Q7_Q7_1',
                                   'Q7_Q7_2', 'Q7_Q7_3', 'Q7_Q7_4', 'Q8_Q8_1', 'Q8_Q8_2','Q10','improve-tech-15','improve-ur-15','improve-vis-15', 'improve-novel-15', 'improve-total-15', 'improve-tech-45','improve-ur-45','improve-vis-45', 'improve-novel-45', 'improve-total-45'
                                ]]

In [ ]:
bogota_1_survey = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([1])]
survey1 = bogota_1_survey[['Q2_Q2_1', 'Q2_Q2_2', 'Q2_Q2_3', 
                                   'Q2_Q2_4', 'Q2_Q2_5', 'Q2_Q2_6', 
                                   'Q2_Q2_7', 'Q2_Q2_8', 'Q2_Q2_9', 
                                   'Q2_Q2_10', 'Q2_Q2_11', 'Q2_Q2_12', 
                                   'Q2_Q2_13', 'Q3_Q3_1', 'Q3_Q3_2', 'Q3_Q3_3', 'Q3_Q3_4', 'Q3_Q3_5','Q4_Q4_1', 'Q4_Q4_2', 'Q4_Q4_3', 'Q4_Q4_4', 'Q4_Q4_5', 'Q5_Q5_1', 'Q5_Q5_2', 'Q5_Q5_3', 'Q5_Q5_4', 'Q5_Q5_5', 'Q7_Q7_1',
                                   'Q7_Q7_2', 'Q7_Q7_3', 'Q7_Q7_4', 'Q8_Q8_1', 'Q8_Q8_2','Q10','improve-tech-15','improve-ur-15','improve-vis-15', 'improve-novel-15', 'improve-total-15', 'improve-tech-45','improve-ur-45','improve-vis-45', 'improve-novel-45', 'improve-total-45'
                                ]]

In [ ]:
bogota_2_survey = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([2])]
survey2 = bogota_2_survey[['Q2_Q2_1', 'Q2_Q2_2', 'Q2_Q2_3', 
                                   'Q2_Q2_4', 'Q2_Q2_5', 'Q2_Q2_6', 
                                   'Q2_Q2_7', 'Q2_Q2_8', 'Q2_Q2_9', 
                                   'Q2_Q2_10', 'Q2_Q2_11', 'Q2_Q2_12', 
                                   'Q2_Q2_13', 'Q3_Q3_1', 'Q3_Q3_2', 'Q3_Q3_3', 'Q3_Q3_4', 'Q3_Q3_5','Q4_Q4_1', 'Q4_Q4_2', 'Q4_Q4_3', 'Q4_Q4_4', 'Q4_Q4_5', 'Q5_Q5_1', 'Q5_Q5_2', 'Q5_Q5_3', 'Q5_Q5_4', 'Q5_Q5_5', 'Q7_Q7_1',
                                   'Q7_Q7_2', 'Q7_Q7_3', 'Q7_Q7_4', 'Q8_Q8_1', 'Q8_Q8_2','Q10','improve-tech-15','improve-ur-15','improve-vis-15', 'improve-novel-15', 'improve-total-15', 'improve-tech-45','improve-ur-45','improve-vis-45', 'improve-novel-45', 'improve-total-45'
                                ]]

In [ ]:
bogota_3_survey = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([3])]
survey3 = bogota_3_survey[['Q2_Q2_1', 'Q2_Q2_2', 'Q2_Q2_3', 
                                   'Q2_Q2_4', 'Q2_Q2_5', 'Q2_Q2_6', 
                                   'Q2_Q2_7', 'Q2_Q2_8', 'Q2_Q2_9', 
                                   'Q2_Q2_10', 'Q2_Q2_11', 'Q2_Q2_12', 
                                   'Q2_Q2_13', 'Q3_Q3_1', 'Q3_Q3_2', 'Q3_Q3_3', 'Q3_Q3_4', 'Q3_Q3_5','Q4_Q4_1', 'Q4_Q4_2', 'Q4_Q4_3', 'Q4_Q4_4', 'Q4_Q4_5', 'Q5_Q5_1', 'Q5_Q5_2', 'Q5_Q5_3', 'Q5_Q5_4', 'Q5_Q5_5', 'Q7_Q7_1',
                                   'Q7_Q7_2', 'Q7_Q7_3', 'Q7_Q7_4', 'Q8_Q8_1', 'Q8_Q8_2','Q10','improve-tech-15','improve-ur-15','improve-vis-15', 'improve-novel-15', 'improve-total-15', 'improve-tech-45','improve-ur-45','improve-vis-45', 'improve-novel-45', 'improve-total-45'
                                ]]

In [ ]:
bogota_0_d3 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([0])]
improve_d3_bogota0 = bogota_0_d3[['d3-add-12', 'd3-delete-12', 'improve-vis-12', 'improve-novel-12','d3-add-23', 'd3-delete-23', 'improve-vis-23', 'improve-novel-23', 'd3-add-34', 'd3-delete-34', 'improve-vis-34', 'improve-novel-34','d3-add-45', 'd3-delete-45', 'improve-vis-45', 'improve-novel-45', 'd3-add-15', 'd3-delete-15', 'improve-vis-15', 'improve-novel-15']]

In [ ]:
bogota_1_d3 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([1])]
improve_d3_bogota1 = bogota_1_d3[['d3-add-12', 'd3-delete-12', 'improve-vis-12', 'improve-novel-12','d3-add-23', 'd3-delete-23', 'improve-vis-23', 'improve-novel-23', 'd3-add-34', 'd3-delete-34', 'improve-vis-34', 'improve-novel-34','d3-add-45', 'd3-delete-45', 'improve-vis-45', 'improve-novel-45', 'd3-add-15', 'd3-delete-15', 'improve-vis-15', 'improve-novel-15']]

In [ ]:
bogota_2_d3 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([2])]
improve_d3_bogota2 = bogota_2_d3[['d3-add-12', 'd3-delete-12', 'improve-vis-12', 'improve-novel-12','d3-add-23', 'd3-delete-23', 'improve-vis-23', 'improve-novel-23', 'd3-add-34', 'd3-delete-34', 'improve-vis-34', 'improve-novel-34','d3-add-45', 'd3-delete-45', 'improve-vis-45', 'improve-novel-45', 'd3-add-15', 'd3-delete-15', 'improve-vis-15', 'improve-novel-15']]

In [ ]:
bogota_3_d3 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([3])]
improve_d3_bogota3 = bogota_3_d3[['d3-add-12', 'd3-delete-12', 'improve-vis-12', 'improve-novel-12','d3-add-23', 'd3-delete-23', 'improve-vis-23', 'improve-novel-23', 'd3-add-34', 'd3-delete-34', 'improve-vis-34', 'improve-novel-34','d3-add-45', 'd3-delete-45', 'improve-vis-45', 'improve-novel-45', 'd3-add-15', 'd3-delete-15', 'improve-vis-15', 'improve-novel-15']]

In [ ]:
improve_scores = overall_loc_scores_final[['improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45',
                             'improve-tech-15', 'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                             'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                             'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_0 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([0])]
improve_scores_bogota0 = bogota_0[['improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_1 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([1])]
improve_scores_bogota1 = bogota_1[['improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_2 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([2])]
improve_scores_bogota2 = bogota_2[['improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_3 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([3])]
improve_scores_bogota3 = bogota_3[['improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns


def corr_sig(df=None):
    p_matrix = np.zeros(shape=(df.shape[1],df.shape[1]))
    for col in df.columns:
        for col2 in df.drop(col,axis=1).columns:
            _ , p = stats.pearsonr(df[col],df[col2])
            p_matrix[df.columns.to_list().index(col),df.columns.to_list().index(col2)] = p
    return p_matrix


def plot_cor_matrix(corr, mask=None):
    f, ax = plt.subplots(figsize=(18, 16))
    sns.heatmap(corr, ax=ax,
                mask=mask,
                # cosmetics
                annot=True, vmin=-1, vmax=1, center=0,
                cmap='coolwarm', linewidths=2, linecolor='black', cbar_kws={'orientation': 'horizontal'})

## Correlation between Overall Survey Results and Overall Scores

In [ ]:
corr = survey.corr(method='spearman')                            # get correlation
p_values = corr_sig(survey)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 0 Survey Results and Bogota 0 Scores

In [ ]:
corr = survey0.corr(method='spearman')                            # get correlation
p_values = corr_sig(survey0)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 1 Survey Results and Bogota 1 Scores

In [ ]:
corr = survey1.corr(method='spearman')                            # get correlation
p_values = corr_sig(survey1)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 2 Survey Results and Bogota 2 Scores

In [ ]:
corr = survey2.corr(method='spearman')                            # get correlation
p_values = corr_sig(survey2)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 3 Survey Results and Bogota 3 Scores

In [ ]:
corr = survey3.corr(method='spearman')                            # get correlation
p_values = corr_sig(survey3)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Overall Scores and Overall D3 Components

In [ ]:
corr = improve_d3.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_d3)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 0 Scores and Bogota 0 D3 Components

In [ ]:
corr = improve_d3_bogota0.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_d3_bogota0)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 1 Scores and Bogota 1 D3 Components

In [ ]:
corr = improve_d3_bogota1.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_d3_bogota1)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 2 Scores and Bogota 2 D3 Components

In [ ]:
corr = improve_d3_bogota2.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_d3_bogota2)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Correlation between Bogota 3 Scores and Bogota 3 D3 Components

In [ ]:
corr = improve_d3_bogota3.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_d3_bogota3)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

In [ ]:
corr = improve_scores.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Overall Correlation between Different Score Dimensions

In [ ]:
corr = improve_scores.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Overall Sample

>> **The goal is to see whether the different subscores are correlated with each other in the overall sample.**

>> * improve-tech-15 with improve-ur-15 ( 0.28 ) - low correlate 

>> * improve-tech-15 with improve-vis-15 ( 0.33 ) - moderate correlation 

>> * improve-tech-15 with improve-novelty-15 ( 0.38 ) - moderate correlation 

>> **We only see low and moderate correlations, so using improve-total-15 is maybe not appropriate.**

>> * improve-total-15 with improve-tech-15 ( 0.66 ) - high correlation 

>> * improve-total-15 with improve-novel-15 ( 0.79 ) - high correlation 

>> * improve-total-15 with improve-vis-15 ( 0.74 ) - high correlation

>> * improve-total-15 with improve-ur-15 ( 0.8 ) - high correlation 

>> **All of the other score dimensions have high correlations with improve-total-15.**

## Bogota 0 Correlation between Different Score Dimensions

In [ ]:
corr = improve_scores_bogota0.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota0)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 0 ( No Transparency ) 

>> **The goal is to see whether the different subscores are correlated with each other in the overall sample.** 

>> * improve-tech-15 with improve-ur-15 ( 0.48 ) - moderate correlate 

>> * improve-tech-15 with improve-vis-15 ( 0.55 ) - high correlation 

>> * improve-tech-15 with improve-novelty-15 ( 0.63 ) - high correlation 

>> **We only see moderate and high correlations among the subscores.**

>> * improve-total-15 with improve-tech-15 ( 0.75 ) - high correlation

>> * improve-total-15 with improve-novel-15 ( 0.84 ) - high correlation

>> * improve-total-15 with improve-vis-15 ( 0.82 ) - high correlation

>> * improve-total-15 with improve-ur-15 ( 0.86 ) - high correlation

>> **All of the other score dimensions have high correlations with improve-total-15.**

## Bogota 1 Correlation between Different Score Dimensions

In [ ]:
corr = improve_scores_bogota1.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota1)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 1 ( Performance Transparency ) 

>> **The goal is to see whether the different subscores are correlated with each other in the overall sample.**

>> * improve-tech-15 with improve-ur-15 - not even significant 

>> * improve-tech-15 with improve-vis-15 ( 0.24 ) - low correlation

>> * improve-tech-15 with improve-novelty-15 ( 0.32 ) - moderate correlation 

>> **We only see low and moderate correlations among the subscores, not sure if improve-total-15 is appropriate.**

>> * improve-total-15 with improve-tech-15 ( 0.69 ) - high correlation

>> * improve-total-15 with improve-novel-15 ( 0.77 ) - high correlation

>> * improve-total-15 with improve-vis-15 ( 0.65 ) - high correlation

>> * improve-total-15 with improve-ur-15 ( 0.68 ) - high correlation

>> **All of the other score dimensions have high correlations with improve-total-15.**

## Bogota 2 Correlation between Different Score Dimensions

In [ ]:
corr = improve_scores_bogota2.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota2)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 2 ( Solution Transparency )

>> **The goal is to see whether the different subscores are correlated with each other in the overall sample.** 

>> * improve-tech-15 with improve-ur-15 - not even significant 

>> * improve-tech-15 with improve-vis-15 ( 0.28 ) - low correlation

>> * improve-tech-15 with improve-novelty-15 - not even significant 

>> **We only see low correlation among the subscores, not sure if improve-total-15 is appropriate.**

>> * improve-total-15 with improve-tech-15 ( 0.6 ) - high correlation

>> * improve-total-15 with improve-novel-15 ( 0.78 ) - high correlation

>> * improve-total-15 with improve-vis-15 ( 0.69 ) - high correlation

>> * improve-total-15 with improve-ur-15 ( 0.78 ) - high correlation

>> **All of the other score dimensions have high correlations with improve-total-15.**

## Bogota 3 Correlation between Different Score Dimensions

In [ ]:
corr = improve_scores_bogota3.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota3)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 3 ( Full Transparency )

>> **The goal is to see whether the different subscores are correlated with each other in the overall sample.** 

>> * improve-tech-15 with improve-ur-15 - not even significant 

>> * improve-tech-15 with improve-vis-15  - not even significant 

>> * improve-tech-15 with improve-novelty-15 - 0.26 (low correlation)

>> **We only see low correlation among the subscores, not sure if improve-total-15 is appropriate.**

>> * improve-total-15 with improve-tech-15 ( 0.53 ) - high correlation

>> * improve-total-15 with improve-novel-15 ( 0.71 ) - high correlation

>> * improve-total-15 with improve-vis-15 ( 0.69 ) - high correlation

>> * improve-total-15 with improve-ur-15 ( 0.83 ) - high correlation

>> **All of the other score dimensions have high correlations with improve-total-15.**

## Inference

>> The overall sample is not representative of the subgroups in terms of the innovation performance score. For example, we see correlations that are not significant in the Bogota 3, which is the full transparency group. However, we see low and moderate correlations on the overall sample. For the case of Bogota 0 ( No Transparency ), however, we see moderate to high correlations.

In [ ]:
improve_scores = overall_loc_scores_final[['improve-effort-12', 
                            'improve-effort-23', 'improve-effort-34', 'improve-effort-45', 'improve-effort-15', 'improve-effort-25','add-loc-12', 'delete-loc-12', 'change-files-12', 
                            'add-loc-23', 'delete-loc-23', 'change-files-23', 
                            'add-loc-34', 'delete-loc-34', 'change-files-34', 
                            'add-loc-45', 'delete-loc-45', 'change-files-45', 
                            'add-loc-15', 'delete-loc-15', 'change-files-15', 
                            'add-loc-25', 'delete-loc-25', 'change-files-25',
                            'improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_0 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([0])]
improve_scores_bogota0 = bogota_0[[ 'improve-effort-12', 
                            'improve-effort-23', 'improve-effort-34', 'improve-effort-45', 'improve-effort-25','improve-effort-15','add-loc-12', 'delete-loc-12', 'change-files-12', 
                            'add-loc-23', 'delete-loc-23', 'change-files-23', 
                            'add-loc-34', 'delete-loc-34', 'change-files-34', 
                            'add-loc-45', 'delete-loc-45', 'change-files-45', 
                            'add-loc-15', 'delete-loc-15', 'change-files-15',
                            'add-loc-25', 'delete-loc-25', 'change-files-25',
                            'improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_1 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([1])]
improve_scores_bogota1 = bogota_1[['improve-effort-12', 
                            'improve-effort-23', 'improve-effort-34', 'improve-effort-45', 'improve-effort-25','improve-effort-15','add-loc-12', 'delete-loc-12', 'change-files-12', 
                            'add-loc-23', 'delete-loc-23', 'change-files-23', 
                            'add-loc-34', 'delete-loc-34', 'change-files-34', 
                            'add-loc-45', 'delete-loc-45', 'change-files-45', 
                            'add-loc-15', 'delete-loc-15', 'change-files-15',
                            'add-loc-25', 'delete-loc-25', 'change-files-25',
                            'improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_2 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([2])]
improve_scores_bogota2 = bogota_2[['improve-effort-12', 
                            'improve-effort-23', 'improve-effort-34', 'improve-effort-45', 'improve-effort-25','improve-effort-15','add-loc-12', 'delete-loc-12', 'change-files-12', 
                            'add-loc-23', 'delete-loc-23', 'change-files-23', 
                            'add-loc-34', 'delete-loc-34', 'change-files-34', 
                            'add-loc-45', 'delete-loc-45', 'change-files-45', 
                            'add-loc-15', 'delete-loc-15', 'change-files-15',
                            'add-loc-25', 'delete-loc-25', 'change-files-25',
                            'improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
bogota_3 = overall_loc_scores_final[overall_loc_scores_final['Group'].isin([3])]
improve_scores_bogota3 = bogota_3[['improve-effort-12', 
                            'improve-effort-23', 'improve-effort-34', 'improve-effort-45', 'improve-effort-25', 'improve-effort-15','add-loc-12', 'delete-loc-12', 'change-files-12', 
                            'add-loc-23', 'delete-loc-23', 'change-files-23', 
                            'add-loc-34', 'delete-loc-34', 'change-files-34', 
                            'add-loc-45', 'delete-loc-45', 'change-files-45', 
                            'add-loc-15', 'delete-loc-15', 'change-files-15', 
                            'add-loc-25', 'delete-loc-25', 'change-files-25',
                            'improve-tech-12', 'improve-tech-23', 'improve-tech-34', 'improve-tech-45', 'improve-tech-15',
                           'improve-novel-12', 'improve-novel-23', 'improve-novel-34', 
                            'improve-novel-45', 'improve-novel-15', 'improve-vis-12', 'improve-vis-23', 
                            'improve-vis-34', 'improve-vis-45', 'improve-vis-15', 'improve-ur-12', 
                            'improve-ur-23', 'improve-ur-34', 'improve-ur-45', 'improve-ur-15', 
                            'improve-total-12', 'improve-total-23', 'improve-total-34', 'improve-total-45', 
                            'improve-total-15']]

In [ ]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns


def corr_sig(df=None):
    p_matrix = np.zeros(shape=(df.shape[1],df.shape[1]))
    for col in df.columns:
        for col2 in df.drop(col,axis=1).columns:
            _ , p = stats.pearsonr(df[col],df[col2])
            p_matrix[df.columns.to_list().index(col),df.columns.to_list().index(col2)] = p
    return p_matrix


def plot_cor_matrix(corr, mask=None):
    f, ax = plt.subplots(figsize=(26, 24))
    sns.heatmap(corr, ax=ax,
                mask=mask,
                # cosmetics
                annot=True, vmin=-1, vmax=1, center=0,
                cmap='coolwarm', linewidths=2, linecolor='black', cbar_kws={'orientation': 'horizontal'})

## Overall Correlation between Different Score Dimensions and Lines of Codes

In [ ]:
corr = improve_scores.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Overall Sample

• The goal is to see whether the different subscores are correlated with each other in the overall sample. 

>> **The goal is to see whether the different types of loc are correlated with each other in the overall sample.**

>> * add-loc-15 with delete-loc-15 - ( 0.89 ) - high correlation

>> * add-loc-15 with change-files-15 ( 0.5 ) - high correlation

>> **We see high correlations of add-loc-15 with delete-loc-15 and change-files-15.**

>> * improve-effort-15 with add-loc-15 - not even significant 

>> * improve-effort-15 with change-files-15 - not even significant 

>> * improve-effort-15 with delete-loc-15 - (-0.47) - moderate negative correlation

>> **We see correlations that are not significant and negative correlations with improve-effort-15**

## Bogota 0 Correlation between LOC and Different Score Dimensions

In [ ]:
corr = improve_scores_bogota0.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota0)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 0 ( No Transparency )

>> **The goal is to see whether the different types of loc are correlated with each other in the overall sample.**

>> * add-loc-15 with delete-loc-15 - ( 0.96 ) - high correlation

>> * add-loc-15 with change-files-15 ( 0.9 ) - high correlation

>> **We see high correlations with add-loc-15 for both delete-loc-15 and change-files-15.**

>> * improve-effort-15 with add-loc-15 - not even significant 

>> * improve-effort-15 with delete-loc-15 - ( -0.43 )( negative moderate correlation )

>> * improve-effort-15 with change-files-15 = not even significant 

>> **We see correlations that are not significant and negative correlations with improve-effort-15**

## Bogota 1 Correlation between LOC and Different Score Dimensions

In [ ]:
corr = improve_scores_bogota1.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota1)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 1 ( Performance Transparency )

>> **The goal is to see whether the different types of loc are correlated with each other in the overall sample.**

>> * add-loc-15 with delete-loc-15 - ( 0.85 ) - high correlation

>> * add-loc-15 with change-files-15 ( 0.53 ) - high correlation

>> **We see high correlations with add-loc-15 for both delete-loc-15 and change-files-15.** 

>> * improve-effort-15 with add-loc-15 - not even significant

>> * improve-effort-15 with delete-loc-15 - ( -0.58 ) - high negative correlation 

>> * improve-effort-15 with change-files-15 - not even significant 

>> **We see correlations that are not significant and negative correlations with improve-effort-15.**

## Bogota 2 Correlation between LOC and Different Score Dimensions

In [ ]:
corr = improve_scores_bogota2.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota2)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 2 ( Solution Transparency )

>> **The goal is to see whether the different types of loc are correlated with each other in the overall sample.**

>> * add-loc-15 with delete-loc-15 - ( 0.94 ) - high correlation

>> * add-loc-15 with change-files-15 ( 0.64 ) - high correlation

>> **We see high correlations with add-loc-15 for both delete-loc-15 and change-files-15.**

>> * improve-effort-15 with add-loc-15 - not even significant

>> * improve-effort-15 with delete-loc-15 - (-0.32) - ( moderate negative correlation )

>> * improve-effort-15 with change-files-15 - not even significant

>> **We see correlations that are not significant and moderate negative correlation.**

## Bogota 3 Correlation between LOC and Different Score Dimensions

In [ ]:
corr = improve_scores_bogota3.corr(method='spearman')                            # get correlation
p_values = corr_sig(improve_scores_bogota3)                     # get p-Value
mask = np.invert(np.tril(p_values<0.05))    # mask - only get significant corr
plot_cor_matrix(corr,mask)

## Interpretation Bogota 3 ( Full Transparency )

>> **The goal is to see whether the different types of loc are correlated with each other in the overall sample.**

>> * add-loc-15 with delete-loc-15 - ( 0.74 ) - high correlation

>> * add-loc-15 with change-files-15 ( 0.43 ) - moderate correlation

>> **We see high correlation and moderate correlation with add-loc-15.**

>> * improve-effort-15 with add-loc-15 - not even significant

>> * improve-effort-15 with delete-loc-15 - (-0.32) - ( moderate negative correlation )

>> * improve-effort-15 with change-files-15 - not even significant

>> **We see correlations that are not significant and moderate negative correlation.**

## improve-tech-15 Box Plot

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='improve-tech-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.swarmplot(x="Group", y="improve-tech-15", data=overall_loc_scores_final, color='#7d0013')
plt.show()

>> Note: We want to have the linechart for each subgroups,   
   x-axis is the phases, 
   y-axis is the raw tech score, 
   legend we will have the groups   
   Interpretation: The 2 transparency conditions
   (2) and (3) seems to be improving more on tech. The median is higher.

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['tech-phase1'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['tech-phase2'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['tech-phase3'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['tech-phase4'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['tech-phase5'].mean()

## improve-tech-15 line charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [ Tech Scores ]

y1 = [28.85, 46.15, 43.59, 47.76, 54.81]
y2 = [39.02, 57.93, 57.01, 61.28, 64.02]
y3 = [33.33, 56.85, 55.29, 56.25, 69.94]
y4 = [36.59, 60.37, 60.06, 64.63, 73.78]   

x_axis=['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4', 'Phase 5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean Scores of Tech Scores for All Treatment Groups")
plt.ylabel("Mean Scores")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

In [ ]:
overall_loc_scores_tech = overall_loc_scores_final[["tech-phase1", "tech-phase2", "tech-phase3", "tech-phase4", "tech-phase5"]]

# lines = overall_loc_scores_tech.plot.line()

overall_loc_scores_tech

## improve-vis-15 Box Plot

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='improve-vis-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.swarmplot(x="Group", y="improve-vis-15", data=overall_loc_scores_final, color='#7d0013')
plt.show()

>> Note: We want to have the linechart for each subgroups,   
   x-axis is the phases, 
   y-axis is the raw tech score, 
   legend we will have the groups   
   Interpretation: The baseline condition (1) seems to be highest in terms of improving on vis. Could be a skills.      effect. Check correlation with effort, LOC.

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['infovis-phase1'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['infovis-phase2'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['infovis-phase3'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['infovis-phase4'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['infovis-phase5'].mean()

## improve-vis-15 line charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [Vis Scores ]

y1 = [14.64, 26.07, 31.09, 32.59, 36.11]
y2 = [32.01, 33.94, 37.60, 42.38, 44.51]
y3 = [26.39, 29.76, 35.42, 36.61, 42.16]
y4 = [29.27, 33.13, 36.58, 35.67, 47.05]   

x_axis=['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4', 'Phase 5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean Scores of Vis Scores for All Treatment Groups")
plt.ylabel("Mean Scores")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

## improve-ur-15 Box Plot

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='improve-ur-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.swarmplot(x="Group", y="improve-ur-15", data=overall_loc_scores_final, color='#7d0013')
plt.show()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['user-requirement-phase1'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['user-requirement-phase2'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['user-requirement-phase3'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['user-requirement-phase4'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['user-requirement-phase5'].mean()

## improve-ur-15 Line Charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [ UR Scores ]

y1 = [8.72, 13.33, 24.62, 23.08, 32.82]
y2 = [20.49, 24.39, 32.2, 36.1, 38.54]
y3 = [14.29, 21.43, 29.52, 33.33, 37.62]
y4 = [17.07, 27.8, 29.27, 33.17, 46.34]   

x_axis=['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4', 'Phase 5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean Scores of UR Scores for All Treatment Groups")
plt.ylabel("Mean Scores")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

## improve-novel-15 Box Plots

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='improve-novel-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.swarmplot(x="Group", y="improve-novel-15", data=overall_loc_scores_final, color='#7d0013')
plt.show()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['novelty-phase1'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['novelty-phase2'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['novelty-phase3'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['novelty-phase4'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['novelty-phase5'].mean()

## improve-novel-15 Line Charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [ Novelty Scores ]

y1 = [8.97, 22.12, 27.08, 29.49, 39.12]
y2 = [26.81, 34.3, 40.7, 38.56, 46.97]
y3 = [24.7, 32.14, 30.26, 29.04, 42.8]
y4 = [19.87, 23.02, 25.3, 30.6, 50.7]   

x_axis=['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4', 'Phase 5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean Scores of Novelty Scores for All Treatment Groups")
plt.ylabel("Mean Scores")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

## add-loc-15 Box Plots

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='add-loc-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.swarmplot(x="Group", y="add-loc-15", data=overall_loc_scores_final, color='#7d0013')
plt.show()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['add-loc-15'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['add-loc-12'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['add-loc-23'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['add-loc-34'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['add-loc-45'].mean()

## add-loc-15 line charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [ Novelty Scores ]

y1 = [15.41, 19.1, 19.1, 19.3]
y2 = [12.02, 19.56, 24.22, 12.02]
y3 = [12.02, 12.12, 19.98, 9.52]
y4 = [25.61, 19.71, 29.73, 37.22]   

x_axis=['Phase 1-2', 'Phase 2-3', 'Phase 3-4', 'Phase 4-5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean of Line Added for All Treatment Groups")
plt.ylabel("Mean Scores")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

## delete-loc-15 Box Plot

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='delete-loc-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.stripplot(x="Group", y="delete-loc-15", data=overall_loc_scores_final, color='#7d0013')
plt.show()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['delete-loc-15'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['delete-loc-12'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['delete-loc-23'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['delete-loc-34'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['delete-loc-45'].mean()

## delete-loc-15 Line Charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [ Novelty Scores ]

y1 = [28.28, 14.59, 56.10, 29.38]
y2 = [22.88, 38.29, 56.90, 22.88]
y3 = [32.86, 32.17, 28.93, 22.83]
y4 = [51.98, 31.34, 81.68, 34.46]   

x_axis=['Phase 1-2', 'Phase 2-3', 'Phase 3-4', 'Phase 4-5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean of Lines Deleted for All Treatment Groups")
plt.ylabel("Mean Scores")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

## improve-effort-15 Box Plots

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='improve-effort-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.stripplot(x="Group", y='improve-effort-15', data=overall_loc_scores_final, color='#7d0013')
plt.show()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['improve-effort-15'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['improve-effort-12'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['improve-effort-23'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['improve-effort-34'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['improve-effort-45'].mean()

## improve-effort-15 Line Charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [ Novelty Scores ]

y1 = [1.27, 11.81, -8.95, 4.64]
y2 = [0.59, 0.41, -4.23, 0.59]
y3 = [-4.40, -3.96, 5.51, -1.89]
y4 = [-0.38, 4.04, -11.11, 19.99]   

x_axis=['Phase 1-2', 'Phase 2-3', 'Phase 3-4', 'Phase 4-5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean of Effort for All Treatment Groups")
plt.ylabel("Mean Scores")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

## change-files-15 Box Plots

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
ax = sns.boxplot(x='Group', y='change-files-15', data=overall_loc_scores_final, color='#99c2a2')
ax = sns.stripplot(x="Group", y='change-files-15', data=overall_loc_scores_final, color='#7d0013')
plt.show()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['change-files-15'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['change-files-12'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['change-files-23'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['change-files-34'].mean()

In [ ]:
overall_loc_scores_final.groupby('Group', as_index=False)['change-files-45'].mean()

## change-files-15 Line Charts

In [ ]:
import matplotlib.pyplot as plt

# Mean Scores of All Groups [ Novelty Scores ]

y1 = [1.27, 11.81, -8.95, 4.64]
y2 = [0.59, 0.41, -4.23, 0.59]
y3 = [-4.40, -3.96, 5.51, -1.89]
y4 = [-0.38, 4.04, -11.11, 19.99]   

x_axis=['Phase 1-2', 'Phase 2-3', 'Phase 3-4', 'Phase 4-5']

line1 = plt.plot(x_axis, y1,'ko-',label='Bogota 0 ( No Transparency )')
line2 = plt.plot(x_axis, y2,'ro-',label='Bogota 1 ( Performance Transparency )') 
line3 = plt.plot(x_axis, y3,'mo-',label='Bogota 2 ( Solution Transparency )')
line3 = plt.plot(x_axis, y4,'bo-',label='Bogota 3 ( Full Transparency )')

plt.title("Mean of Change Files for All Treatment Groups")
plt.ylabel("Mean Change Files")

plt.legend(bbox_to_anchor=(1, 1),
           bbox_transform=plt.gcf().transFigure)

## Calculate one-way anove for each variable (each column) based on the "Group" column.

In [ ]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

dropped_student = overall_loc_scores_final.drop('Student', axis=1)
df_long = dropped_student.melt(id_vars="Group")

df_long

In [ ]:
df_long.to_csv('long.csv')

In [ ]:
def aov_func(x):
    model = ols('value ~ Group', data=x).fit()
    return sm.stats.anova_lm(model)
        
output_df = df_long.groupby("variable").apply(aov_func)
output_df

## List of Variables that are Significant [ Less than or Equal to 0.05 ]

In [ ]:
output_df.loc[(output_df['PR(>F)'] <= 0.05)]

> Interpretation - improve-tech-15 mean score highest for Bogota 3

In [ ]:
print(overall_loc_scores_final['improve-tech-15'].loc[overall_loc_scores_final['Group'] == 0].mean())
print(overall_loc_scores_final['improve-tech-15'].loc[overall_loc_scores_final['Group'] == 1].mean())
print(overall_loc_scores_final['improve-tech-15'].loc[overall_loc_scores_final['Group'] == 2].mean())
print(overall_loc_scores_final['improve-tech-15'].loc[overall_loc_scores_final['Group'] == 3].mean())

> Interpretation - improve-novel-45 mean score highest for Bogota 3

In [ ]:
print(overall_loc_scores_final['improve-novel-45'].loc[overall_loc_scores_final['Group'] == 0].mean())
print(overall_loc_scores_final['improve-novel-45'].loc[overall_loc_scores_final['Group'] == 1].mean())
print(overall_loc_scores_final['improve-novel-45'].loc[overall_loc_scores_final['Group'] == 2].mean())
print(overall_loc_scores_final['improve-novel-45'].loc[overall_loc_scores_final['Group'] == 3].mean())

> Interpretation - improve-vis-45 mean score highest for Bogota 3

In [ ]:
print(overall_loc_scores_final['improve-vis-45'].loc[overall_loc_scores_final['Group'] == 0].mean())
print(overall_loc_scores_final['improve-vis-45'].loc[overall_loc_scores_final['Group'] == 1].mean())
print(overall_loc_scores_final['improve-vis-45'].loc[overall_loc_scores_final['Group'] == 2].mean())
print(overall_loc_scores_final['improve-vis-45'].loc[overall_loc_scores_final['Group'] == 3].mean())

> Interpretation - improve-total-45 mean score highest for Bogota 3

In [ ]:
print(overall_loc_scores_final['improve-total-45'].loc[overall_loc_scores_final['Group'] == 0].mean())
print(overall_loc_scores_final['improve-total-45'].loc[overall_loc_scores_final['Group'] == 1].mean())
print(overall_loc_scores_final['improve-total-45'].loc[overall_loc_scores_final['Group'] == 2].mean())
print(overall_loc_scores_final['improve-total-45'].loc[overall_loc_scores_final['Group'] == 3].mean())

## Post-Hoc Test [ Section to be Ignored ]

In [ ]:
import pingouin as pg
from pingouin import pairwise_ttests

posthocs = pairwise_ttests(dv='improve-effort-25', between='Group', padjust='bonf', data=overall_loc_scores_final, correction=True)
posthocs

In [ ]:
pg.pairwise_gameshowell(data=overall_loc_scores_final, dv='improve-effort-25', between='Group')

In [ ]:
import statsmodels.stats.multicomp as mc
import scipy.stats as stats

comp = mc.MultiComparison(overall_loc_scores_final['improve-effort-25'], overall_loc_scores_final['Group'])

tb1, a1, a2 = comp.allpairtest(stats.ttest_ind, method='bonferroni')
tb1

In [ ]:
import statsmodels.stats.multicomp as mc
import scipy.stats as stats

comp = mc.MultiComparison(overall_loc_scores_final['improve-tech-15'], overall_loc_scores_final['Group'])

tb1, a1, a2 = comp.allpairtest(stats.ttest_ind, method='bonferroni')
tb1

In [ ]:
import statsmodels.stats.multicomp as mc
import scipy.stats as stats

comp = mc.MultiComparison(overall_loc_scores_final['improve-novel-45'], overall_loc_scores_final['Group'])

tb1, a1, a2 = comp.allpairtest(stats.ttest_ind, method='bonferroni')
tb1

In [ ]:
import statsmodels.stats.multicomp as mc
import scipy.stats as stats

comp = mc.MultiComparison(overall_loc_scores_final['improve-vis-45'], overall_loc_scores_final['Group'])

tb1, a1, a2 = comp.allpairtest(stats.ttest_ind, method='bonferroni')
tb1

In [ ]:
import statsmodels.stats.multicomp as mc
import scipy.stats as stats

comp = mc.MultiComparison(overall_loc_scores_final['improve-total-15'], overall_loc_scores_final['Group'])

tb1, a1, a2 = comp.allpairtest(stats.ttest_ind, method='bonferroni')
tb1

In [ ]:
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=overall_loc_scores_final['improve-effort-25'],
                          groups=overall_loc_scores_final['Group'],
                          alpha=0.05)

#display results
print(tukey)

In [ ]:
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=overall_loc_scores_final['improve-novel-45'],
                          groups=overall_loc_scores_final['Group'],
                          alpha=0.05)

#display results
print(tukey)

In [ ]:
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=overall_loc_scores_final['Q5_Q5_3'],
                          groups=overall_loc_scores_final['Group'],
                          alpha=0.05)

#display results
print(tukey)

In [ ]:
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=overall_loc_scores_final['improve-tech-15'],
                          groups=overall_loc_scores_final['Group'],
                          alpha=0.05)

#display results
print(tukey)

In [ ]:
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=overall_loc_scores_final['improve-vis-45'],
                          groups=overall_loc_scores_final['Group'],
                          alpha=0.05)

#display results
print(tukey)

In [ ]:
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=overall_loc_scores_final['improve-total-45'],
                          groups=overall_loc_scores_final['Group'],
                          alpha=0.05)

#display results
print(tukey)

In [ ]:
output_df.to_csv('output.csv')

### Cronbach’s Alpha ( Internal Consistency )

0.9 ≤ α	Excellent

0.8 ≤ α < 0.9	Good

0.7 ≤ α < 0.8	Acceptable

0.6 ≤ α < 0.7	Questionable

0.5 ≤ α < 0.6	Poor

α < 0.5	Unacceptable

In [ ]:
# 95% confidence interval for Cronbach's alpha

import pingouin as pg

dropped_student_group = overall_loc_scores_final.drop(['Student', 'Group'], axis=1)

pg.cronbach_alpha(data=dropped_student_group)

## Adequacy Test

Before you perform factor analysis, you need to evaluate the “factorability” of our dataset. Factorability means "can we found the factors in the dataset?". There are two methods to check the factorability or sampling adequacy:


* Bartlett’s Test
* Kaiser-Meyer-Olkin Test

Bartlett’s test of sphericity checks whether or not the observed variables intercorrelate at all using the observed correlation matrix against the identity matrix. If the test found statistically insignificant, you should not employ a factor analysis.

In [ ]:
# In this Bartlett ’s test, the p-value is 0. The test was statistically significant, 
# indicating that the observed correlation matrix is not an identity matrix.

from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(dropped_student_group)
p_value

In [ ]:
# Kaiser-Meyer-Olkin (KMO) Test measures the suitability of data for factor analysis. 
# It determines the adequacy for each observed variable and for the complete model. 
# KMO estimates the proportion of variance among all the observed variable. 
# Lower proportion id more suitable for factor analysis. KMO values range between 0 and 1. 
# Value of KMO less than 0.6 is considered inadequate.

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(dropped_student_group)
kmo_model

## Factor Analysis Phase 1 - 5 [ All Groups ]

In [ ]:
df_phase15 = dropped_student_group[['improve-novel-15', 'improve-vis-15', 'improve-ur-15', 'improve-tech-15', 'improve-total-15',
                                   ]]
df_phase15

> Variance differs a lot between the score variables, so we standardize them to values between 0 and 1 before performing PCA.

In [ ]:
print(df_phase15.var()['improve-novel-15'])
print(df_phase15.var()['improve-vis-15'])
print(df_phase15.var()['improve-ur-15'])
print(df_phase15.var()['improve-tech-15'])
print(df_phase15.var()['improve-total-15'])

In [ ]:
df_new = (df_phase15-df_phase15.mean())/df_phase15.std()
df_new.describe()

In [ ]:
# Here, we can see only for 1 eigenvalues are greater than one. 
# It means we need to choose only 1 factors (or unobserved variables).

from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(df_new)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

In [ ]:
# create a factor analyzer variable and perform factor analysis 

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(dropped_student_group)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
# Do a scree plot 

xvals = range(1, dropped_student_group.shape[1] + 1)

In [ ]:
plt.scatter(xvals, ev)
plt.plot(xvals, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(df_new)

In [ ]:
T = pca.transform(df_new)

In [ ]:
df_new.shape

In [ ]:
T.shape

In [ ]:
df_new.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

# So just 1 principle component can explain almost 67% of the variance from these 5 features.

In [ ]:
components = pd.DataFrame(pca.components_, columns = df_new.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])
    

    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, df_new.columns.values)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

def draw_vectors(transformed_features, components_, columns):
    """
    This funtion will project your *original* features
    onto your principal component feature-space, so that you can
    visualize how "important" each one was in the
    multi-dimensional scaling
    """

    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])
    yvector = components_[1] * max(transformed_features[:,1])

    ax = plt.axes()

    for i in range(num_columns):
    # Use an arrow to project each original feature as a
    # labeled vector on your principal component axes
        plt.arrow(0, 0, xvector[i], yvector[i], color='b', width=0.0005, head_width=0.02, alpha=0.75)
        plt.text(xvector[i]*1.2, yvector[i]*1.2, list(columns)[i], color='b', alpha=0.75)

    return ax

>> We can see from the plot that all components are positive in the first principle component. 

>> improve-ur-15, improve-novel-15, improve-total-15, improve-vis-15 are negative in the second principle component. Their lengths portray their magnitudes.

>> The participants in green have high values for the first principle component – They have high improve-ur-15, improve-novel-15, improve-total-15, improve-vis-15 and change-files-15

>> The participants in red have high values for the second principle component – They have high delete-loc-15 and add-loc-15

In [ ]:
# Get variance of each factors

# 1. Sum of squared loadings (variance)
# 2. Proportional variance
# 3. Cumulative variance

## 
fa.get_factor_variance()

## Factor Analysis - Group 0

In [ ]:
dropped_student = overall_loc_scores_final.drop(['Student'], axis=1)

bogota_0 = dropped_student[dropped_student['Group'].isin([0])]

df_phase15_bogota0 = bogota_0[['improve-novel-15', 'improve-vis-15', 'improve-ur-15', 'improve-tech-15', 'improve-total-15']]
df_phase15_bogota0.head(5)

In [ ]:
print(df_phase15_bogota0.var()['improve-novel-15'])
print(df_phase15_bogota0.var()['improve-vis-15'])
print(df_phase15_bogota0.var()['improve-ur-15'])
print(df_phase15_bogota0.var()['improve-tech-15'])
print(df_phase15_bogota0.var()['improve-total-15'])

In [ ]:
df_new_bogota0 = (df_phase15_bogota0-df_phase15_bogota0.mean())/df_phase15_bogota0.std()
df_new_bogota0.describe()

In [ ]:
# Here, we can see only for 18-factors eigenvalues are greater than one. 
# It means we need to choose only 18 factors (or unobserved variables).

from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(df_new_bogota0)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

In [ ]:
# create a factor analyzer variable and perform factor analysis 

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(df_new_bogota0)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
# Do a scree plot 

xvals_bogota0 = range(1, df_new_bogota0.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota0, ev)
plt.plot(xvals_bogota0, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(df_new_bogota0)

In [ ]:
T = pca.transform(df_new_bogota0)

In [ ]:
df_new_bogota0.shape

In [ ]:
T.shape

In [ ]:
df_new_bogota0.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

# So just 1 principle components can explain almost 75% of the variance from these 9 features.

In [ ]:
components = pd.DataFrame(pca.components_, columns = df_new_bogota0.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])
   

    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, df_new_bogota0.columns.values)

## Factor Analysis - Group 1

In [ ]:
dropped_student = overall_loc_scores_final.drop(['Student'], axis=1)

bogota_1 = dropped_student[dropped_student['Group'].isin([1])]

df_phase15_bogota1 = bogota_1[['improve-novel-15', 'improve-vis-15', 'improve-ur-15', 'improve-tech-15', 'improve-total-15',]]
df_phase15_bogota1.head(5)

In [ ]:
print(df_phase15_bogota1.var()['improve-novel-15'])
print(df_phase15_bogota1.var()['improve-vis-15'])
print(df_phase15_bogota1.var()['improve-ur-15'])
print(df_phase15_bogota1.var()['improve-tech-15'])
print(df_phase15_bogota1.var()['improve-total-15'])

In [ ]:
df_new_bogota1 = (df_phase15_bogota1-df_phase15_bogota1.mean())/df_phase15_bogota1.std()
df_new_bogota1.describe()

In [ ]:
# Here, we can see only for 18-factors eigenvalues are greater than one. 
# It means we need to choose only 18 factors (or unobserved variables).

from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(df_new_bogota1)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(df_new_bogota1)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
# Do a scree plot 

xvals_bogota1 = range(1, df_new_bogota1.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota1, ev)
plt.plot(xvals_bogota1, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(df_new_bogota0)

In [ ]:
T = pca.transform(df_new_bogota0)

In [ ]:
df_new_bogota1.shape

In [ ]:
T.shape

In [ ]:
df_new_bogota1.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = df_new_bogota1.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])


    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, df_new_bogota1.columns.values)

## Factor Analysis - Group 2

In [ ]:
dropped_student = overall_loc_scores_final.drop(['Student'], axis=1)

bogota_2 = dropped_student[dropped_student['Group'].isin([2])]

df_phase15_bogota2 = bogota_2[['improve-novel-15', 'improve-vis-15', 'improve-ur-15', 'improve-tech-15', 'improve-total-15']]
df_phase15_bogota2.head(5)

In [ ]:
print(df_phase15_bogota2.var()['improve-novel-15'])
print(df_phase15_bogota2.var()['improve-vis-15'])
print(df_phase15_bogota2.var()['improve-ur-15'])
print(df_phase15_bogota2.var()['improve-tech-15'])
print(df_phase15_bogota2.var()['improve-total-15'])

In [ ]:
df_new_bogota2 = (df_phase15_bogota2-df_phase15_bogota2.mean())/df_phase15_bogota2.std()
df_new_bogota2.describe()

In [ ]:
# Here, we can see only for 18-factors eigenvalues are greater than one. 
# It means we need to choose only 18 factors (or unobserved variables).

from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(df_new_bogota2)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

# create a factor analyzer variable and perform factor analysis 

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(df_new_bogota2)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
# Do a scree plot 

xvals_bogota2 = range(1, df_new_bogota2.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota2, ev)
plt.plot(xvals_bogota2, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(df_new_bogota2)

In [ ]:
T = pca.transform(df_new_bogota2)

In [ ]:
df_new_bogota2.shape

In [ ]:
T.shape

In [ ]:
df_new_bogota2.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

# So just 3 principle components can explain almost 73% of the variance from these 9 features.

In [ ]:
components = pd.DataFrame(pca.components_, columns = df_new_bogota2.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])


    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, df_new_bogota0.columns.values)

## Factor Analysis - Group 3

In [ ]:
dropped_student = overall_loc_scores_final.drop(['Student'], axis=1)

bogota_3 = dropped_student[dropped_student['Group'].isin([3])]

df_phase15_bogota3 = bogota_3[['improve-novel-15', 'improve-vis-15', 'improve-ur-15', 'improve-tech-15', 'improve-total-15']]
df_phase15_bogota3.head(5)

In [ ]:
print(df_phase15_bogota3.var()['improve-novel-15'])
print(df_phase15_bogota3.var()['improve-vis-15'])
print(df_phase15_bogota3.var()['improve-ur-15'])
print(df_phase15_bogota3.var()['improve-tech-15'])
print(df_phase15_bogota3.var()['improve-total-15'])

In [ ]:
df_new_bogota3 = (df_phase15_bogota3-df_phase15_bogota3.mean())/df_phase15_bogota3.std()
df_new_bogota3.describe()

In [ ]:
# Here, we can see only for 18-factors eigenvalues are greater than one. 
# It means we need to choose only 18 factors (or unobserved variables).

from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(df_new_bogota3)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

fa = FactorAnalyzer(n_factors=2, rotation="varimax")
fa.fit(df_new_bogota3)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
# Do a scree plot 

xvals_bogota3 = range(1, df_new_bogota3.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota3, ev)
plt.plot(xvals_bogota3, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2, svd_solver='full')
pca.fit(df_new_bogota3)

In [ ]:
T = pca.transform(df_new_bogota3)

In [ ]:
df_new_bogota3.shape

In [ ]:
T.shape

In [ ]:
df_new_bogota3.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = df_new_bogota3.columns, index=[0, 1])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])
    yvector = components_[1] * max(transformed_features[:,1])

    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2 + yvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, df_new_bogota3.columns.values)

In [ ]:
ax = draw_vectors(T, pca.components_, df_new_bogota3.columns.values)
T_df = pd.DataFrame(T)
T_df.columns = ['component1', 'component2']

T_df['color'] = 'y'
T_df.loc[T_df['component1'] > 2 , 'color'] = 'g'
T_df.loc[T_df['component2'] > 2, 'color'] = 'r'

plt.xlabel('Principle Component 1')
plt.ylabel('Principle Component 2')
plt.scatter(T_df['component1'], T_df['component2'], color=T_df['color'], alpha=0.5)
plt.show()

## ANOVA with Pingouin Package [ Section to be Ignored ]

In [ ]:
import pandas as pd
import pingouin as pg


aov = pg.anova(dv='improve-novel-15', between=['Group', 'add-loc-15'], data=overall_loc_scores_final,
             detailed=True)

print(aov)

In [ ]:
import pandas as pd
import pingouin as pg


aov = pg.anova(dv='improve-tech-15', between=['Group', 'improve-effort-15'], data=overall_loc_scores_final,
             detailed=True)

print(aov)

In [ ]:
import pandas as pd
import pingouin as pg


aov = pg.anova(dv='improve-novel-15', between=['Group', 'improve-effort-15'], data=overall_loc_scores_final,
             detailed=True)

print(aov)

In [ ]:
import pandas as pd
import pingouin as pg


aov = pg.anova(dv='improve-vis-15', between=['Group', 'improve-effort-15'], data=overall_loc_scores_final,
             detailed=True)

print(aov)

In [ ]:
from pingouin import ancova, read_dataset
ancova(data=overall_loc_scores_final, dv='improve-novel-15', covar=['add-loc-15', 'improve-effort-15', 'delete-loc-15'], between='Group')

In [ ]:
import pandas as pd
import pingouin as pg


aov = pg.anova(dv='improve-ur-15', between=['Group', 'improve-effort-15'], data=overall_loc_scores_final,
             detailed=True)

print(aov)

## EDA Survey Questions [ Programming Skills ] 


### Q7 - 1

- Strongly Disagree - 0
- Disagree - 1
- Somewhat Disagree - 2
- Neither Agree nor Disagree - 3
- Somewhat Agree - 4
- Agree - 5
- Strongly Agree - 6

>> I am extremely skilled at programming in Javascript

>> Interpretation - Majority of the participants in all groups don't think that they are extremely skilled at Javascript.

In [ ]:
survey0['Q7_Q7_1'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey1['Q7_Q7_1'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey2['Q7_Q7_1'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey3['Q7_Q7_1'].value_counts().plot(kind='bar', figsize=(15, 7))

### Q7-2

>> I consider myself knowledgeable about good coding techniques on mashup design (combining data in an interactive web application)

>> Interpretation - Majority of the participants are undecided whether they know what a mashup is except for the full transparency group where majority of the participants have no idea what a mashup is.

In [ ]:
survey0['Q7_Q7_2'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey1['Q7_Q7_2'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey2['Q7_Q7_2'].value_counts().plot(kind='bar', figsize=(15, 7))

In [36]:
survey3['Q7_Q7_2'].value_counts().plot(kind='bar', figsize=(15, 7))

NameError: name 'survey3' is not defined

### Q7-3

>> I know somewhat more than most programmers about programming in Javascript

>> Interpretation - Majority of the participants in all groups. don't think that they know a lot about Javascript.

In [ ]:
survey0['Q7_Q7_3'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey1['Q7_Q7_3'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey2['Q7_Q7_3'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey3['Q7_Q7_3'].value_counts().plot(kind='bar', figsize=(15, 7))

### Q7 - 4

>> I know how to find what I am looking for when designing a mashup

>> Interpretation - Majority of the participants are undecided about designing mashup.

In [ ]:
survey0['Q7_Q7_4'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey1['Q7_Q7_4'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey2['Q7_Q7_3'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey3['Q7_Q7_4'].value_counts().plot(kind='bar', figsize=(15, 7))

### Q8 - 1

- Very Bad - 0
- Bad - 1
- Poor - 2
- Neither Good nor Bad - 3
- Fair - 4
- Good - 5
- Very Good - 6

>> How would you rate your skill at programming, compared to other things you do on the computer?

In [ ]:
survey0['Q8_Q8_1'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey1['Q8_Q8_1'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey2['Q8_Q8_1'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey3['Q8_Q8_1'].value_counts().plot(kind='bar', figsize=(15, 7))

### Q8 - 2

>> How would you rate your skill at programming, compared to the sport or game you are best at?

In [ ]:
survey0['Q8_Q8_2'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey1['Q8_Q8_2'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey2['Q8_Q8_2'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey3['Q8_Q8_2'].value_counts().plot(kind='bar', figsize=(15, 7))

### Q10 

- Bottom of the contest - 0
- Below Average - 1
- Average - 2
- Top 10 - 3
- Top 3 - 4

>> Based on your past experience,  what place do you think you will receive in this IronHacks?

>> Inference - Majority of the participants in all groups think that they are going to perform average.

In [ ]:
survey0['Q10'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey1['Q10'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey2['Q10'].value_counts().plot(kind='bar', figsize=(15, 7))

In [ ]:
survey3['Q10'].value_counts().plot(kind='bar', figsize=(15, 7))

## Cronbach's Alpha

## PCA Survey Question 2

> High Cronbach's alpha between survey items for Question 2. High Internal Consistency.

In [ ]:
Q2 = survey[['Q2_Q2_1', 'Q2_Q2_2', 'Q2_Q2_3', 'Q2_Q2_4', 'Q2_Q2_5', 'Q2_Q2_6', 'Q2_Q2_7', 'Q2_Q2_8',
                    'Q2_Q2_9', 'Q2_Q2_10', 'Q2_Q2_11', 'Q2_Q2_12', 'Q2_Q2_13']]


# 95% confidence interval for Cronbach's alpha

import pingouin as pg

pg.cronbach_alpha(data=Q2)

In [ ]:
Q2.to_csv("Q2-final.csv")

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(Q2)
p_value

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(Q2)
kmo_model

In [ ]:
Q2.head(5)

In [ ]:
from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(Q2)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

fa = FactorAnalyzer(n_factors=2, rotation="varimax")
fa.fit(Q2)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
xvals_bogota3 = range(1, Q2.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota3, ev)
plt.plot(xvals_bogota3, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2, svd_solver='full')
pca.fit(Q2)

In [ ]:
T = pca.transform(Q2)

In [ ]:
Q2.shape

In [ ]:
T.shape

In [ ]:
Q2.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = Q2.columns, index=[0, 1])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])
    yvector = components_[1] * max(transformed_features[:,1])

    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2 + yvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, Q2.columns.values)

> ## Interpretation: 

- Q2_Q2_5 is 'Because I want to get in touch with the experts in IronHacks'. 
- Q2_Q2_13 is 'To pass the class'

In [ ]:
ax = draw_vectors(T, pca.components_, Q2.columns.values)
T_df = pd.DataFrame(T)
T_df.columns = ['component1', 'component2']

T_df['color'] = 'y'
T_df.loc[T_df['component1'] > 2 , 'color'] = 'g'
T_df.loc[T_df['component2'] > 2, 'color'] = 'r'

plt.xlabel('Principle Component 1')
plt.ylabel('Principle Component 2')
plt.scatter(T_df['component1'], T_df['component2'], color=T_df['color'], alpha=0.5)
plt.show()

## PCA for Survey Question 3

> High Internal Consistency between Survey Items in Question 3

In [ ]:
Q3 = survey[['Q3_Q3_1', 'Q3_Q3_2', 'Q3_Q3_3', 'Q3_Q3_4', 'Q3_Q3_5']]


# 95% confidence interval for Cronbach's alpha

import pingouin as pg

pg.cronbach_alpha(data=Q3)

In [ ]:
Q3.to_csv('Q3-final.csv')

In [ ]:
from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(Q3)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

# only 1 eigenvalues greater than 1, so we use 1 factor - No rotation will be performed when the number of factors equals 1.

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(Q3)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
xvals_bogota3 = range(1, Q3.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota3, ev)
plt.plot(xvals_bogota3, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(Q3)

In [ ]:
T = pca.transform(Q3)

In [ ]:
Q3.shape

In [ ]:
T.shape

In [ ]:
Q3.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = Q3.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])

    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, Q3.columns.values)

> ## Interpretation: 

- Q3_Q3_1 - I am able to communicate ideas in many different ways

## PCA for Survey Question 4

In [ ]:
Q4 = survey[['Q4_Q4_1', 'Q4_Q4_2', 'Q4_Q4_3', 'Q4_Q4_4', 'Q4_Q4_5']]


# 95% confidence interval for Cronbach's alpha

import pingouin as pg

pg.cronbach_alpha(data=Q4)

In [ ]:
Q4.to_csv('Q4-final.csv')

In [ ]:
from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(Q4)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

# only 1 eigenvalues greater than 1, so we use 1 factor - No rotation will be performed when the number of factors equals 1.

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

# create a factor analyzer variable and perform factor analysis 

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(Q4)

# Get the loadings
loadings = fa.loadings_

# Get the Eigenvector and Eigenvalues
ev, v = fa.get_eigenvalues()

# Do a scree plot 

xvals = range(1, Q4.shape[1] + 1)

plt.scatter(xvals, ev)
plt.plot(xvals, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(Q4)

In [ ]:
T = pca.transform(Q4)

In [ ]:
Q4.shape

In [ ]:
T.shape

In [ ]:
Q4.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = Q4.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])


    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, Q4.columns.values)

> ## Interpretation: 

- Q4_Q4_1 - I create diagrams that map concepts, facts, and relationships between components

## PCA for Survey Question 5

> High Internal Consistency between Survey Items in Q5

In [ ]:
Q5 = survey[['Q5_Q5_1', 'Q5_Q5_2', 'Q5_Q5_3', 'Q5_Q5_4', 'Q5_Q5_5']]


# 95% confidence interval for Cronbach's alpha

import pingouin as pg

pg.cronbach_alpha(data=Q5)

In [ ]:
Q5.to_csv('Q5-final.csv')

In [ ]:
from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(Q5)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

# 2 eigenvalues greater than 1, so we use 2 factors

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

# create a factor analyzer variable and perform factor analysis 

fa = FactorAnalyzer(n_factors=2, rotation="varimax")
fa.fit(Q5)

# Get the loadings
loadings = fa.loadings_

# Get the Eigenvector and Eigenvalues
ev, v = fa.get_eigenvalues()

# Do a scree plot 

xvals = range(1, Q5.shape[1] + 1)

plt.scatter(xvals, ev)
plt.plot(xvals, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [37]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

NameError: name 'loadings' is not defined

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2, svd_solver='full')
pca.fit(Q5)

In [ ]:
T = pca.transform(Q5)

In [ ]:
Q5.shape

In [ ]:
T.shape

In [ ]:
Q5.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = Q5.columns, index=[0, 1])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])
    yvector = components_[1] * max(transformed_features[:,1])

    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2 + yvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, Q5.columns.values)

> ## Interpretation: 

- Q5_Q5_Q4 - I have the necessary skills to complete a web programming task in Javascript
- Q5_Q5_Q2 - I have a clear vision of what needs to be achieved when developing a mashup (combining data in an interactive web application) in Javascript

In [ ]:
ax = draw_vectors(T, pca.components_, Q5.columns.values)
T_df = pd.DataFrame(T)
T_df.columns = ['component1', 'component2']

T_df['color'] = 'y'
T_df.loc[T_df['component1'] > 0 , 'color'] = 'g'
T_df.loc[T_df['component2'] > 0, 'color'] = 'r'

plt.xlabel('Principle Component 1')
plt.ylabel('Principle Component 2')
plt.scatter(T_df['component1'], T_df['component2'], color=T_df['color'], alpha=0.5)
plt.show()

## PCA for Survey Question 7

> High Internal Consistency between Survey Items in Q7

In [ ]:
Q7 = survey[['Q7_Q7_1', 'Q7_Q7_2', 'Q7_Q7_3', 'Q7_Q7_4']]


# 95% confidence interval for Cronbach's alpha

import pingouin as pg

pg.cronbach_alpha(data=Q7)

In [ ]:
Q7.to_csv('Q7-final.csv')

In [ ]:
from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer(rotation=None)
fa.fit(Q7)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

# only 1 eigenvalues greater than 1, so we use 1 factor - No rotation will be performed when the number of factors equals 1.

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(Q7)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

In [ ]:
 # Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
xvals_bogota3 = range(1, Q7.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota3, ev)
plt.plot(xvals_bogota3, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(Q7)

In [ ]:
T = pca.transform(Q7)

In [ ]:
Q7.shape

In [ ]:
T.shape

In [ ]:
Q7.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = Q7.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])


    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, Q7.columns.values)

> ## Interpretation: 
    
- Q7_Q7_3 - I know somewhat more than most programmers about programming in Javascript

- Factor Analysis with Varimax Rotation, Factor Analysis with no rotation and PCA give same results.

## PCA for Survey Question 8

> High Internal Consistency between Survey Items in Q8

In [ ]:
Q8 = survey[['Q8_Q8_1', 'Q8_Q8_2']]

# 95% confidence interval for Cronbach's alpha

import pingouin as pg

pg.cronbach_alpha(data=Q8)

In [ ]:
Q8.to_csv('Q8-final.csv')

In [ ]:
from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer()
fa.fit(Q8)
eigen_values, vectors = fa.get_eigenvalues()
eigen_values

# only 1 eigenvalues greater than 1, so we use 1 factor - No rotation will be performed when the number of factors equals 1.

In [ ]:
from factor_analyzer import FactorAnalyzer 
import matplotlib.pyplot as plt

fa = FactorAnalyzer(n_factors=1, rotation="varimax")
fa.fit(Q8)

In [ ]:
# Get the loadings

loadings = fa.loadings_

In [ ]:
# Get the Eigenvector and Eigenvalues

ev, v = fa.get_eigenvalues()

In [ ]:
xvals_bogota3 = range(1, Q8.shape[1] + 1)

In [ ]:
plt.scatter(xvals_bogota3, ev)
plt.plot(xvals_bogota3, ev)
plt.title('Scree Plot')
plt.xlabel('Factor')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
df_pca = pd.DataFrame.from_records(loadings)
df_pca

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1, svd_solver='full')
pca.fit(Q8)

In [ ]:
T = pca.transform(Q8)

In [ ]:
Q8.shape

In [38]:
T.shape

NameError: name 'T' is not defined

In [ ]:
Q8.head()

In [ ]:
T

In [ ]:
pca.explained_variance_ratio_

In [ ]:
components = pd.DataFrame(pca.components_, columns = Q8.columns, index=[0])
components

In [ ]:
import math

def get_important_features(transformed_features, components_, columns):
    """
    This function will return the most "important" 
    features so we can determine which have the most
    effect on multi-dimensional scaling
    """
    num_columns = len(columns)

    # Scale the principal components by the max value in
    # the transformed set belonging to that component
    xvector = components_[0] * max(transformed_features[:,0])


    # Sort each column by it's length. These are your *original*
    # columns, not the principal components.
    important_features = { columns[i] : math.sqrt(xvector[i]**2) for i in range(num_columns) }
    important_features = sorted(zip(important_features.values(), important_features.keys()), reverse=True)
    print("Features by importance:\n", important_features)

get_important_features(T, pca.components_, Q8.columns.values)

> ## Interpretation: 
    
- How would you rate your skill at programming, compared to the sport or game you are best at?

## Adequacy Test
> Before you perform factor analysis, you need to evaluate the “factorability” of our dataset. Factorability means "can we found the factors in the dataset?". There are two methods to check the factorability or sampling adequacy:

- Bartlett’s Test
- Kaiser-Meyer-Olkin Test

> Bartlett’s test of sphericity checks whether or not the observed variables intercorrelate at all using the observed correlation matrix against the identity matrix. If the test found statistically insignificant, you should not employ a factor analysis

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(Q2)
p_value

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(Q3)
p_value

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(Q4)
p_value

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(Q5)
p_value

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(Q7)
p_value

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(Q8)
p_value

## KMO Test 

>  Kaiser-Meyer-Olkin (KMO) Test measures the suitability of data for factor analysis. 
It determines the adequacy for each observed variable and for the complete model. 
KMO estimates the proportion of variance among all the observed variable. 
Lower proportion id more suitable for factor analysis. KMO values range between 0 and 1. 
Value of KMO less than 0.6 is considered inadequate.

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(Q2)
kmo_model

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(Q3)
kmo_model

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(Q4)
kmo_model

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(Q5)
kmo_model

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(Q7)
kmo_model

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(Q8)
kmo_model

## Factor Analysis of Q2 

> The first step of any factor analysis is to look at a correlation plot of all the variables to see if any variables are useless or too correlated with others.

In [ ]:
import seaborn as sns
plt.figure(figsize=(20,10))
c= Q2.corr()
sns.heatmap(c)

In [ ]:
fa = FactorAnalyzer()
fa.fit(Q2)
#Get Eigen values and plot them
ev, v = fa.get_eigenvalues()
ev

In [ ]:
plt.plot(range(1,Q2.shape[1]+1),ev)

## Interpretation -

> We will only use 2 factors here, given the big dropoff in eigenvalue after the 2nd factor. The factors have eigenvalues of 8.15 , meaning that they describe the variance of about 8.15 variables.

> The FactorAnalyzer function is where we specify the number of factors we want as well as the type of rotation. Simply put, the idea of rotation is to rotate the factors in order to achieve a simpler and more interpretable structure. Many types of rotations exist. Below, I will use varimax rotation, which maximizes the sum of the variance of squared loadings while ensuring that the factors created are not correlated (orthogonality). Let’s see what factors are created.

In [ ]:
fa = FactorAnalyzer(2, rotation='varimax')
fa.fit(Q2)
loads = fa.loadings_
print(loads)

> The higher a factor loading, the more important a variable is for said factor. A loading cutoff of 0.5 will be used here. This cutoff determines which variables belong to which factor. For instance, we see that the first factor contains variables 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 (loadings of 0.71, 0.65, 0.9, 0.76, 0.5, 0.63, 0.7, 0.64, 0.62, 0.64 respectively).

> For the second factor, it contains variables 7, 8, 10 ( loadings of 0.72,0.58, 0.52  respectively ). 


> Here are the 2 factors created, the variables they contain and their possible “interpretability”:

- Motivation: "To become known for being an excellent programmer", "The internship possibility", "Because I have ideas I want to introduce to the experts in IronHacks", "Because I want to get in touch with the experts in IronHacks", "To become known as a creative person", "To improve my skills", "To test my capabilities", "I enjoy dealing with new problems", "To keep up with new ideas and innovations", "I am dissatisfied with existing applications and I think I can do better", "Just because I am curious"

- Intrinsic Motivation: "To improve my skills", "To test my capabilities", "To keep up with new ideas and innovations"

Now, that's great, but how do we know if our factors are any good? Well, the Cronbach alpha can be used to measure whether or not the variables of a factor form a “coherent” and reliable factor. A value above 0.6 for the alpha is in practice deemed acceptable. Here is the code to get the Cronbach alpha using the pingouin package.

In [ ]:

# Create the factors

factor1 = Q2[['Q2_Q2_2', 'Q2_Q2_3', 'Q2_Q2_4', 'Q2_Q2_5', 'Q2_Q2_6', 'Q2_Q2_7', 'Q2_Q2_8', 'Q2_Q2_9', 'Q2_Q2_10', 
             'Q2_Q2_11', 'Q2_Q2_12']]
factor2 = Q2[['Q2_Q2_7', 'Q2_Q2_8', 'Q2_Q2_10']]

# Get cronbach alpha
# factor1_alpha = pg.cronbach_alpha(factor1)
factor1_alpha = pg.cronbach_alpha(data=factor1)
factor2_alpha = pg.cronbach_alpha(data=factor2)
print(factor1_alpha, factor2_alpha)

> The alphas are evaluated at 0.93 and 0.89, which indicates that they are useful and coherent. We could use these new factors as variable for other analysis or for prediction. Here is the code to apply the factors to the entire dataframe and create the 2 new variables, that could be used as replacement for the 13 variables.

In [ ]:
new_variables = fa.fit_transform(Q2)
new_variables

## Factor Analysis of Q3

In [ ]:
import seaborn as sns
plt.figure(figsize=(20,10))
c= Q3.corr()
sns.heatmap(c)

In [ ]:
#Subset of the data, the 14 columns containing the survey answers
fa = FactorAnalyzer()
fa.fit(Q3)
#Get Eigen values and plot them
ev, v = fa.get_eigenvalues()
ev
plt.plot(range(1,Q3.shape[1]+1),ev)

In [ ]:
fa = FactorAnalyzer(2, rotation='varimax')
fa.fit(Q3)
loads = fa.loadings_
print(loads)

> Here are the 2 factors created, the variables they contain and their possible “interpretability”:
    
- Flexibility with others: “I am able to communicate ideas in many different ways.”， “I am willing to consider solutions offered by others.”， “I am willing to be flexible in any given situation.”

- Flexibility with oneself: “I am willing to consider alternative solutions to problems.“， ”I am willing to try different ways of solving problems.“

In [ ]:
#Create the factors
factor1 = Q3[['Q3_Q3_1', 'Q3_Q3_3', 'Q3_Q3_5']]
factor2 = Q3[['Q3_Q3_2', 'Q3_Q3_4']]

#Get cronbach alpha
factor1_alpha = pg.cronbach_alpha(factor1)
factor2_alpha = pg.cronbach_alpha(factor2)

print(factor1_alpha, factor2_alpha)

## Factor Analysis of Q4

In [ ]:
import seaborn as sns
plt.figure(figsize=(20,10))
c= Q4.corr()
sns.heatmap(c)

In [ ]:
#Subset of the data, the 14 columns containing the survey answers
fa = FactorAnalyzer()
fa.fit(Q4)
#Get Eigen values and plot them
ev, v = fa.get_eigenvalues()
ev
plt.plot(range(1,Q4.shape[1]+1),ev)

In [39]:
fa = FactorAnalyzer(2, rotation='varimax')
fa.fit(Q4)
loads = fa.loadings_
print(loads)

NameError: name 'FactorAnalyzer' is not defined

> Here are the 2 factors created, the variables they contain and their possible “interpretability”:
    
- Normal Diagrams: "I create diagrams that map concepts, facts, and relationships between components", "I arrange information into charts and tables", "I draw diagrams that show relationships between concepts", "I create diagrams to understand complexity"

- Programming Diagrams: "I map out components and their attributes"

In [ ]:
#Create the factors
factor1 = Q3[['Q3_Q3_1', 'Q3_Q3_2', 'Q3_Q3_3', 'Q3_Q3_5']]


#Get cronbach alpha
factor1_alpha = pg.cronbach_alpha(factor1)


print(factor1_alpha)

## Factor Analysis of Q5

In [ ]:
import seaborn as sns
plt.figure(figsize=(20,10))
c= Q5.corr()
sns.heatmap(c)

In [ ]:
#Subset of the data, the 14 columns containing the survey answers
fa = FactorAnalyzer()
fa.fit(Q5)
#Get Eigen values and plot them
ev, v = fa.get_eigenvalues()
ev
plt.plot(range(1,Q5.shape[1]+1),ev)

In [ ]:
fa = FactorAnalyzer(2, rotation='varimax')
fa.fit(Q5)
loads = fa.loadings_
print(loads)

> Here are the 2 factors created, the variables they contain and their possible “interpretability”:
    
- Javascript Skills: "I have sufficient access to information about best practices in JavaScript coding", "I have a clear vision of what needs to be achieved when developing a mashup (combining data in an interactive web application) in Javascript", "I have the necessary skills to complete a web programming task in Javascript"

- Misc Skills ( Communication skills and learn new knowledge ) : "I am able to communicate programming issues with others well", "I have the technical competence to absorb new programming knowledge"

In [ ]:
#Create the factors
factor1 = Q5[['Q5_Q5_1', 'Q5_Q5_2', 'Q5_Q5_4']]
factor2 = Q5[['Q5_Q5_3', 'Q5_Q5_5']]


#Get cronbach alpha
factor1_alpha = pg.cronbach_alpha(factor1)
factor2_alpha = pg.cronbach_alpha(factor2)

print(factor1_alpha, factor2_alpha)

## Factor Analysis of Q7

In [ ]:
import seaborn as sns
plt.figure(figsize=(20,10))
c= Q7.corr()
sns.heatmap(c)

In [ ]:
#Subset of the data, the 14 columns containing the survey answers
fa = FactorAnalyzer()
fa.fit(Q7)
#Get Eigen values and plot them
ev, v = fa.get_eigenvalues()
ev
plt.plot(range(1,Q7.shape[1]+1),ev)

In [ ]:
fa = FactorAnalyzer(2, rotation='varimax')
fa.fit(Q7)
loads = fa.loadings_
print(loads)

> Here are the 2 factors created, the variables they contain and their possible “interpretability”:
    
- Javascript Skills: "I am extremely skilled at programming in Javascript", "I know somewhat more than most programmers about programming in Javascript"

- Mashup Design Skills : "I consider myself knowledgeable about good coding techniques on mashup design (combining data in an interactive web application)", "I know how to find what I am looking for when designing a mashup"

In [ ]:
#Create the factors
factor1 = Q7[['Q7_Q7_1', 'Q7_Q7_3']]
factor2 = Q7[['Q7_Q7_2', 'Q7_Q7_4']]


#Get cronbach alpha
factor1_alpha = pg.cronbach_alpha(factor1)
factor2_alpha = pg.cronbach_alpha(factor2)

print(factor1_alpha, factor2_alpha)

## Factor Analysis of Q8

In [ ]:
import seaborn as sns
plt.figure(figsize=(20,10))
c= Q8.corr()
sns.heatmap(c)

In [ ]:
#Subset of the data, the 14 columns containing the survey answers
fa = FactorAnalyzer()
fa.fit(Q8)
#Get Eigen values and plot them
ev, v = fa.get_eigenvalues()
ev
plt.plot(range(1,Q8.shape[1]+1),ev)

In [ ]:
fa = FactorAnalyzer(2, rotation='varimax')
fa.fit(Q8)
loads = fa.loadings_
print(loads)

## PCA on Q2 to Check for Clusters

## Step 1: Reduce Dimensionality
In this step, we will find the optimal number of components which capture the greatest amount of variance in the data. In my case, as seen in Fig. 1 below, that number is one.

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format='retina'

# Standardize the data to have a mean of ~0 and a variance of 1
X_std = StandardScaler().fit_transform(Q2)
# Create a PCA instance: pca
pca = PCA(n_components=13)
principalComponents = pca.fit_transform(X_std)
# Plot the explained variances
features = range(pca.n_components_)
plt.bar(features, pca.explained_variance_ratio_, color='black')
plt.xlabel('PCA features')
plt.ylabel('variance %')
plt.xticks(features)
# Save components to a DataFrame
PCA_components = pd.DataFrame(principalComponents)

> Fig. 1 shows that the first three components explain the majority of the variance in our data. For this visualization use case, we will quickly plot just the first two. We do this to notice if there are any clear clusters.

In [ ]:
plt.scatter(PCA_components[0], PCA_components[1], alpha=.1, color='black')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')

> Fig. 2 shows no distinguishable clusters. This factoid tells us that the observations in the dataset cannot be grouped. Because each observation in the data is for one person, we could say that the clusters represent same group of people.

> In this step, we will use k-means clustering to view the top 2 PCA components. To do this, we will first fit these principal components to the k-means algorithm and determine the best number of clusters. Determining the ideal number of clusters for our k-means model can be done by measuring the sum of the squared distances to the nearest cluster center aka inertia. Much like the scree plot in fig. 1 for PCA, the k-means scree plot below indicates the percentage of variance explained, but in slightly different terms, as a function of the number of clusters.

In [ ]:
ks = range(1, 10)
inertias = []
for k in ks:
    # Create a KMeans instance with k clusters: model
    model = KMeans(n_clusters=k)
    
    # Fit model to samples
    model.fit(PCA_components.iloc[:,:2])
    
    # Append the inertia to the list of inertias
    inertias.append(model.inertia_)
    
plt.plot(ks, inertias, '-o', color='black')
plt.xlabel('number of clusters, k')
plt.ylabel('inertia')
plt.xticks(ks)
plt.show()

> Fig. 3 shows that after 1 clusters (at the elbow), the change in the value of inertia is no longer significant, and most likely, neither is the variance of the rest of the data after the elbow point. Therefore we can discard everything after k=1 and proceed to the last step in the process.

## PCA on Q3 to Check for Clusters

> In this step, we will find the optimal number of components which capture the greatest amount of variance in the data. In my case, as seen in Fig. 1 below, that number is one.

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format='retina'

# Standardize the data to have a mean of ~0 and a variance of 1
X_std = StandardScaler().fit_transform(Q3)
# Create a PCA instance: pca
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(X_std)
# Plot the explained variances
features = range(pca.n_components_)
plt.bar(features, pca.explained_variance_ratio_, color='black')
plt.xlabel('PCA features')
plt.ylabel('variance %')
plt.xticks(features)
# Save components to a DataFrame
PCA_components = pd.DataFrame(principalComponents)

In [ ]:
plt.scatter(PCA_components[0], PCA_components[1], alpha=.1, color='black')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')

In [ ]:
ks = range(1, 10)
inertias = []
for k in ks:
    # Create a KMeans instance with k clusters: model
    model = KMeans(n_clusters=k)
    
    # Fit model to samples
    model.fit(PCA_components.iloc[:,:2])
    
    # Append the inertia to the list of inertias
    inertias.append(model.inertia_)
    
plt.plot(ks, inertias, '-o', color='black')
plt.xlabel('number of clusters, k')
plt.ylabel('inertia')
plt.xticks(ks)
plt.show()

## PCA on Q4 to Check for Clusters

> In this step, we will find the optimal number of components which capture the greatest amount of variance in the data. In my case, as seen in Fig. 1 below, that number is one.

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format='retina'

# Standardize the data to have a mean of ~0 and a variance of 1
X_std = StandardScaler().fit_transform(Q4)
# Create a PCA instance: pca
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(X_std)
# Plot the explained variances
features = range(pca.n_components_)
plt.bar(features, pca.explained_variance_ratio_, color='black')
plt.xlabel('PCA features')
plt.ylabel('variance %')
plt.xticks(features)
# Save components to a DataFrame
PCA_components = pd.DataFrame(principalComponents)

In [ ]:
plt.scatter(PCA_components[0], PCA_components[1], alpha=.1, color='black')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')

In [ ]:
ks = range(1, 10)
inertias = []
for k in ks:
    # Create a KMeans instance with k clusters: model
    model = KMeans(n_clusters=k)
    
    # Fit model to samples
    model.fit(PCA_components.iloc[:,:2])
    
    # Append the inertia to the list of inertias
    inertias.append(model.inertia_)
    
plt.plot(ks, inertias, '-o', color='black')
plt.xlabel('number of clusters, k')
plt.ylabel('inertia')
plt.xticks(ks)
plt.show()

## PCA on Q5 to Check for Clusters

> In this step, we will find the optimal number of components which capture the greatest amount of variance in the data. In my case, as seen in Fig. 1 below, that number is one.

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format='retina'

# Standardize the data to have a mean of ~0 and a variance of 1
X_std = StandardScaler().fit_transform(Q5)
# Create a PCA instance: pca
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(X_std)
# Plot the explained variances
features = range(pca.n_components_)
plt.bar(features, pca.explained_variance_ratio_, color='black')
plt.xlabel('PCA features')
plt.ylabel('variance %')
plt.xticks(features)
# Save components to a DataFrame
PCA_components = pd.DataFrame(principalComponents)

In [ ]:
plt.scatter(PCA_components[0], PCA_components[1], alpha=.1, color='black')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')

In [ ]:
ks = range(1, 10)
inertias = []
for k in ks:
    # Create a KMeans instance with k clusters: model
    model = KMeans(n_clusters=k)
    
    # Fit model to samples
    model.fit(PCA_components.iloc[:,:2])
    
    # Append the inertia to the list of inertias
    inertias.append(model.inertia_)
    
plt.plot(ks, inertias, '-o', color='black')
plt.xlabel('number of clusters, k')
plt.ylabel('inertia')
plt.xticks(ks)
plt.show()

## PCA on Q7 to Check for Clusters

> In this step, we will find the optimal number of components which capture the greatest amount of variance in the data. In my case, as seen in Fig. 1 below, that number is one.

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format='retina'

# Standardize the data to have a mean of ~0 and a variance of 1
X_std = StandardScaler().fit_transform(Q7)
# Create a PCA instance: pca
pca = PCA(n_components=4)
principalComponents = pca.fit_transform(X_std)
# Plot the explained variances
features = range(pca.n_components_)
plt.bar(features, pca.explained_variance_ratio_, color='black')
plt.xlabel('PCA features')
plt.ylabel('variance %')
plt.xticks(features)
# Save components to a DataFrame
PCA_components = pd.DataFrame(principalComponents)

In [40]:
plt.scatter(PCA_components[0], PCA_components[1], alpha=.1, color='black')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')

NameError: name 'plt' is not defined

In [ ]:
ks = range(1, 10)
inertias = []
for k in ks:
    # Create a KMeans instance with k clusters: model
    model = KMeans(n_clusters=k)
    
    # Fit model to samples
    model.fit(PCA_components.iloc[:,:2])
    
    # Append the inertia to the list of inertias
    inertias.append(model.inertia_)
    
plt.plot(ks, inertias, '-o', color='black')
plt.xlabel('number of clusters, k')
plt.ylabel('inertia')
plt.xticks(ks)
plt.show()

## PCA on Q8 to Check for Clusters

> In this step, we will find the optimal number of components which capture the greatest amount of variance in the data. In my case, as seen in Fig. 1 below, that number is one.

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format='retina'

# Standardize the data to have a mean of ~0 and a variance of 1
X_std = StandardScaler().fit_transform(Q8)
# Create a PCA instance: pca
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(X_std)
# Plot the explained variances
features = range(pca.n_components_)
plt.bar(features, pca.explained_variance_ratio_, color='black')
plt.xlabel('PCA features')
plt.ylabel('variance %')
plt.xticks(features)
# Save components to a DataFrame
PCA_components = pd.DataFrame(principalComponents)

In [ ]:
plt.scatter(PCA_components[0], PCA_components[1], alpha=.1, color='black')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')

In this step, we will use k-means clustering to view the top three PCA components. To do this, we will first fit these principal components to the k-means algorithm and determine the best number of clusters. Determining the ideal number of clusters for our k-means model can be done by measuring the sum of the squared distances to the nearest cluster center aka inertia. Much like the scree plot in fig. 1 for PCA, the k-means scree plot below indicates the percentage of variance explained, but in slightly different terms, as a function of the number of clusters.

In [ ]:
ks = range(1, 10)
inertias = []
for k in ks:
    # Create a KMeans instance with k clusters: model
    model = KMeans(n_clusters=k)
    
    # Fit model to samples
    model.fit(PCA_components.iloc[:,:2])
    
    # Append the inertia to the list of inertias
    inertias.append(model.inertia_)
    
plt.plot(ks, inertias, '-o', color='black')
plt.xlabel('number of clusters, k')
plt.ylabel('inertia')
plt.xticks(ks)
plt.show()

In [ ]:
question_means = Q2.mean(axis = 0)
grand_mean = question_means.mean()
grand_mean

In [ ]:
std_by_questions = question_means.std()
std_by_questions

In [ ]:
pca = PCA(n_components = 2, random_state=1)
X_pca = pca.fit_transform(Q2)

In [ ]:
pca.explained_variance_ratio_.cumsum()[1]

> We managed to save around 63% of the variance, which is not very good but not bad either (people tend to prefer explained variance ≥ 90%). We don’t have to worry to much about this because we will not apply PCA for the final clustering result (and we will compare their result).
Another disadvantage of PCA is it transforms the features into abstract features. This mean we will lose data interpretability, hence making us unable to answer many critical questions.

In [ ]:
distortions = []
K_to_try = range(1, 10)

for i in K_to_try:
    model = KMeans(
            n_clusters=i,
            init='k-means++',
            n_jobs=-1,
            random_state=1)
    model.fit(X_pca)
    distortions.append(model.inertia_)
plt.plot(K_to_try, distortions, marker='o')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Distortion')
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# use the best K from elbow method
model = KMeans(
    n_clusters=2,
    init='k-means++',
    n_jobs=-1,
    random_state=1)

model = model.fit(X_pca)

y = model.predict(X_pca)

plt.scatter(X_pca[y == 0, 0], X_pca[y == 0, 1], s = 50, c = 'yellow', label = 'Cluster 1')
plt.scatter(X_pca[y == 1, 0], X_pca[y == 1, 1], s = 50, c = 'green', label = 'Cluster 2')
#plt.scatter(X_pca[y == 2, 0], X_pca[y == 2, 1], s = 50, c = 'red', label = 'Cluster 3')
plt.scatter(model.cluster_centers_[:, 0], model.cluster_centers_[:, 1], s = 100, c = 'blue', label = 'Centroids')
plt.title('Clusters of Students')
plt.xlabel('Principle Component 1')
plt.ylabel('Principle Component 2')
plt.legend()
plt.grid()
plt.show()

In [ ]:
import collections

print(collections.Counter(y))

In [ ]:
model = model.fit(Q2)

y_final = model.predict(Q2)

In [ ]:
print(collections.Counter(y_final))

> Only one observation has different cluster compared to the result with PCA (an observation moved from the 1st cluster to the 3rd). This mean reducing the data to 2 dimensions by PCA don’t decrease the clustering performance significantly.
Let’s compute the average answer of each cluster to see the difference between them :

In [ ]:
from scipy.cluster import hierarchy as hier

dendrogram = hier.dendrogram(hier.linkage(X_pca, method = 'ward'))
plt.title('Dendrogram')
plt.xlabel('questions')
plt.ylabel('Euclidean distances')
plt.show()

> Notice that there are two colours : green and red (exclude blue, which is the root). This mean the best k number of clusters according to Ward’s linkage (method = ‘ward’) is two.

In [ ]:
from sklearn.cluster import AgglomerativeClustering

model = AgglomerativeClustering(n_clusters = 2, 
                          affinity ='euclidean', 
                          linkage ='ward')
y = model.fit_predict(X_pca)

In [ ]:
print(collections.Counter(y))