In [1]:
import pandas as pd
import os

In [2]:
import csv

In [3]:
os.getcwd()

'/Users/jialincheoh/analysis-2017/d3-components'

In [4]:
# Here goes the automatic API downloading

all_functions = set()
classes_dict = dict()
with open("./API.md") as f: 
    #required_api_list.append(str_api.strip())
    readme_reader = csv.reader(f)
    readme_reader_iter = iter(readme_reader)
    current_class = 'init'
    next(readme_reader_iter) #skipping header
    for i,row in enumerate(readme_reader_iter):
        if row:
            if  row[0].startswith('## ['):
                current_class = row[0].split(']')[0].split('[')[-1].split('(')[-1].split(')')[0].strip()
                classes_dict[row[0].split(']')[0].split('[')[-1].split('(')[-1].split(')')[0].strip()] = dict()
                current_subclass = '_'
                classes_dict[current_class][current_subclass] = set()
            if row[0].startswith('### ['): 
                current_subclass = row[0].split(']')[0].split('[')[-1].split(' ')[0]
                classes_dict[current_class][current_subclass] = set()
            if '[d3.' in row[0]:
                all_functions.add('.'+row[0].split(']')[0].split('[')[-1].split('.')[-1])
                classes_dict[current_class][current_subclass].add('.'+row[0].split(']')[0].split('[')[-1].split('.')[-1])

package_component_list = list([['package','component']])
for package, semantic_class in classes_dict.items():
    for semantic_class, components in semantic_class.items():
        for component in components:
            package_component_list.append([package,component])

if 'results' not in os.listdir('.'):
    os.mkdir('results')

pd.DataFrame(package_component_list).to_csv('./packages_components.csv',index=False,header=False)

In [5]:
os.listdir('./data/spring2017-unal-goldironhack-phase1/')

['2017-Purdue-UNAL-IronHack-cap182',
 '2017-Purdue-UNAL-IronHack-nfmorenog',
 '2017-Purdue-UNAL-IronHack-falperezgo',
 '2017-Purdue-UNAL-IronHack-lfvalderrama',
 '2017-Purdue-UNAL-IronHack-xdanielsb',
 '2017-Purdue-UNAL-IronHack-ykchautai',
 '2017-Purdue-UNAL-IronHack-oeroaq',
 '2017-Purdue-UNAL-IronHack-Danielsv9207',
 '2017-Purdue-UNAL-IronHack-janoguerab',
 '2017-Purdue-UNAL-IronHack-nabautistal',
 '2017-Purdue-UNAL-IronHack-dsbarrerag',
 '2017-Purdue-UNAL-IronHack-Christian7sr',
 '2017-Purdue-UNAL-IronHack-Chranium',
 '2017-Purdue-UNAL-IronHack-srmedinac',
 '2017-Purdue-UNAL-IronHack-jucjimenezmo',
 '2017-Purdue-UNAL-IronHack-kgbayala528',
 '2017-Purdue-UNAL-IronHack-wolfstain',
 '2017-Purdue-UNAL-IronHack-DianaNavarrete',
 '2017-Purdue-UNAL-IronHack-bsgarciac',
 '2017-Purdue-UNAL-IronHack-jiapulidoar',
 '2017-Purdue-UNAL-IronHack-ronaldsg20',
 '2017-Purdue-UNAL-IronHack-bdcajicam',
 '2017-Purdue-UNAL-IronHack-andfsanchezlem',
 '2017-Purdue-UNAL-IronHack-li2266',
 '2017-Purdue-UNAL-IronHack-JulianaNino',
 '2017-Purdue-UNAL-IronHack-jonatan360',
 '2017-Purdue-UNAL-IronHack-camilo654',
 '2017-Purdue-UNAL-IronHack-stevenbustos',
 '2017-Purdue-UNAL-IronHack-jscontrerasp',
 '2017-Purdue-UNAL-IronHack-gsuarezc04',
 '2017-Purdue-UNAL-IronHack-jmalvarezd',
 '2017-Purdue-UNAL-IronHack-katherinsb',
 '2017-Purdue-UNAL-IronHack-annipi',
 '2017-Purdue-UNAL-IronHack-fmbernalb',
 '2017-Purdue-UNAL-IronHack-mballeng91',
 '2017-Purdue-UNAL-IronHack-jscastelblancoh',
 '2017-Purdue-UNAL-IronHack-capinzor',
 '2017-Purdue-UNAL-IronHack-jdsuarezj',
 '2017-Purdue-UNAL-IronHack-jufcontrerasco',
 '2017-Purdue-UNAL-IronHack-NicolasZon',
 '2017-Purdue-UNAL-IronHack-tres-iqus',
 '2017-Purdue-UNAL-IronHack-hsmartineza',
 '2017-Purdue-UNAL-IronHack-dfhincapiem',
 '2017-Purdue-UNAL-IronHack-gasierram',
 '2017-Purdue-UNAL-IronHack-JuanitoAli',
 '2017-Purdue-UNAL-IronHack-fabianr23',
 '2017-Purdue-UNAL-IronHack-leavendanoro',
 '2017-Purdue-UNAL-IronHack-ccvacad',
 '2017-Purdue-UNAL-IronHack-jcneivaa',
 '2017-Purdue-UNAL-IronHack-yocuervoc',
 '2017-Purdue-UNAL-IronHack-JoseMolano',
 '2017-Purdue-UNAL-IronHack-CSebasGomez',
 '2017-Purdue-UNAL-IronHack-juandavidro',
 '2017-Purdue-UNAL-IronHack-jdsolanos',
 '2017-Purdue-UNAL-IronHack-afceballosr',
 '2017-Purdue-UNAL-IronHack-DglyP',
 '2017-Purdue-UNAL-IronHack-jjrodriguezn',
 '2017-Purdue-UNAL-IronHack-CamiloRueda',
 '2017-Purdue-UNAL-IronHack-oserasoa',
 '2017-Purdue-UNAL-IronHack-joaortizro',
 '2017-Purdue-UNAL-IronHack-davidh17',
 '2017-Purdue-UNAL-IronHack-JairVillalba',
 '2017-Purdue-UNAL-IronHack-davidrh195',
 '2017-Purdue-UNAL-IronHack-juclopezso',
 '2017-Purdue-UNAL-IronHack-raulramirezp',
 '2017-Purdue-UNAL-IronHack-camilo13152',
 '2017-Purdue-UNAL-IronHack-kmendezp96',
 '2017-Purdue-UNAL-IronHack-miaborjaac',
 '2017-Purdue-UNAL-IronHack-dduartec',
 '2017-Purdue-UNAL-IronHack-crarojasca',
 '2017-Purdue-UNAL-IronHack-UNhcrodriguezl',
 '2017-Purdue-UNAL-IronHack-pipemax85',
 '2017-Purdue-UNAL-IronHack-ivdgonzalezco',
 '2017-Purdue-UNAL-IronHack-jesusfchavarro',
 '2017-Purdue-UNAL-IronHack-wilson911013',
 '2017-Purdue-UNAL-IronHack-JhonEmmanuelTorres',
 '2017-Purdue-UNAL-IronHack-jjmuesesq',
 '2017-Purdue-UNAL-IronHack-adamantwharf',
 '2017-Purdue-UNAL-IronHack-NicolasPrr',
 '2017-Purdue-UNAL-IronHack-luegilca',
 'README.md',
 '2017-Purdue-UNAL-IronHack-macuestap',
 '2017-Purdue-UNAL-IronHack-lemartinp',
 '2017-Purdue-UNAL-IronHack-dagofonseca',
 '2017-Purdue-UNAL-IronHack-jsviveroj',
 '2017-Purdue-UNAL-IronHack-luealfonsoru',
 '2017-Purdue-UNAL-IronHack-afforeroc',
 '2017-Purdue-UNAL-IronHack-djguzmanc',
 '2017-Purdue-UNAL-IronHack-uxjudges2',
 '2017-Purdue-UNAL-IronHack-cdcordobaa',
 '2017-Purdue-UNAL-IronHack-gcantem',
 '2017-Purdue-UNAL-IronHack-feartheGru',
 '2017-Purdue-UNAL-IronHack-lgmoralesa',
 '2017-Purdue-UNAL-IronHack-CristianLozano',
 '2017-Purdue-UNAL-IronHack-mdbelloc',
 '2017-Purdue-UNAL-IronHack-Yelis3',
 '2017-Purdue-UNAL-IronHack-joahernandezca',
 '2017-Purdue-UNAL-IronHack-anfmorenoso',
 '2017-Purdue-UNAL-IronHack-jumcorredorro',
 '2017-Purdue-UNAL-IronHack-begarzonf',
 '2017-Purdue-UNAL-IronHack-spenas',
 '2017-Purdue-UNAL-IronHack-smarquezo',
 '2017-Purdue-UNAL-IronHack-gabi04',
 '2017-Purdue-UNAL-IronHack-maikellPardo',
 '2017-Purdue-UNAL-IronHack-jmhurtadoc',
 '2017-Purdue-UNAL-IronHack-jusherrerama',
 '2017-Purdue-UNAL-IronHack-fevargasmo',
 '2017-Purdue-UNAL-IronHack-aldiazve',
 '2017-Purdue-UNAL-IronHack-lsfinite',
 '2017-Purdue-UNAL-IronHack-jorge52an',
 '2017-Purdue-UNAL-IronHack-daandradec',
 '2017-Purdue-UNAL-IronHack-jsnarvaezb',
 '2017-Purdue-UNAL-IronHack-capinillab',
 '2017-Purdue-UNAL-IronHack-djsanabriac',
 '2017-Purdue-UNAL-IronHack-cesarochoa2006',
 '2017-Purdue-UNAL-IronHack-juasmartinezbel',
 '2017-Purdue-UNAL-IronHack-debeltranc',
 '2017-Purdue-UNAL-IronHack-adriel62',
 '2017-Purdue-UNAL-IronHack-diegoaguevarar',
 '2017-Purdue-UNAL-IronHack-ligibrial',
 '2017-Purdue-UNAL-IronHack-juanescai',
 '2017-Purdue-UNAL-IronHack-jcrubioa',
 '2017-Purdue-UNAL-IronHack-Phoenixest',
 '2017-Purdue-UNAL-IronHack-juligarji',
 '2017-Purdue-UNAL-IronHack-kancas',
 '2017-Purdue-UNAL-IronHack-ItsNavi',
 '2017-Purdue-UNAL-IronHack-leguzman',
 '2017-Purdue-UNAL-IronHack-jmcuestasb',
 '2017-Purdue-UNAL-IronHack-sacastroc',
 '2017-Purdue-UNAL-IronHack-jhonsd1996',
 '2017-Purdue-UNAL-IronHack-jdmonroyg',
 '2017-Purdue-UNAL-IronHack-Zeugmax',
 '2017-Purdue-UNAL-IronHack-MogGy94',
 '2017-Purdue-UNAL-IronHack-sagilm',
 '2017-Purdue-UNAL-IronHack-sarizag',
 '2017-Purdue-UNAL-IronHack-dasalgadob',
 '2017-Purdue-UNAL-IronHack-Gantiva',
 '2017-Purdue-UNAL-IronHack-idrojasf',
 '2017-Purdue-UNAL-IronHack-Moimolcp',
 '2017-Purdue-UNAL-IronHack-anmmunozme',
 '2017-Purdue-UNAL-IronHack-jhriverasa',
 '2017-Purdue-UNAL-IronHack-fffeelipe',
 '2017-Purdue-UNAL-IronHack-gfalbarracinr',
 '2017-Purdue-UNAL-IronHack-cccristanchoc',
 '2017-Purdue-UNAL-IronHack-pcberriop',
 '2017-Purdue-UNAL-IronHack-ncampuzano',
 '2017-Purdue-UNAL-IronHack-helmeraac',
 '2017-Purdue-UNAL-IronHack-ofnanezn',
 '2017-Purdue-UNAL-IronHack-odprietoh',
 '2017-Purdue-UNAL-IronHack-maikellPardoA',
 '2017-Purdue-UNAL-IronHack-wapiravaguens',
 '2017-Purdue-UNAL-IronHack-Dandarprox',
 '2017-Purdue-UNAL-IronHack-HashNick',
 '2017-Purdue-UNAL-IronHack-diegocruz10',
 '2017-Purdue-UNAL-IronHack-Davsatu313',
 '2017-Purdue-UNAL-IronHack-lacardenasv',
 '2017-Purdue-UNAL-IronHack-bdvegat',
 '2017-Purdue-UNAL-IronHack-lizzyt10h',
 '2017-Purdue-UNAL-IronHack-DavidQP',
 '2017-Purdue-UNAL-IronHack-Judgarciani',
 '2017-Purdue-UNAL-IronHack-oacastillol',
 '2017-Purdue-UNAL-IronHack-mnguzmanc',
 '2017-Purdue-UNAL-IronHack-Semoralesga',
 '2017-Purdue-UNAL-IronHack-jhcardenasa',
 '2017-Purdue-UNAL-IronHack-crigar',
 '2017-Purdue-UNAL-IronHack-AFelipeGA']

In [6]:
d3_components_all =[components for val in classes_dict.values() for v in val.values() for components in list(v)]

In [7]:
df_phase1 = pd.DataFrame()

participants_code_path = './data/spring2017-unal-goldironhack-phase1/'  #'../../2-1 Raw/05 Participants code/'
for repo_folder in [ repo for repo in os.listdir(participants_code_path) if not repo.startswith('.')]:
    for root, folders, files in os.walk(participants_code_path+repo_folder):
        for file_name in files:
            if file_name.endswith(".js"):
                with open(os.path.join( root,  file_name)) as  file_object:
                    file_content = file_object.read()
                    d3_components = set()
                    #for d3 libraries
                    for d3_component in d3_components_all:
                        if d3_component in file_content:
                            class_d3 = [ '_'.join([d3class,subclass,d3_component]) for d3class, val in classes_dict.items() for subclass,components in val.items() if d3_component in components ]
                            if  class_d3:
                                d3_components.add(class_d3[0])
                                #libraries.append(d3_component)
                    num_components = len(list(d3_components))
                    df_phase1 = df_phase1.append(pd.DataFrame({'components':list(d3_components),"username_folder_name":num_components*[repo_folder],"js_loc_in_each_js":num_components*[len(file_content)]}))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [8]:
df_phase1

,components,username_folder_name,js_loc_in_each_js
0,d3-fetch___.json,2017-Purdue-UNAL-IronHack-nfmorenog,846.0
1,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nfmorenog,846.0
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-lfvalderrama,1855.0
1,d3-fetch___.json,2017-Purdue-UNAL-IronHack-lfvalderrama,1855.0
2,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-lfvalderrama,1855.0
...,...,...,...
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
1,d3-selection_Selecting_.selectAll,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
2,d3-selection_Selecting_.select,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
3,d3-selection_Selecting_.style,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
4,d3-selection_Modifying_.create,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0

In [9]:
df_phase1_count = df_phase1.groupby(['username_folder_name']).size().reset_index(name='count')
df_phase1_count

                      username_folder_name  count
0       2017-Purdue-UNAL-IronHack-Chranium      1
1      2017-Purdue-UNAL-IronHack-bsgarciac      1
2    2017-Purdue-UNAL-IronHack-jiapulidoar     28
3    2017-Purdue-UNAL-IronHack-kgbayala528      4
4   2017-Purdue-UNAL-IronHack-lfvalderrama      3
5      2017-Purdue-UNAL-IronHack-nfmorenog      2
6         2017-Purdue-UNAL-IronHack-oeroaq      7
7     2017-Purdue-UNAL-IronHack-ronaldsg20   1503
8      2017-Purdue-UNAL-IronHack-srmedinac      4
9      2017-Purdue-UNAL-IronHack-wolfstain      2
10     2017-Purdue-UNAL-IronHack-xdanielsb     53

In [10]:
components = df_phase1_count.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack     bsgarciac
2   017  Purdue  UNAL  IronHack   jiapulidoar
3   017  Purdue  UNAL  IronHack   kgbayala528
4   017  Purdue  UNAL  IronHack  lfvalderrama
5   017  Purdue  UNAL  IronHack     nfmorenog
6   017  Purdue  UNAL  IronHack        oeroaq
7   017  Purdue  UNAL  IronHack    ronaldsg20
8   017  Purdue  UNAL  IronHack     srmedinac
9   017  Purdue  UNAL  IronHack     wolfstain
10  017  Purdue  UNAL  IronHack     xdanielsb

In [11]:
df_phase1_count['name'] = components[4]
df_phase1_count

                      username_folder_name  count          name
0       2017-Purdue-UNAL-IronHack-Chranium      1      Chranium
1      2017-Purdue-UNAL-IronHack-bsgarciac      1     bsgarciac
2    2017-Purdue-UNAL-IronHack-jiapulidoar     28   jiapulidoar
3    2017-Purdue-UNAL-IronHack-kgbayala528      4   kgbayala528
4   2017-Purdue-UNAL-IronHack-lfvalderrama      3  lfvalderrama
5      2017-Purdue-UNAL-IronHack-nfmorenog      2     nfmorenog
6         2017-Purdue-UNAL-IronHack-oeroaq      7        oeroaq
7     2017-Purdue-UNAL-IronHack-ronaldsg20   1503    ronaldsg20
8      2017-Purdue-UNAL-IronHack-srmedinac      4     srmedinac
9      2017-Purdue-UNAL-IronHack-wolfstain      2     wolfstain
10     2017-Purdue-UNAL-IronHack-xdanielsb     53     xdanielsb

In [12]:
df_phase1_count.to_csv('Phase-1-Output.csv')

In [13]:
df_phase2 = pd.DataFrame()

participants_code_path = './data/spring2017-unal-goldironhack-phase2/'  #'../../2-1 Raw/05 Participants code/'
for repo_folder in [ repo for repo in os.listdir(participants_code_path) if not repo.startswith('.')]:
    for root, folders, files in os.walk(participants_code_path+repo_folder):
        for file_name in files:
            if file_name.endswith(".js"):
                with open(os.path.join( root,  file_name)) as  file_object:
                    file_content = file_object.read()
                    d3_components = set()
                    #for d3 libraries
                    for d3_component in d3_components_all:
                        if d3_component in file_content:
                            class_d3 = [ '_'.join([d3class,subclass,d3_component]) for d3class, val in classes_dict.items() for subclass,components in val.items() if d3_component in components ]
                            if  class_d3:
                                d3_components.add(class_d3[0])
                                #libraries.append(d3_component)
                    num_components = len(list(d3_components))
                    df_phase2 = df_phase2.append(pd.DataFrame({'components':list(d3_components),"username_folder_name":num_components*[repo_folder],"js_loc_in_each_js":num_components*[len(file_content)]}))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [14]:
df_phase2_count = df_phase2.groupby(['username_folder_name']).size().reset_index(name='count')
df_phase2_count

                      username_folder_name  count
0       2017-Purdue-UNAL-IronHack-Chranium      1
1      2017-Purdue-UNAL-IronHack-bsgarciac      4
2     2017-Purdue-UNAL-IronHack-dsbarrerag      3
3     2017-Purdue-UNAL-IronHack-falperezgo     52
4    2017-Purdue-UNAL-IronHack-jiapulidoar   3007
5    2017-Purdue-UNAL-IronHack-kgbayala528      4
6   2017-Purdue-UNAL-IronHack-lfvalderrama      3
7      2017-Purdue-UNAL-IronHack-nfmorenog      3
8         2017-Purdue-UNAL-IronHack-oeroaq     10
9     2017-Purdue-UNAL-IronHack-ronaldsg20   1503
10     2017-Purdue-UNAL-IronHack-srmedinac     75
11     2017-Purdue-UNAL-IronHack-wolfstain      3
12     2017-Purdue-UNAL-IronHack-xdanielsb     71

In [15]:
components = df_phase2_count.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack     bsgarciac
2   017  Purdue  UNAL  IronHack    dsbarrerag
3   017  Purdue  UNAL  IronHack    falperezgo
4   017  Purdue  UNAL  IronHack   jiapulidoar
5   017  Purdue  UNAL  IronHack   kgbayala528
6   017  Purdue  UNAL  IronHack  lfvalderrama
7   017  Purdue  UNAL  IronHack     nfmorenog
8   017  Purdue  UNAL  IronHack        oeroaq
9   017  Purdue  UNAL  IronHack    ronaldsg20
10  017  Purdue  UNAL  IronHack     srmedinac
11  017  Purdue  UNAL  IronHack     wolfstain
12  017  Purdue  UNAL  IronHack     xdanielsb

In [16]:
df_phase2_count['name'] = components[4]
df_phase2_count

                      username_folder_name  count          name
0       2017-Purdue-UNAL-IronHack-Chranium      1      Chranium
1      2017-Purdue-UNAL-IronHack-bsgarciac      4     bsgarciac
2     2017-Purdue-UNAL-IronHack-dsbarrerag      3    dsbarrerag
3     2017-Purdue-UNAL-IronHack-falperezgo     52    falperezgo
4    2017-Purdue-UNAL-IronHack-jiapulidoar   3007   jiapulidoar
5    2017-Purdue-UNAL-IronHack-kgbayala528      4   kgbayala528
6   2017-Purdue-UNAL-IronHack-lfvalderrama      3  lfvalderrama
7      2017-Purdue-UNAL-IronHack-nfmorenog      3     nfmorenog
8         2017-Purdue-UNAL-IronHack-oeroaq     10        oeroaq
9     2017-Purdue-UNAL-IronHack-ronaldsg20   1503    ronaldsg20
10     2017-Purdue-UNAL-IronHack-srmedinac     75     srmedinac
11     2017-Purdue-UNAL-IronHack-wolfstain      3     wolfstain
12     2017-Purdue-UNAL-IronHack-xdanielsb     71     xdanielsb

In [17]:
df_phase2_count.to_csv('Phase-2-Output.csv')

In [18]:
os.listdir(participants_code_path)

['2017-Purdue-UNAL-IronHack-cap182',
 '2017-Purdue-UNAL-IronHack-nfmorenog',
 '2017-Purdue-UNAL-IronHack-falperezgo',
 '2017-Purdue-UNAL-IronHack-lfvalderrama',
 '2017-Purdue-UNAL-IronHack-xdanielsb',
 '2017-Purdue-UNAL-IronHack-ykchautai',
 '2017-Purdue-UNAL-IronHack-oeroaq',
 '2017-Purdue-UNAL-IronHack-Danielsv9207',
 '2017-Purdue-UNAL-IronHack-janoguerab',
 '2017-Purdue-UNAL-IronHack-nabautistal',
 '2017-Purdue-UNAL-IronHack-dsbarrerag',
 '2017-Purdue-UNAL-IronHack-Christian7sr',
 '2017-Purdue-UNAL-IronHack-Chranium',
 '2017-Purdue-UNAL-IronHack-srmedinac',
 '2017-Purdue-UNAL-IronHack-jucjimenezmo',
 '2017-Purdue-UNAL-IronHack-kgbayala528',
 '2017-Purdue-UNAL-IronHack-wolfstain',
 '2017-Purdue-UNAL-IronHack-DianaNavarrete',
 '2017-Purdue-UNAL-IronHack-bsgarciac',
 '2017-Purdue-UNAL-IronHack-jiapulidoar',
 '2017-Purdue-UNAL-IronHack-ronaldsg20',
 '2017-Purdue-UNAL-IronHack-bdcajicam',
 '2017-Purdue-UNAL-IronHack-andfsanchezlem',
 '2017-Purdue-UNAL-IronHack-li2266',
 '2017-Purdue-UNAL-IronHack-JulianaNino',
 '2017-Purdue-UNAL-IronHack-jonatan360',
 '2017-Purdue-UNAL-IronHack-camilo654',
 '2017-Purdue-UNAL-IronHack-stevenbustos',
 '2017-Purdue-UNAL-IronHack-jscontrerasp',
 '2017-Purdue-UNAL-IronHack-gsuarezc04',
 '2017-Purdue-UNAL-IronHack-jmalvarezd',
 '2017-Purdue-UNAL-IronHack-katherinsb',
 '2017-Purdue-UNAL-IronHack-annipi',
 '2017-Purdue-UNAL-IronHack-fmbernalb',
 '2017-Purdue-UNAL-IronHack-mballeng91',
 '2017-Purdue-UNAL-IronHack-jscastelblancoh',
 '2017-Purdue-UNAL-IronHack-capinzor',
 '2017-Purdue-UNAL-IronHack-jdsuarezj',
 '2017-Purdue-UNAL-IronHack-jufcontrerasco',
 '2017-Purdue-UNAL-IronHack-NicolasZon',
 '2017-Purdue-UNAL-IronHack-tres-iqus',
 '2017-Purdue-UNAL-IronHack-hsmartineza',
 '2017-Purdue-UNAL-IronHack-dfhincapiem',
 '2017-Purdue-UNAL-IronHack-gasierram',
 '2017-Purdue-UNAL-IronHack-JuanitoAli',
 '2017-Purdue-UNAL-IronHack-fabianr23',
 '2017-Purdue-UNAL-IronHack-leavendanoro',
 '2017-Purdue-UNAL-IronHack-ccvacad',
 '2017-Purdue-UNAL-IronHack-jcneivaa',
 '2017-Purdue-UNAL-IronHack-yocuervoc',
 '2017-Purdue-UNAL-IronHack-JoseMolano',
 '2017-Purdue-UNAL-IronHack-CSebasGomez',
 '2017-Purdue-UNAL-IronHack-juandavidro',
 '2017-Purdue-UNAL-IronHack-jdsolanos',
 '2017-Purdue-UNAL-IronHack-afceballosr',
 '2017-Purdue-UNAL-IronHack-DglyP',
 '2017-Purdue-UNAL-IronHack-jjrodriguezn',
 '2017-Purdue-UNAL-IronHack-CamiloRueda',
 '2017-Purdue-UNAL-IronHack-oserasoa',
 '2017-Purdue-UNAL-IronHack-joaortizro',
 '2017-Purdue-UNAL-IronHack-davidh17',
 '2017-Purdue-UNAL-IronHack-JairVillalba',
 '2017-Purdue-UNAL-IronHack-davidrh195',
 '2017-Purdue-UNAL-IronHack-juclopezso',
 '2017-Purdue-UNAL-IronHack-raulramirezp',
 '2017-Purdue-UNAL-IronHack-camilo13152',
 '2017-Purdue-UNAL-IronHack-kmendezp96',
 '2017-Purdue-UNAL-IronHack-miaborjaac',
 '2017-Purdue-UNAL-IronHack-dduartec',
 '2017-Purdue-UNAL-IronHack-crarojasca',
 '2017-Purdue-UNAL-IronHack-UNhcrodriguezl',
 '2017-Purdue-UNAL-IronHack-pipemax85',
 '2017-Purdue-UNAL-IronHack-ivdgonzalezco',
 '2017-Purdue-UNAL-IronHack-jesusfchavarro',
 '2017-Purdue-UNAL-IronHack-wilson911013',
 '2017-Purdue-UNAL-IronHack-JhonEmmanuelTorres',
 '2017-Purdue-UNAL-IronHack-jjmuesesq',
 '2017-Purdue-UNAL-IronHack-adamantwharf',
 '2017-Purdue-UNAL-IronHack-NicolasPrr',
 '2017-Purdue-UNAL-IronHack-luegilca',
 'README.md',
 '2017-Purdue-UNAL-IronHack-macuestap',
 '2017-Purdue-UNAL-IronHack-lemartinp',
 '2017-Purdue-UNAL-IronHack-dagofonseca',
 '2017-Purdue-UNAL-IronHack-jsviveroj',
 '2017-Purdue-UNAL-IronHack-luealfonsoru',
 '2017-Purdue-UNAL-IronHack-afforeroc',
 '2017-Purdue-UNAL-IronHack-djguzmanc',
 '2017-Purdue-UNAL-IronHack-uxjudges2',
 '2017-Purdue-UNAL-IronHack-cdcordobaa',
 '2017-Purdue-UNAL-IronHack-gcantem',
 '2017-Purdue-UNAL-IronHack-feartheGru',
 '2017-Purdue-UNAL-IronHack-lgmoralesa',
 '2017-Purdue-UNAL-IronHack-CristianLozano',
 '2017-Purdue-UNAL-IronHack-mdbelloc',
 '2017-Purdue-UNAL-IronHack-Yelis3',
 '2017-Purdue-UNAL-IronHack-joahernandezca',
 '2017-Purdue-UNAL-IronHack-anfmorenoso',
 '2017-Purdue-UNAL-IronHack-jumcorredorro',
 '2017-Purdue-UNAL-IronHack-begarzonf',
 '2017-Purdue-UNAL-IronHack-spenas',
 '2017-Purdue-UNAL-IronHack-smarquezo',
 '2017-Purdue-UNAL-IronHack-gabi04',
 '2017-Purdue-UNAL-IronHack-maikellPardo',
 '2017-Purdue-UNAL-IronHack-jmhurtadoc',
 '2017-Purdue-UNAL-IronHack-jusherrerama',
 '2017-Purdue-UNAL-IronHack-fevargasmo',
 '2017-Purdue-UNAL-IronHack-aldiazve',
 '2017-Purdue-UNAL-IronHack-lsfinite',
 '2017-Purdue-UNAL-IronHack-jorge52an',
 '2017-Purdue-UNAL-IronHack-daandradec',
 '2017-Purdue-UNAL-IronHack-jsnarvaezb',
 '2017-Purdue-UNAL-IronHack-capinillab',
 '2017-Purdue-UNAL-IronHack-djsanabriac',
 '2017-Purdue-UNAL-IronHack-cesarochoa2006',
 '2017-Purdue-UNAL-IronHack-juasmartinezbel',
 '2017-Purdue-UNAL-IronHack-debeltranc',
 '2017-Purdue-UNAL-IronHack-adriel62',
 '2017-Purdue-UNAL-IronHack-diegoaguevarar',
 '2017-Purdue-UNAL-IronHack-ligibrial',
 '2017-Purdue-UNAL-IronHack-juanescai',
 '2017-Purdue-UNAL-IronHack-jcrubioa',
 '2017-Purdue-UNAL-IronHack-Phoenixest',
 '2017-Purdue-UNAL-IronHack-juligarji',
 '2017-Purdue-UNAL-IronHack-kancas',
 '2017-Purdue-UNAL-IronHack-ItsNavi',
 '2017-Purdue-UNAL-IronHack-leguzman',
 '2017-Purdue-UNAL-IronHack-jmcuestasb',
 '2017-Purdue-UNAL-IronHack-sacastroc',
 '2017-Purdue-UNAL-IronHack-jhonsd1996',
 '2017-Purdue-UNAL-IronHack-jdmonroyg',
 '2017-Purdue-UNAL-IronHack-Zeugmax',
 '2017-Purdue-UNAL-IronHack-MogGy94',
 '2017-Purdue-UNAL-IronHack-sagilm',
 '2017-Purdue-UNAL-IronHack-sarizag',
 '2017-Purdue-UNAL-IronHack-dasalgadob',
 '2017-Purdue-UNAL-IronHack-Gantiva',
 '2017-Purdue-UNAL-IronHack-idrojasf',
 '2017-Purdue-UNAL-IronHack-Moimolcp',
 '2017-Purdue-UNAL-IronHack-anmmunozme',
 '2017-Purdue-UNAL-IronHack-jhriverasa',
 '2017-Purdue-UNAL-IronHack-fffeelipe',
 '2017-Purdue-UNAL-IronHack-gfalbarracinr',
 '2017-Purdue-UNAL-IronHack-cccristanchoc',
 '2017-Purdue-UNAL-IronHack-pcberriop',
 '2017-Purdue-UNAL-IronHack-ncampuzano',
 '2017-Purdue-UNAL-IronHack-helmeraac',
 '2017-Purdue-UNAL-IronHack-ofnanezn',
 '2017-Purdue-UNAL-IronHack-odprietoh',
 '2017-Purdue-UNAL-IronHack-maikellPardoA',
 '2017-Purdue-UNAL-IronHack-wapiravaguens',
 '2017-Purdue-UNAL-IronHack-Dandarprox',
 '2017-Purdue-UNAL-IronHack-HashNick',
 '2017-Purdue-UNAL-IronHack-diegocruz10',
 '2017-Purdue-UNAL-IronHack-Davsatu313',
 '2017-Purdue-UNAL-IronHack-lacardenasv',
 '2017-Purdue-UNAL-IronHack-bdvegat',
 '2017-Purdue-UNAL-IronHack-lizzyt10h',
 '2017-Purdue-UNAL-IronHack-DavidQP',
 '2017-Purdue-UNAL-IronHack-Judgarciani',
 '2017-Purdue-UNAL-IronHack-oacastillol',
 '2017-Purdue-UNAL-IronHack-mnguzmanc',
 '2017-Purdue-UNAL-IronHack-Semoralesga',
 '2017-Purdue-UNAL-IronHack-jhcardenasa',
 '2017-Purdue-UNAL-IronHack-crigar',
 '2017-Purdue-UNAL-IronHack-AFelipeGA']

In [19]:
# https://stackoverflow.com/questions/50382685/i-use-chardet-to-test-encode-but-i-got-error

import chardet
print(chardet.detect(file_content.encode()))

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [20]:
df_phase3 = pd.DataFrame()

participants_code_path = './data/spring2017-unal-goldironhack-phase3/'  #'../../2-1 Raw/05 Participants code/'
for repo_folder in [ repo for repo in os.listdir(participants_code_path) if not repo.startswith('.')]:
    for root, folders, files in os.walk(participants_code_path+repo_folder):
        for file_name in files:
            if file_name.endswith(".js"):
                with open(os.path.join( root,  file_name)) as  file_object:
                    file_content = file_object.read()
                    d3_components = set()
                    #for d3 libraries
                    for d3_component in d3_components_all:
                        if d3_component in file_content:
                            class_d3 = [ '_'.join([d3class,subclass,d3_component]) for d3class, val in classes_dict.items() for subclass,components in val.items() if d3_component in components ]
                            if  class_d3:
                                d3_components.add(class_d3[0])
                                #libraries.append(d3_component)
                    num_components = len(list(d3_components))
                    df_phase3 = df_phase3.append(pd.DataFrame({'components':list(d3_components),"username_folder_name":num_components*[repo_folder],"js_loc_in_each_js":num_components*[len(file_content)]}))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [21]:
df_phase3_count = df_phase3.groupby(['username_folder_name']).size().reset_index(name='count')
df_phase3_count

                      username_folder_name  count
0       2017-Purdue-UNAL-IronHack-Chranium      1
1   2017-Purdue-UNAL-IronHack-Christian7sr      1
2      2017-Purdue-UNAL-IronHack-bsgarciac     14
3     2017-Purdue-UNAL-IronHack-dsbarrerag      5
4     2017-Purdue-UNAL-IronHack-falperezgo     52
5    2017-Purdue-UNAL-IronHack-jiapulidoar   3009
6    2017-Purdue-UNAL-IronHack-kgbayala528      4
7   2017-Purdue-UNAL-IronHack-lfvalderrama      6
8      2017-Purdue-UNAL-IronHack-nfmorenog      3
9         2017-Purdue-UNAL-IronHack-oeroaq     58
10    2017-Purdue-UNAL-IronHack-ronaldsg20   1505
11     2017-Purdue-UNAL-IronHack-srmedinac     75
12     2017-Purdue-UNAL-IronHack-wolfstain     55
13     2017-Purdue-UNAL-IronHack-xdanielsb     94

In [22]:
components = df_phase3_count.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack  Christian7sr
2   017  Purdue  UNAL  IronHack     bsgarciac
3   017  Purdue  UNAL  IronHack    dsbarrerag
4   017  Purdue  UNAL  IronHack    falperezgo
5   017  Purdue  UNAL  IronHack   jiapulidoar
6   017  Purdue  UNAL  IronHack   kgbayala528
7   017  Purdue  UNAL  IronHack  lfvalderrama
8   017  Purdue  UNAL  IronHack     nfmorenog
9   017  Purdue  UNAL  IronHack        oeroaq
10  017  Purdue  UNAL  IronHack    ronaldsg20
11  017  Purdue  UNAL  IronHack     srmedinac
12  017  Purdue  UNAL  IronHack     wolfstain
13  017  Purdue  UNAL  IronHack     xdanielsb

In [23]:
df_phase3_count['name'] = components[4]
df_phase3_count

                      username_folder_name  count          name
0       2017-Purdue-UNAL-IronHack-Chranium      1      Chranium
1   2017-Purdue-UNAL-IronHack-Christian7sr      1  Christian7sr
2      2017-Purdue-UNAL-IronHack-bsgarciac     14     bsgarciac
3     2017-Purdue-UNAL-IronHack-dsbarrerag      5    dsbarrerag
4     2017-Purdue-UNAL-IronHack-falperezgo     52    falperezgo
5    2017-Purdue-UNAL-IronHack-jiapulidoar   3009   jiapulidoar
6    2017-Purdue-UNAL-IronHack-kgbayala528      4   kgbayala528
7   2017-Purdue-UNAL-IronHack-lfvalderrama      6  lfvalderrama
8      2017-Purdue-UNAL-IronHack-nfmorenog      3     nfmorenog
9         2017-Purdue-UNAL-IronHack-oeroaq     58        oeroaq
10    2017-Purdue-UNAL-IronHack-ronaldsg20   1505    ronaldsg20
11     2017-Purdue-UNAL-IronHack-srmedinac     75     srmedinac
12     2017-Purdue-UNAL-IronHack-wolfstain     55     wolfstain
13     2017-Purdue-UNAL-IronHack-xdanielsb     94     xdanielsb

In [24]:
df_phase3_count.to_csv('Phase-3-Output.csv')

In [25]:
df_phase4 = pd.DataFrame()

participants_code_path = './data/spring2017-unal-goldironhack-phase4/'  #'../../2-1 Raw/05 Participants code/'
for repo_folder in [ repo for repo in os.listdir(participants_code_path) if not repo.startswith('.')]:
    for root, folders, files in os.walk(participants_code_path+repo_folder):
        for file_name in files:
            if file_name.endswith(".js"):
                with open(os.path.join( root,  file_name)) as  file_object:
                    file_content = file_object.read()
                    d3_components = set()
                    #for d3 libraries
                    for d3_component in d3_components_all:
                        if d3_component in file_content:
                            class_d3 = [ '_'.join([d3class,subclass,d3_component]) for d3class, val in classes_dict.items() for subclass,components in val.items() if d3_component in components ]
                            if  class_d3:
                                d3_components.add(class_d3[0])
                                #libraries.append(d3_component)
                    num_components = len(list(d3_components))
                    df_phase4 = df_phase4.append(pd.DataFrame({'components':list(d3_components),"username_folder_name":num_components*[repo_folder],"js_loc_in_each_js":num_components*[len(file_content)]}))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [26]:
df_phase4_count = df_phase4.groupby(['username_folder_name']).size().reset_index(name='count')
df_phase4_count

                      username_folder_name  count
0       2017-Purdue-UNAL-IronHack-Chranium      1
1   2017-Purdue-UNAL-IronHack-Christian7sr      1
2      2017-Purdue-UNAL-IronHack-bsgarciac      9
3     2017-Purdue-UNAL-IronHack-dsbarrerag      5
4     2017-Purdue-UNAL-IronHack-falperezgo     59
5    2017-Purdue-UNAL-IronHack-jiapulidoar   3009
6   2017-Purdue-UNAL-IronHack-jucjimenezmo      4
7    2017-Purdue-UNAL-IronHack-kgbayala528      4
8   2017-Purdue-UNAL-IronHack-lfvalderrama      6
9      2017-Purdue-UNAL-IronHack-nfmorenog      3
10        2017-Purdue-UNAL-IronHack-oeroaq    115
11    2017-Purdue-UNAL-IronHack-ronaldsg20   1506
12     2017-Purdue-UNAL-IronHack-srmedinac     75
13     2017-Purdue-UNAL-IronHack-wolfstain     56
14     2017-Purdue-UNAL-IronHack-xdanielsb     94

In [27]:
components = df_phase4_count.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack  Christian7sr
2   017  Purdue  UNAL  IronHack     bsgarciac
3   017  Purdue  UNAL  IronHack    dsbarrerag
4   017  Purdue  UNAL  IronHack    falperezgo
5   017  Purdue  UNAL  IronHack   jiapulidoar
6   017  Purdue  UNAL  IronHack  jucjimenezmo
7   017  Purdue  UNAL  IronHack   kgbayala528
8   017  Purdue  UNAL  IronHack  lfvalderrama
9   017  Purdue  UNAL  IronHack     nfmorenog
10  017  Purdue  UNAL  IronHack        oeroaq
11  017  Purdue  UNAL  IronHack    ronaldsg20
12  017  Purdue  UNAL  IronHack     srmedinac
13  017  Purdue  UNAL  IronHack     wolfstain
14  017  Purdue  UNAL  IronHack     xdanielsb

In [28]:
df_phase4_count['name'] = components[4]
df_phase4_count

                      username_folder_name  count          name
0       2017-Purdue-UNAL-IronHack-Chranium      1      Chranium
1   2017-Purdue-UNAL-IronHack-Christian7sr      1  Christian7sr
2      2017-Purdue-UNAL-IronHack-bsgarciac      9     bsgarciac
3     2017-Purdue-UNAL-IronHack-dsbarrerag      5    dsbarrerag
4     2017-Purdue-UNAL-IronHack-falperezgo     59    falperezgo
5    2017-Purdue-UNAL-IronHack-jiapulidoar   3009   jiapulidoar
6   2017-Purdue-UNAL-IronHack-jucjimenezmo      4  jucjimenezmo
7    2017-Purdue-UNAL-IronHack-kgbayala528      4   kgbayala528
8   2017-Purdue-UNAL-IronHack-lfvalderrama      6  lfvalderrama
9      2017-Purdue-UNAL-IronHack-nfmorenog      3     nfmorenog
10        2017-Purdue-UNAL-IronHack-oeroaq    115        oeroaq
11    2017-Purdue-UNAL-IronHack-ronaldsg20   1506    ronaldsg20
12     2017-Purdue-UNAL-IronHack-srmedinac     75     srmedinac
13     2017-Purdue-UNAL-IronHack-wolfstain     56     wolfstain
14     2017-Purdue-UNAL-IronHack-xdanielsb     94     xdanielsb

In [29]:
df_phase4_count.to_csv('Phase-4-Output.csv')

In [30]:
df_phase5 = pd.DataFrame()

participants_code_path = './data/spring2017-unal-goldironhack-phase5/'  #'../../2-1 Raw/05 Participants code/'
for repo_folder in [ repo for repo in os.listdir(participants_code_path) if not repo.startswith('.')]:
    for root, folders, files in os.walk(participants_code_path+repo_folder):
        for file_name in files:
            if file_name.endswith(".js"):
                with open(os.path.join( root,  file_name)) as  file_object:
                    file_content = file_object.read()
                    d3_components = set()
                    #for d3 libraries
                    for d3_component in d3_components_all:
                        if d3_component in file_content:
                            class_d3 = [ '_'.join([d3class,subclass,d3_component]) for d3class, val in classes_dict.items() for subclass,components in val.items() if d3_component in components ]
                            if  class_d3:
                                d3_components.add(class_d3[0])
                                #libraries.append(d3_component)
                    num_components = len(list(d3_components))
                    df_phase5 = df_phase5.append(pd.DataFrame({'components':list(d3_components),"username_folder_name":num_components*[repo_folder],"js_loc_in_each_js":num_components*[len(file_content)]}))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [31]:
df_phase5

,components,username_folder_name,js_loc_in_each_js
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-nfmorenog,5857.0
1,d3-fetch___.json,2017-Purdue-UNAL-IronHack-nfmorenog,5857.0
2,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nfmorenog,5857.0
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-falperezgo,13466.0
1,d3-fetch___.json,2017-Purdue-UNAL-IronHack-falperezgo,13466.0
...,...,...,...
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
1,d3-selection_Selecting_.selectAll,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
2,d3-selection_Selecting_.select,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
3,d3-selection_Selecting_.style,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0
4,d3-selection_Modifying_.create,2017-Purdue-UNAL-IronHack-ronaldsg20,4247.0

In [32]:
df_phase5_count = df_phase5.groupby(['username_folder_name']).size().reset_index(name='count')
df_phase5_count

                      username_folder_name  count
0       2017-Purdue-UNAL-IronHack-Chranium      1
1   2017-Purdue-UNAL-IronHack-Christian7sr      4
2      2017-Purdue-UNAL-IronHack-bsgarciac      9
3     2017-Purdue-UNAL-IronHack-dsbarrerag      6
4     2017-Purdue-UNAL-IronHack-falperezgo     59
5    2017-Purdue-UNAL-IronHack-jiapulidoar   3011
6   2017-Purdue-UNAL-IronHack-jucjimenezmo      4
7    2017-Purdue-UNAL-IronHack-kgbayala528      4
8   2017-Purdue-UNAL-IronHack-lfvalderrama      5
9    2017-Purdue-UNAL-IronHack-nabautistal      8
10     2017-Purdue-UNAL-IronHack-nfmorenog      3
11        2017-Purdue-UNAL-IronHack-oeroaq     92
12    2017-Purdue-UNAL-IronHack-ronaldsg20   1508
13     2017-Purdue-UNAL-IronHack-srmedinac     75
14     2017-Purdue-UNAL-IronHack-wolfstain     56
15     2017-Purdue-UNAL-IronHack-xdanielsb    133

In [33]:
components = df_phase5_count.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack  Christian7sr
2   017  Purdue  UNAL  IronHack     bsgarciac
3   017  Purdue  UNAL  IronHack    dsbarrerag
4   017  Purdue  UNAL  IronHack    falperezgo
5   017  Purdue  UNAL  IronHack   jiapulidoar
6   017  Purdue  UNAL  IronHack  jucjimenezmo
7   017  Purdue  UNAL  IronHack   kgbayala528
8   017  Purdue  UNAL  IronHack  lfvalderrama
9   017  Purdue  UNAL  IronHack   nabautistal
10  017  Purdue  UNAL  IronHack     nfmorenog
11  017  Purdue  UNAL  IronHack        oeroaq
12  017  Purdue  UNAL  IronHack    ronaldsg20
13  017  Purdue  UNAL  IronHack     srmedinac
14  017  Purdue  UNAL  IronHack     wolfstain
15  017  Purdue  UNAL  IronHack     xdanielsb

In [34]:
df_phase5_count['name'] = components[4]
df_phase5_count

                      username_folder_name  count          name
0       2017-Purdue-UNAL-IronHack-Chranium      1      Chranium
1   2017-Purdue-UNAL-IronHack-Christian7sr      4  Christian7sr
2      2017-Purdue-UNAL-IronHack-bsgarciac      9     bsgarciac
3     2017-Purdue-UNAL-IronHack-dsbarrerag      6    dsbarrerag
4     2017-Purdue-UNAL-IronHack-falperezgo     59    falperezgo
5    2017-Purdue-UNAL-IronHack-jiapulidoar   3011   jiapulidoar
6   2017-Purdue-UNAL-IronHack-jucjimenezmo      4  jucjimenezmo
7    2017-Purdue-UNAL-IronHack-kgbayala528      4   kgbayala528
8   2017-Purdue-UNAL-IronHack-lfvalderrama      5  lfvalderrama
9    2017-Purdue-UNAL-IronHack-nabautistal      8   nabautistal
10     2017-Purdue-UNAL-IronHack-nfmorenog      3     nfmorenog
11        2017-Purdue-UNAL-IronHack-oeroaq     92        oeroaq
12    2017-Purdue-UNAL-IronHack-ronaldsg20   1508    ronaldsg20
13     2017-Purdue-UNAL-IronHack-srmedinac     75     srmedinac
14     2017-Purdue-UNAL-IronHack-wolfstain     56     wolfstain
15     2017-Purdue-UNAL-IronHack-xdanielsb    133     xdanielsb

In [35]:
df_phase5_count.to_csv('Phase-5-Output.csv')

In [36]:
df_phase1_drop = df_phase1.drop('js_loc_in_each_js', 1)
df_phase2_drop = df_phase2.drop('js_loc_in_each_js', 1)

In [37]:
mergedDF_12 = pd.merge(df_phase1_drop, df_phase2_drop, how='outer',on=['username_folder_name','components'],indicator=True)
mergedDF_12

,components,username_folder_name,_merge
0,d3-fetch___.json,2017-Purdue-UNAL-IronHack-nfmorenog,both
1,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nfmorenog,both
2,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-lfvalderrama,both
3,d3-fetch___.json,2017-Purdue-UNAL-IronHack-lfvalderrama,both
4,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-lfvalderrama,both
...,...,...,...
123228,d3-interpolate___.interpolateString,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
123229,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
123230,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
123231,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
123232,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only

In [38]:
df_phase3_drop = df_phase3.drop('js_loc_in_each_js', 1)

In [39]:
mergedDF_23 = pd.merge(df_phase2_drop, df_phase3_drop, how='outer',on=['username_folder_name','components'],indicator=True)
mergedDF_23

,components,username_folder_name,_merge
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-nfmorenog,both
1,d3-fetch___.json,2017-Purdue-UNAL-IronHack-nfmorenog,both
2,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nfmorenog,both
3,d3-timer___.now,2017-Purdue-UNAL-IronHack-falperezgo,both
4,d3-timer___.now,2017-Purdue-UNAL-IronHack-falperezgo,both
...,...,...,...
584805,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-bsgarciac,right_only
584806,d3-selection_Modifying_.create,2017-Purdue-UNAL-IronHack-bsgarciac,right_only
584807,d3-selection_Modifying_.create,2017-Purdue-UNAL-IronHack-bsgarciac,right_only
584808,d3-color___.color,2017-Purdue-UNAL-IronHack-bsgarciac,right_only
584809,d3-color___.color,2017-Purdue-UNAL-IronHack-bsgarciac,right_only

In [40]:
df_phase4_drop = df_phase4.drop('js_loc_in_each_js', 1)

In [41]:
mergedDF_34 = pd.merge(df_phase3_drop, df_phase4_drop, how='outer',on=['username_folder_name','components'],indicator=True)
mergedDF_34

,components,username_folder_name,_merge
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-nfmorenog,both
1,d3-fetch___.json,2017-Purdue-UNAL-IronHack-nfmorenog,both
2,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nfmorenog,both
3,d3-timer___.now,2017-Purdue-UNAL-IronHack-falperezgo,both
4,d3-timer___.now,2017-Purdue-UNAL-IronHack-falperezgo,both
...,...,...,...
585663,d3-fetch___.json,2017-Purdue-UNAL-IronHack-jucjimenezmo,right_only
585664,d3-selection_Handling_.event,2017-Purdue-UNAL-IronHack-jucjimenezmo,right_only
585665,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-jucjimenezmo,right_only
585666,d3-selection_Selecting_.select,2017-Purdue-UNAL-IronHack-bsgarciac,right_only
585667,d3-selection_Selecting_.selectAll,2017-Purdue-UNAL-IronHack-bsgarciac,right_only

In [42]:
df_phase5_drop = df_phase5.drop('js_loc_in_each_js', 1)

In [43]:
mergedDF_45 = pd.merge(df_phase4_drop, df_phase5_drop, how='outer',on=['username_folder_name','components'],indicator=True)
mergedDF_45

,components,username_folder_name,_merge
0,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-nfmorenog,both
1,d3-fetch___.json,2017-Purdue-UNAL-IronHack-nfmorenog,both
2,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nfmorenog,both
3,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-falperezgo,both
4,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-falperezgo,both
...,...,...,...
586535,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nabautistal,right_only
586536,d3-selection_Modifying_.create,2017-Purdue-UNAL-IronHack-dsbarrerag,right_only
586537,d3-selection_Local_.local,2017-Purdue-UNAL-IronHack-Christian7sr,right_only
586538,d3-shape_Lines_.line,2017-Purdue-UNAL-IronHack-Christian7sr,right_only
586539,d3-fetch___.text,2017-Purdue-UNAL-IronHack-Christian7sr,right_only

In [44]:
mergedDF_15 = pd.merge(df_phase1_drop, df_phase5_drop, how='outer',on=['username_folder_name','components'],indicator=True)
mergedDF_15

,components,username_folder_name,_merge
0,d3-fetch___.json,2017-Purdue-UNAL-IronHack-nfmorenog,both
1,d3-collection_Maps_.map,2017-Purdue-UNAL-IronHack-nfmorenog,both
2,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-lfvalderrama,both
3,d3-collection_Sets_.set,2017-Purdue-UNAL-IronHack-lfvalderrama,both
4,d3-fetch___.json,2017-Purdue-UNAL-IronHack-lfvalderrama,both
...,...,...,...
124054,d3-interpolate___.interpolateString,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
124055,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
124056,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
124057,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only
124058,d3-array_Transformations_.permute,2017-Purdue-UNAL-IronHack-jiapulidoar,right_only

In [45]:
mergedDF_15_final = mergedDF_15.groupby(['username_folder_name', '_merge']).size().unstack(fill_value=0)
mergedDF_15_final

_merge                                  left_only  right_only    both
username_folder_name
2017-Purdue-UNAL-IronHack-Chranium              0           0       1
2017-Purdue-UNAL-IronHack-Christian7sr          0           4       0
2017-Purdue-UNAL-IronHack-bsgarciac             0           8       1
2017-Purdue-UNAL-IronHack-dsbarrerag            0           6       0
2017-Purdue-UNAL-IronHack-falperezgo            0          59       0
2017-Purdue-UNAL-IronHack-jiapulidoar           0        1017    2622
2017-Purdue-UNAL-IronHack-jucjimenezmo          0           4       0
2017-Purdue-UNAL-IronHack-kgbayala528           0           0       4
2017-Purdue-UNAL-IronHack-lfvalderrama          0           1       4
2017-Purdue-UNAL-IronHack-nabautistal           0           8       0
2017-Purdue-UNAL-IronHack-nfmorenog             0           1       2
2017-Purdue-UNAL-IronHack-oeroaq                0          58      59
2017-Purdue-UNAL-IronHack-ronaldsg20            0           0  119771
2017-Purdue-UNAL-IronHack-srmedinac             0          59      16
2017-Purdue-UNAL-IronHack-wolfstain             0          50       6
2017-Purdue-UNAL-IronHack-xdanielsb             1          27     270

In [46]:
mergedDF_15_final.to_csv('mergedDF_15_final.csv')

In [47]:
mergedDF_45_final = mergedDF_45.groupby(['username_folder_name', '_merge']).size().unstack(fill_value=0)
mergedDF_45_final

_merge                                  left_only  right_only    both
username_folder_name
2017-Purdue-UNAL-IronHack-Chranium              0           0       1
2017-Purdue-UNAL-IronHack-Christian7sr          0           3       1
2017-Purdue-UNAL-IronHack-bsgarciac             0           0       9
2017-Purdue-UNAL-IronHack-dsbarrerag            0           1       9
2017-Purdue-UNAL-IronHack-falperezgo            0           0     127
2017-Purdue-UNAL-IronHack-jiapulidoar           0           0  464650
2017-Purdue-UNAL-IronHack-jucjimenezmo          0           0       4
2017-Purdue-UNAL-IronHack-kgbayala528           0           0       4
2017-Purdue-UNAL-IronHack-lfvalderrama          0           0       9
2017-Purdue-UNAL-IronHack-nabautistal           0           8       0
2017-Purdue-UNAL-IronHack-nfmorenog             0           0       3
2017-Purdue-UNAL-IronHack-oeroaq                7           1     715
2017-Purdue-UNAL-IronHack-ronaldsg20            0           0  120061
2017-Purdue-UNAL-IronHack-srmedinac             0           0     257
2017-Purdue-UNAL-IronHack-wolfstain             0           0     184
2017-Purdue-UNAL-IronHack-xdanielsb             0          11     475

In [48]:
mergedDF_45_final.to_csv('mergedDF_45_final.csv')

In [49]:
mergedDF_34_final = mergedDF_34.groupby(['username_folder_name', '_merge']).size().unstack(fill_value=0)
mergedDF_34_final

_merge                                  left_only  right_only    both
username_folder_name
2017-Purdue-UNAL-IronHack-Chranium              0           0       1
2017-Purdue-UNAL-IronHack-Christian7sr          0           0       1
2017-Purdue-UNAL-IronHack-bsgarciac             0           2      14
2017-Purdue-UNAL-IronHack-dsbarrerag            0           0       9
2017-Purdue-UNAL-IronHack-falperezgo            0           3     112
2017-Purdue-UNAL-IronHack-jiapulidoar           0           0  464501
2017-Purdue-UNAL-IronHack-jucjimenezmo          0           4       0
2017-Purdue-UNAL-IronHack-kgbayala528           0           0       4
2017-Purdue-UNAL-IronHack-lfvalderrama          0           0      12
2017-Purdue-UNAL-IronHack-nfmorenog             0           0       3
2017-Purdue-UNAL-IronHack-oeroaq                4          20     371
2017-Purdue-UNAL-IronHack-ronaldsg20            0           0  119813
2017-Purdue-UNAL-IronHack-srmedinac             0           0     257
2017-Purdue-UNAL-IronHack-wolfstain             0           0     180
2017-Purdue-UNAL-IronHack-xdanielsb             0           1     356

In [50]:
mergedDF_34_final.to_csv('mergedDF_34_final.csv')

In [51]:
mergedDF_23_final = mergedDF_23.groupby(['username_folder_name', '_merge']).size().unstack(fill_value=0)
mergedDF_23_final

_merge                                  left_only  right_only    both
username_folder_name
2017-Purdue-UNAL-IronHack-Chranium              0           0       1
2017-Purdue-UNAL-IronHack-Christian7sr          0           1       0
2017-Purdue-UNAL-IronHack-bsgarciac             0           6       8
2017-Purdue-UNAL-IronHack-dsbarrerag            0           0       5
2017-Purdue-UNAL-IronHack-falperezgo            0           0     104
2017-Purdue-UNAL-IronHack-jiapulidoar           0           0  464462
2017-Purdue-UNAL-IronHack-kgbayala528           0           0       4
2017-Purdue-UNAL-IronHack-lfvalderrama          0           1       5
2017-Purdue-UNAL-IronHack-nfmorenog             0           0       3
2017-Purdue-UNAL-IronHack-oeroaq                0          38      47
2017-Purdue-UNAL-IronHack-ronaldsg20            0           0  119525
2017-Purdue-UNAL-IronHack-srmedinac             0           0     257
2017-Purdue-UNAL-IronHack-wolfstain             0          45      10
2017-Purdue-UNAL-IronHack-xdanielsb             1           6     281

In [52]:
mergedDF_23_final.to_csv('mergedDF_23_final.csv')

In [53]:
mergedDF_12_final = mergedDF_12.groupby(['username_folder_name', '_merge']).size().unstack(fill_value=0)
mergedDF_12_final

_merge                                  left_only  right_only    both
username_folder_name
2017-Purdue-UNAL-IronHack-Chranium              0           0       1
2017-Purdue-UNAL-IronHack-bsgarciac             0           3       1
2017-Purdue-UNAL-IronHack-dsbarrerag            0           3       0
2017-Purdue-UNAL-IronHack-falperezgo            0          52       0
2017-Purdue-UNAL-IronHack-jiapulidoar           0        1015    2620
2017-Purdue-UNAL-IronHack-kgbayala528           0           0       4
2017-Purdue-UNAL-IronHack-lfvalderrama          0           0       3
2017-Purdue-UNAL-IronHack-nfmorenog             0           1       2
2017-Purdue-UNAL-IronHack-oeroaq                0           0      15
2017-Purdue-UNAL-IronHack-ronaldsg20            0           0  119259
2017-Purdue-UNAL-IronHack-srmedinac             0          59      16
2017-Purdue-UNAL-IronHack-wolfstain             1           2       1
2017-Purdue-UNAL-IronHack-xdanielsb             0           5     170

In [54]:
mergedDF_12_final.to_csv('mergedDF_12_final.csv')

In [55]:
d3_phase12 = pd.read_csv('mergedDF_12_final.csv')
d3_phase12

                      username_folder_name  left_only  right_only    both
0       2017-Purdue-UNAL-IronHack-Chranium          0           0       1
1      2017-Purdue-UNAL-IronHack-bsgarciac          0           3       1
2     2017-Purdue-UNAL-IronHack-dsbarrerag          0           3       0
3     2017-Purdue-UNAL-IronHack-falperezgo          0          52       0
4    2017-Purdue-UNAL-IronHack-jiapulidoar          0        1015    2620
5    2017-Purdue-UNAL-IronHack-kgbayala528          0           0       4
6   2017-Purdue-UNAL-IronHack-lfvalderrama          0           0       3
7      2017-Purdue-UNAL-IronHack-nfmorenog          0           1       2
8         2017-Purdue-UNAL-IronHack-oeroaq          0           0      15
9     2017-Purdue-UNAL-IronHack-ronaldsg20          0           0  119259
10     2017-Purdue-UNAL-IronHack-srmedinac          0          59      16
11     2017-Purdue-UNAL-IronHack-wolfstain          1           2       1
12     2017-Purdue-UNAL-IronHack-xdanielsb          0           5     170

In [56]:
components = d3_phase12.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack     bsgarciac
2   017  Purdue  UNAL  IronHack    dsbarrerag
3   017  Purdue  UNAL  IronHack    falperezgo
4   017  Purdue  UNAL  IronHack   jiapulidoar
5   017  Purdue  UNAL  IronHack   kgbayala528
6   017  Purdue  UNAL  IronHack  lfvalderrama
7   017  Purdue  UNAL  IronHack     nfmorenog
8   017  Purdue  UNAL  IronHack        oeroaq
9   017  Purdue  UNAL  IronHack    ronaldsg20
10  017  Purdue  UNAL  IronHack     srmedinac
11  017  Purdue  UNAL  IronHack     wolfstain
12  017  Purdue  UNAL  IronHack     xdanielsb

In [57]:
d3_phase12['name'] = components[4]
d3_phase12_rename = d3_phase12.rename(columns={"left_only": "d3-delete-12", "right_only": "d3-add-12"})
d3_phase12_rename = d3_phase12.rename(columns={"name": "Student", "left_only": "d3-delete-12", "right_only": "d3-add-12"})
d3_phase12_final = d3_phase12_rename.drop(['username_folder_name', 'both'], 1)
d3_phase12_final

    d3-delete-12  d3-add-12       Student
0              0          0      Chranium
1              0          3     bsgarciac
2              0          3    dsbarrerag
3              0         52    falperezgo
4              0       1015   jiapulidoar
5              0          0   kgbayala528
6              0          0  lfvalderrama
7              0          1     nfmorenog
8              0          0        oeroaq
9              0          0    ronaldsg20
10             0         59     srmedinac
11             1          2     wolfstain
12             0          5     xdanielsb

In [58]:
d3_phase12_final.to_csv('d3_phase12_final.csv')

In [59]:
d3_phase23 = pd.read_csv('mergedDF_23_final.csv')
d3_phase23

                      username_folder_name  left_only  right_only    both
0       2017-Purdue-UNAL-IronHack-Chranium          0           0       1
1   2017-Purdue-UNAL-IronHack-Christian7sr          0           1       0
2      2017-Purdue-UNAL-IronHack-bsgarciac          0           6       8
3     2017-Purdue-UNAL-IronHack-dsbarrerag          0           0       5
4     2017-Purdue-UNAL-IronHack-falperezgo          0           0     104
5    2017-Purdue-UNAL-IronHack-jiapulidoar          0           0  464462
6    2017-Purdue-UNAL-IronHack-kgbayala528          0           0       4
7   2017-Purdue-UNAL-IronHack-lfvalderrama          0           1       5
8      2017-Purdue-UNAL-IronHack-nfmorenog          0           0       3
9         2017-Purdue-UNAL-IronHack-oeroaq          0          38      47
10    2017-Purdue-UNAL-IronHack-ronaldsg20          0           0  119525
11     2017-Purdue-UNAL-IronHack-srmedinac          0           0     257
12     2017-Purdue-UNAL-IronHack-wolfstain          0          45      10
13     2017-Purdue-UNAL-IronHack-xdanielsb          1           6     281

In [60]:
components = d3_phase23.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack  Christian7sr
2   017  Purdue  UNAL  IronHack     bsgarciac
3   017  Purdue  UNAL  IronHack    dsbarrerag
4   017  Purdue  UNAL  IronHack    falperezgo
5   017  Purdue  UNAL  IronHack   jiapulidoar
6   017  Purdue  UNAL  IronHack   kgbayala528
7   017  Purdue  UNAL  IronHack  lfvalderrama
8   017  Purdue  UNAL  IronHack     nfmorenog
9   017  Purdue  UNAL  IronHack        oeroaq
10  017  Purdue  UNAL  IronHack    ronaldsg20
11  017  Purdue  UNAL  IronHack     srmedinac
12  017  Purdue  UNAL  IronHack     wolfstain
13  017  Purdue  UNAL  IronHack     xdanielsb

In [61]:
d3_phase23['name'] = components[4]
d3_phase23_rename = d3_phase23.rename(columns={"left_only": "d3-delete-23", "right_only": "d3-add-23"})
d3_phase23_rename = d3_phase23.rename(columns={"name": "Student", "left_only": "d3-delete-23", "right_only": "d3-add-23"})
d3_phase23_final = d3_phase23_rename.drop(['username_folder_name', 'both'], 1)
d3_phase23_final

    d3-delete-23  d3-add-23       Student
0              0          0      Chranium
1              0          1  Christian7sr
2              0          6     bsgarciac
3              0          0    dsbarrerag
4              0          0    falperezgo
5              0          0   jiapulidoar
6              0          0   kgbayala528
7              0          1  lfvalderrama
8              0          0     nfmorenog
9              0         38        oeroaq
10             0          0    ronaldsg20
11             0          0     srmedinac
12             0         45     wolfstain
13             1          6     xdanielsb

In [62]:
d3_phase23_final.to_csv('d3_phase23_final.csv')

In [63]:
d3_phase34 = pd.read_csv('mergedDF_34_final.csv')
d3_phase34

                      username_folder_name  left_only  right_only    both
0       2017-Purdue-UNAL-IronHack-Chranium          0           0       1
1   2017-Purdue-UNAL-IronHack-Christian7sr          0           0       1
2      2017-Purdue-UNAL-IronHack-bsgarciac          0           2      14
3     2017-Purdue-UNAL-IronHack-dsbarrerag          0           0       9
4     2017-Purdue-UNAL-IronHack-falperezgo          0           3     112
5    2017-Purdue-UNAL-IronHack-jiapulidoar          0           0  464501
6   2017-Purdue-UNAL-IronHack-jucjimenezmo          0           4       0
7    2017-Purdue-UNAL-IronHack-kgbayala528          0           0       4
8   2017-Purdue-UNAL-IronHack-lfvalderrama          0           0      12
9      2017-Purdue-UNAL-IronHack-nfmorenog          0           0       3
10        2017-Purdue-UNAL-IronHack-oeroaq          4          20     371
11    2017-Purdue-UNAL-IronHack-ronaldsg20          0           0  119813
12     2017-Purdue-UNAL-IronHack-srmedinac          0           0     257
13     2017-Purdue-UNAL-IronHack-wolfstain          0           0     180
14     2017-Purdue-UNAL-IronHack-xdanielsb          0           1     356

In [64]:
components = d3_phase34.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack  Christian7sr
2   017  Purdue  UNAL  IronHack     bsgarciac
3   017  Purdue  UNAL  IronHack    dsbarrerag
4   017  Purdue  UNAL  IronHack    falperezgo
5   017  Purdue  UNAL  IronHack   jiapulidoar
6   017  Purdue  UNAL  IronHack  jucjimenezmo
7   017  Purdue  UNAL  IronHack   kgbayala528
8   017  Purdue  UNAL  IronHack  lfvalderrama
9   017  Purdue  UNAL  IronHack     nfmorenog
10  017  Purdue  UNAL  IronHack        oeroaq
11  017  Purdue  UNAL  IronHack    ronaldsg20
12  017  Purdue  UNAL  IronHack     srmedinac
13  017  Purdue  UNAL  IronHack     wolfstain
14  017  Purdue  UNAL  IronHack     xdanielsb

In [65]:
d3_phase34['name'] = components[4]
d3_phase34_rename = d3_phase34.rename(columns={"left_only": "d3-delete-34", "right_only": "d3-add-34"})
d3_phase34_rename = d3_phase34.rename(columns={"name": "Student", "left_only": "d3-delete-34", "right_only": "d3-add-34"})
d3_phase34_final = d3_phase34_rename.drop(['username_folder_name', 'both'], 1)
d3_phase34_final

    d3-delete-34  d3-add-34       Student
0              0          0      Chranium
1              0          0  Christian7sr
2              0          2     bsgarciac
3              0          0    dsbarrerag
4              0          3    falperezgo
5              0          0   jiapulidoar
6              0          4  jucjimenezmo
7              0          0   kgbayala528
8              0          0  lfvalderrama
9              0          0     nfmorenog
10             4         20        oeroaq
11             0          0    ronaldsg20
12             0          0     srmedinac
13             0          0     wolfstain
14             0          1     xdanielsb

In [66]:
d3_phase34_final.to_csv('d3_phase34_final.csv')

In [67]:
d3_phase45 = pd.read_csv('mergedDF_45_final.csv')
d3_phase45

                      username_folder_name  left_only  right_only    both
0       2017-Purdue-UNAL-IronHack-Chranium          0           0       1
1   2017-Purdue-UNAL-IronHack-Christian7sr          0           3       1
2      2017-Purdue-UNAL-IronHack-bsgarciac          0           0       9
3     2017-Purdue-UNAL-IronHack-dsbarrerag          0           1       9
4     2017-Purdue-UNAL-IronHack-falperezgo          0           0     127
5    2017-Purdue-UNAL-IronHack-jiapulidoar          0           0  464650
6   2017-Purdue-UNAL-IronHack-jucjimenezmo          0           0       4
7    2017-Purdue-UNAL-IronHack-kgbayala528          0           0       4
8   2017-Purdue-UNAL-IronHack-lfvalderrama          0           0       9
9    2017-Purdue-UNAL-IronHack-nabautistal          0           8       0
10     2017-Purdue-UNAL-IronHack-nfmorenog          0           0       3
11        2017-Purdue-UNAL-IronHack-oeroaq          7           1     715
12    2017-Purdue-UNAL-IronHack-ronaldsg20          0           0  120061
13     2017-Purdue-UNAL-IronHack-srmedinac          0           0     257
14     2017-Purdue-UNAL-IronHack-wolfstain          0           0     184
15     2017-Purdue-UNAL-IronHack-xdanielsb          0          11     475

In [68]:
components = d3_phase45.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack  Christian7sr
2   017  Purdue  UNAL  IronHack     bsgarciac
3   017  Purdue  UNAL  IronHack    dsbarrerag
4   017  Purdue  UNAL  IronHack    falperezgo
5   017  Purdue  UNAL  IronHack   jiapulidoar
6   017  Purdue  UNAL  IronHack  jucjimenezmo
7   017  Purdue  UNAL  IronHack   kgbayala528
8   017  Purdue  UNAL  IronHack  lfvalderrama
9   017  Purdue  UNAL  IronHack   nabautistal
10  017  Purdue  UNAL  IronHack     nfmorenog
11  017  Purdue  UNAL  IronHack        oeroaq
12  017  Purdue  UNAL  IronHack    ronaldsg20
13  017  Purdue  UNAL  IronHack     srmedinac
14  017  Purdue  UNAL  IronHack     wolfstain
15  017  Purdue  UNAL  IronHack     xdanielsb

In [69]:
d3_phase45['name'] = components[4]
d3_phase45_rename = d3_phase45.rename(columns={"left_only": "d3-delete-45", "right_only": "d3-add-45"})
d3_phase45_rename = d3_phase45.rename(columns={"name": "Student","left_only": "d3-delete-45", "right_only": "d3-add-45"})
d3_phase45_final = d3_phase45_rename.drop(['username_folder_name', 'both'], 1)
d3_phase45_final

    d3-delete-45  d3-add-45       Student
0              0          0      Chranium
1              0          3  Christian7sr
2              0          0     bsgarciac
3              0          1    dsbarrerag
4              0          0    falperezgo
5              0          0   jiapulidoar
6              0          0  jucjimenezmo
7              0          0   kgbayala528
8              0          0  lfvalderrama
9              0          8   nabautistal
10             0          0     nfmorenog
11             7          1        oeroaq
12             0          0    ronaldsg20
13             0          0     srmedinac
14             0          0     wolfstain
15             0         11     xdanielsb

In [70]:
d3_phase45_final.to_csv('d3_phase45_final.csv')

In [71]:
d3_phase15 = pd.read_csv('mergedDF_15_final.csv')
d3_phase15

                      username_folder_name  left_only  right_only    both
0       2017-Purdue-UNAL-IronHack-Chranium          0           0       1
1   2017-Purdue-UNAL-IronHack-Christian7sr          0           4       0
2      2017-Purdue-UNAL-IronHack-bsgarciac          0           8       1
3     2017-Purdue-UNAL-IronHack-dsbarrerag          0           6       0
4     2017-Purdue-UNAL-IronHack-falperezgo          0          59       0
5    2017-Purdue-UNAL-IronHack-jiapulidoar          0        1017    2622
6   2017-Purdue-UNAL-IronHack-jucjimenezmo          0           4       0
7    2017-Purdue-UNAL-IronHack-kgbayala528          0           0       4
8   2017-Purdue-UNAL-IronHack-lfvalderrama          0           1       4
9    2017-Purdue-UNAL-IronHack-nabautistal          0           8       0
10     2017-Purdue-UNAL-IronHack-nfmorenog          0           1       2
11        2017-Purdue-UNAL-IronHack-oeroaq          0          58      59
12    2017-Purdue-UNAL-IronHack-ronaldsg20          0           0  119771
13     2017-Purdue-UNAL-IronHack-srmedinac          0          59      16
14     2017-Purdue-UNAL-IronHack-wolfstain          0          50       6
15     2017-Purdue-UNAL-IronHack-xdanielsb          1          27     270

In [72]:
components = d3_phase15.username_folder_name.str[1:].str.split('-', expand = True)
components

      0       1     2         3             4
0   017  Purdue  UNAL  IronHack      Chranium
1   017  Purdue  UNAL  IronHack  Christian7sr
2   017  Purdue  UNAL  IronHack     bsgarciac
3   017  Purdue  UNAL  IronHack    dsbarrerag
4   017  Purdue  UNAL  IronHack    falperezgo
5   017  Purdue  UNAL  IronHack   jiapulidoar
6   017  Purdue  UNAL  IronHack  jucjimenezmo
7   017  Purdue  UNAL  IronHack   kgbayala528
8   017  Purdue  UNAL  IronHack  lfvalderrama
9   017  Purdue  UNAL  IronHack   nabautistal
10  017  Purdue  UNAL  IronHack     nfmorenog
11  017  Purdue  UNAL  IronHack        oeroaq
12  017  Purdue  UNAL  IronHack    ronaldsg20
13  017  Purdue  UNAL  IronHack     srmedinac
14  017  Purdue  UNAL  IronHack     wolfstain
15  017  Purdue  UNAL  IronHack     xdanielsb

In [73]:
d3_phase15['name'] = components[4]
d3_phase15_rename = d3_phase15.rename(columns={"left_only": "d3-delete-15", "right_only": "d3-add-15"})
d3_phase15_rename = d3_phase15.rename(columns={"name": "Student","left_only": "d3-delete-15", "right_only": "d3-add-15"})
d3_phase15_final = d3_phase15_rename.drop(['username_folder_name', 'both'], 1)
d3_phase15_final

    d3-delete-15  d3-add-15       Student
0              0          0      Chranium
1              0          4  Christian7sr
2              0          8     bsgarciac
3              0          6    dsbarrerag
4              0         59    falperezgo
5              0       1017   jiapulidoar
6              0          4  jucjimenezmo
7              0          0   kgbayala528
8              0          1  lfvalderrama
9              0          8   nabautistal
10             0          1     nfmorenog
11             0         58        oeroaq
12             0          0    ronaldsg20
13             0         59     srmedinac
14             0         50     wolfstain
15             1         27     xdanielsb

In [74]:
d3_phase15_final.to_csv('d3_phase15_final.csv')