In [1]:
%store -r overall_phase1
%store -r overall_phase2
%store -r overall_phase3
%store -r overall_phase4
%store -r overall_phase5
%store -r df_template
%store -r bogota_final

In [4]:
bogota_final['total-max-phase5'] = bogota_final.groupby(["Group"])['total-phase5'].transform(np.max)

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,improve-effort-12,improve-effort-23,improve-effort-34,improve-effort-45,improve-effort-15,improve-effort-25,functions,unique,len_unique,len_functions
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,0.0,0.0,-14.0,-6.0,-32.5,0.0,"[.ready, .click, .mcheck, .on, .closest, .list...","[.ready, .click, .mcheck, .on, .closest, .list...",21.0,21.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,-1.0,-16.5,45.5,13.0,-29.0,-21.0,"[style.css, map.js, document.getElementById, g...","[style.css, map.js, document.getElementById, g...",5.0,5.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,7.0,1.5,9.0,-4.0,7.0,-12.0,[],[],0.0,0.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,0.0,0.0,0.0,73.5,0.0,0.0,[],[],0.0,0.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,104.0,8.0,60.5,0.5,0.0,34.5,[],[],0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,0.0,12.0,1.0,1.0,11.5,11.5,"[jquery.min.js, bootstrap.min.js, tutorial.css...","[jquery.min.js, bootstrap.min.js, tutorial.css...",33.0,33.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,-33.5,0.0,0.0,0.0,0.0,-111.0,[],[],0.0,0.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,[],[],0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,[],[],0.0,0.0
163,Januguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [2]:
bogota_best = bogota_final[bogota_final['total-max-phase1'] == bogota_final['total-phase1']]
bogota_best

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,perform_diff_best_phase1,perform_diff_best_phase2,perform_diff_best_phase3,perform_diff_best_phase4,perform_diff_best_phase5,abs_perform_diff_best_phase1,abs_perform_diff_best_phase2,abs_perform_diff_best_phase3,abs_perform_diff_best_phase4,abs_perform_diff_best_phase5
22,juandavidro,0.0,20.0,58.33,25.00,153.33,50.0,37.5,20.0,54.17,...,0.0,-119.17,-117.50,-201.66,-199.59,0.0,119.17,117.50,201.66,199.59
50,gcantem,1.0,100.0,70.83,87.50,283.33,25.0,100.0,60.0,29.17,...,0.0,-81.66,-119.16,-85.83,-74.17,0.0,81.66,119.16,85.83,74.17
117,xdanielsb,2.0,100.0,87.50,70.00,357.50,100.0,50.0,0.0,25.00,...,0.0,-242.50,-283.33,-283.33,0.00,0.0,242.50,283.33,283.33,0.00
151,jmalvarezd,3.0,80.0,75.00,93.75,348.75,100.0,87.5,60.0,70.83,...,0.0,-135.00,-55.00,-140.00,-12.08,0.0,135.00,55.00,140.00,12.08

In [3]:
bogota_best = bogota_best.append(df_template, ignore_index=True)
bogota_best

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,perform_diff_best_phase3,perform_diff_best_phase4,perform_diff_best_phase5,abs_perform_diff_best_phase1,abs_perform_diff_best_phase2,abs_perform_diff_best_phase3,abs_perform_diff_best_phase4,abs_perform_diff_best_phase5,functions,phase
0,juandavidro,0.0,20.0,58.33,25.00,153.33,50.0,37.5,20.0,54.17,...,-117.50,-201.66,-199.59,0.0,119.17,117.50,201.66,199.59,NaN,NaN
1,gcantem,1.0,100.0,70.83,87.50,283.33,25.0,100.0,60.0,29.17,...,-119.16,-85.83,-74.17,0.0,81.66,119.16,85.83,74.17,NaN,NaN
2,xdanielsb,2.0,100.0,87.50,70.00,357.50,100.0,50.0,0.0,25.00,...,-283.33,-283.33,0.00,0.0,242.50,283.33,283.33,0.00,NaN,NaN
3,jmalvarezd,3.0,80.0,75.00,93.75,348.75,100.0,87.5,60.0,70.83,...,-55.00,-140.00,-12.08,0.0,135.00,55.00,140.00,12.08,NaN,NaN
4,template,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[bootstrap.min.css, theme.min.css, jquery.min....",0.0