In [1]:
# restore variables from Data-Frame-Spring-2017(Scores,LOC,Survey,D3).ipynb

%store -r bogota0
%store -r bogota1
%store -r bogota2
%store -r bogota3

# restore variables from Functional-Basic-Preprocessing.ipynb

%store -r overall_phase1
%store -r overall_phase2
%store -r overall_phase3
%store -r overall_phase4
%store -r overall_phase5

# load the libraries

import pandas as pd
import numpy as np

## Performance Distance from the Best

In [2]:
# append all dataframes from all groups

bogota0['group'] = 0
bogota1['group'] = 1
bogota2['group'] = 2
bogota3['group'] = 3

bogota01 = bogota0.append(bogota1, ignore_index=True)
bogota12 = bogota01.append(bogota2, ignore_index=True)
bogota_final = bogota12.append(bogota3, ignore_index=True)

/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2598/169917622.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bogota01 = bogota0.append(bogota1, ignore_index=True)
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2598/169917622.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bogota12 = bogota01.append(bogota2, ignore_index=True)
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2598/169917622.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bogota_final = bogota12.append(bogota3, ignore_index=True)

In [3]:
# get max total score for each group

bogota_final['total-max-phase1'] = bogota_final.groupby(["group"])['total-phase1'].transform(np.max)
bogota_final['total-max-phase2'] = bogota_final.groupby(["group"])['total-phase2'].transform(np.max)
bogota_final['total-max-phase3'] = bogota_final.groupby(["group"])['total-phase3'].transform(np.max)
bogota_final['total-max-phase4'] = bogota_final.groupby(["group"])['total-phase4'].transform(np.max)
bogota_final['total-max-phase5'] = bogota_final.groupby(["group"])['total-phase5'].transform(np.max)

In [4]:
# create new column for max performance distance in the dataframe

bogota_final['perform_diff_best_phase2'] = bogota_final['total-phase2'] - bogota_final['total-max-phase1']
bogota_final['perform_diff_best_phase3'] = bogota_final['total-phase3'] - bogota_final['total-max-phase2']
bogota_final['perform_diff_best_phase4'] = bogota_final['total-phase4'] - bogota_final['total-max-phase3']
bogota_final['perform_diff_best_phase5'] = bogota_final['total-phase5'] - bogota_final['total-max-phase4']

In [5]:
# see how the overall dataframe looks like

bogota_final

,Unnamed: 0,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,...,group,total-max-phase1,total-max-phase2,total-max-phase3,total-max-phase4,total-max-phase5,perform_diff_best_phase2,perform_diff_best_phase3,perform_diff_best_phase4,perform_diff_best_phase5
0,0,fffeelipe,0,20,29.17,50.00,199.17,100.0,100.0,20.0,...,0,300.83,247.50,293.33,313.33,352.92,-128.33,-75.00,-100.41,-114.16
1,1,mnguzmanc,0,60,75.00,67.50,290.00,87.5,87.5,20.0,...,0,300.83,247.50,293.33,313.33,352.92,-80.83,-10.83,-48.33,-23.33
2,2,jmcuestasb,0,100,54.17,25.00,254.17,75.0,62.5,100.0,...,0,300.83,247.50,293.33,313.33,352.92,-160.00,-115.00,-72.50,-59.16
3,3,katherinsb,0,20,37.50,16.67,136.67,62.5,37.5,20.0,...,0,300.83,247.50,293.33,313.33,352.92,-288.33,-247.50,-165.00,-176.66
4,4,jjrodriguezn,0,60,58.33,87.50,255.83,50.0,37.5,40.0,...,0,300.83,247.50,293.33,313.33,352.92,-189.16,-144.17,-161.66,-57.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,36,NicolasPrr,3,100,83.33,90.00,360.83,87.5,62.5,0.0,...,3,329.17,333.33,330.00,358.33,360.83,-229.17,-225.00,-209.17,2.50
159,37,jumcorredorro,3,100,62.50,75.00,325.00,87.5,87.5,80.0,...,3,329.17,333.33,330.00,358.33,360.83,-20.00,-3.33,-25.00,-33.33
160,38,feartheGru,3,0,0.00,0.00,0.00,0.0,0.0,NaN,...,3,329.17,333.33,330.00,358.33,360.83,-316.67,-333.33,-330.00,-358.33
161,39,Danielsv9207,3,0,0.00,0.00,0.00,0.0,0.0,NaN,...,3,329.17,333.33,330.00,358.33,360.83,-316.67,-333.33,-330.00,-358.33
162,40,JhonEmmanuelTorres,3,0,0.00,0.00,0.00,0.0,0.0,NaN,...,3,329.17,333.33,330.00,358.33,360.83,-316.67,-333.33,-330.00,-358.33

## Similarity from the Best

In [6]:
# Restructure Functions Dataframe

overall_phase1.rename({'functions': 'functions-phase1', 'unique': 'unique-phase1', 'len_unique': 'len_unique_phase1'}, axis=1, inplace=True)
overall_phase2.rename({'functions': 'functions-phase2', 'unique': 'unique-phase2', 'len_unique': 'len_unique_phase2'}, axis=1, inplace=True)
overall_phase3.rename({'functions': 'functions-phase3', 'unique': 'unique-phase3', 'len_unique': 'len_unique_phase3'}, axis=1, inplace=True)
overall_phase4.rename({'functions': 'functions-phase4', 'unique': 'unique-phase4', 'len_unique': 'len_unique_phase4'}, axis=1, inplace=True)
overall_phase5.rename({'functions': 'functions-phase5', 'unique': 'unique-phase5', 'len_unique': 'len_unique_phase5'}, axis=1, inplace=True)

In [17]:
# Get row for bogota 0 for every phase and append them together
# we will need to have separate dataframes for each group since we can't compare similarity intergroups

group0_phase1 = overall_phase1[overall_phase1['Group'] == 0]
group0_phase2 = overall_phase2[overall_phase2['Group'] == 0]
group0_phase3 = overall_phase3[overall_phase3['Group'] == 0]
group0_phase4 = overall_phase4[overall_phase4['Group'] == 0]
group0_phase5 = overall_phase5[overall_phase5['Group'] == 0]

group0_12 = group0_phase1.append(group0_phase2, ignore_index=True)
group0_23 = group0_12.append(group0_phase3, ignore_index=True)
group0_34 = group0_23.append(group0_phase4, ignore_index=True)
group0_final = group0_34.append(group0_phase5, ignore_index=True)

/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2598/1458977645.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  group0_12 = group0_phase1.append(group0_phase2, ignore_index=True)
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2598/1458977645.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  group0_23 = group0_12.append(group0_phase3, ignore_index=True)
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2598/1458977645.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  group0_34 = group0_23.append(group0_phase4, ignore_index=True)
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2598/1458977645.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  group0_final = group0_34.append(group0_phase5, ignore_index=True)

In [18]:
group0_final

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,len_unique_phase2,functions-phase3,unique-phase3,len_unique_phase3,functions-phase4,unique-phase4,len_unique_phase4,functions-phase5,unique-phase5,len_unique_phase5
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,odprietoh,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,[],0.0
211,janoguerab,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"js.org,.v,.min.js,document.getElementById,goog...","[js.org, .v, .min.js, document.getElementById,...",36.0
212,djsanabriac,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"bootstrap.min.css,main.js,jquery.min.js,docume...","[bootstrap.min.css, main.js, jquery.min.js, do...",32.0
213,anmmunozme,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,".ajax,data.cityofchicago.org,iimk.json,.done,d...","[.ajax, data.cityofchicago.org, iimk.json, .do...",2297.0
214,li2266,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,[],0.0

In [ ]:
# Get row for bogota 1 for every phase and append them together
# we will need to have separate dataframes for each group since we can't compare similarity intergroups

group1_phase1 = overall_phase1[overall_phase1['Group'] == 0]
group1_phase2 = overall_phase2[overall_phase2['Group'] == 0]
group1_phase3 = overall_phase3[overall_phase3['Group'] == 0]
group1_phase4 = overall_phase4[overall_phase4['Group'] == 0]
group1_phase5 = overall_phase5[overall_phase5['Group'] == 0]

group1_12 = group0_phase1.append(group0_phase2, ignore_index=True)
group1_23 = group0_12.append(group0_phase3, ignore_index=True)
group1_34 = group0_23.append(group0_phase4, ignore_index=True)
group1_final = group0_34.append(group0_phase5, ignore_index=True)