In [1]:
# retrieved from functional variety notebook 

%store -r overall_phase1
%store -r overall_phase2
%store -r overall_phase3
%store -r overall_phase4
%store -r overall_phase5

%store -r overall_phase1_bogota0
%store -r overall_phase2_bogota0
%store -r overall_phase3_bogota0
%store -r overall_phase4_bogota0
%store -r overall_phase5_bogota0

%store -r overall_phase1_bogota1
%store -r overall_phase2_bogota1
%store -r overall_phase3_bogota1
%store -r overall_phase4_bogota1
%store -r overall_phase5_bogota1

%store -r overall_phase1_bogota2
%store -r overall_phase2_bogota2
%store -r overall_phase3_bogota2
%store -r overall_phase4_bogota2
%store -r overall_phase5_bogota2

%store -r overall_phase1_bogota3
%store -r overall_phase2_bogota3
%store -r overall_phase3_bogota3
%store -r overall_phase4_bogota3
%store -r overall_phase5_bogota3

%store -r survey

import pandas as pd

In [2]:
p1 = overall_phase1[['Student', 'Group', 'len_unique']]
p1['phase'] = 1
p1 = p1[p1['Group'].notnull()]

p2 = overall_phase2[['Student', 'Group', 'len_unique']]
p2['phase'] = 2
p2 = p2[p2['Group'].notnull()]

p3 = overall_phase3[['Student', 'Group', 'len_unique']]
p3['phase'] = 3
p3 = p3[p3['Group'].notnull()]

p4 = overall_phase4[['Student', 'Group', 'len_unique']]
p4['phase'] = 4
p4 = p4[p4['Group'].notnull()]

p5 = overall_phase5[['Student', 'Group', 'len_unique']]
p5['phase'] = 5
p5 = p5[p5['Group'].notnull()]

/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2642/3608670455.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p1['phase'] = 1
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2642/3608670455.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p2['phase'] = 2
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2642/3608670455.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p3['phase'] = 3
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2642/3608670455.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p4['phase'] = 4
/var/folders/nr/2yp640v56_x34zrd2n5jvfqc0000gn/T/ipykernel_2642/3608670455.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p5['phase'] = 5

In [3]:
variety = pd.concat([p1, p2, p3, p4, p5], ignore_index = True)
variety.reset_index()

     index             Student  Group  len_unique  phase
0        0           fffeelipe    0.0        21.0      1
1        1           mnguzmanc    0.0         5.0      1
2        2          jmcuestasb    0.0         0.0      1
3        3          katherinsb    0.0         0.0      1
4        4        jjrodriguezn    0.0         0.0      1
..     ...                 ...    ...         ...    ...
810    810          NicolasPrr    3.0       133.0      5
811    811       jumcorredorro    3.0       181.0      5
812    812          feartheGru    3.0         0.0      5
813    813        Danielsv9207    3.0         0.0      5
814    814  JhonEmmanuelTorres    3.0         0.0      5

[815 rows x 5 columns]

In [4]:
%store variety

Stored 'variety' (DataFrame)

In [5]:
overall_phase2['unique']

,Student,Group,user-requirement-phase5,infovis-phase5,novelty-phase5,total-phase5,tech-phase5,tech-phase4,user-requirement-phase4,infovis-phase4,...,improve-effort-12,improve-effort-23,improve-effort-34,improve-effort-45,improve-effort-15,improve-effort-25,functions,unique,len_unique,len_functions
0,fffeelipe,0.0,20.0,29.17,50.00,199.17,100.0,100.0,20.0,29.17,...,0.0,0.0,-14.0,-6.0,-32.5,0.0,"[.ready, .click, .mcheck, .on, .closest, .list...","[.ready, .click, .mcheck, .on, .closest, .list...",21.0,21.0
1,mnguzmanc,0.0,60.0,75.00,67.50,290.00,87.5,87.5,20.0,37.50,...,-1.0,-16.5,45.5,13.0,-29.0,-21.0,"[style.css, map.js, document.getElementById, g...","[style.css, map.js, document.getElementById, g...",5.0,5.0
2,jmcuestasb,0.0,100.0,54.17,25.00,254.17,75.0,62.5,100.0,58.33,...,7.0,1.5,9.0,-4.0,7.0,-12.0,[],[],0.0,0.0
3,katherinsb,0.0,20.0,37.50,16.67,136.67,62.5,37.5,20.0,45.83,...,0.0,0.0,0.0,73.5,0.0,0.0,[],[],0.0,0.0
4,jjrodriguezn,0.0,60.0,58.33,87.50,255.83,50.0,37.5,40.0,54.17,...,104.0,8.0,60.5,0.5,0.0,34.5,[],[],0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,jumcorredorro,3.0,100.0,62.50,75.00,325.00,87.5,87.5,80.0,58.33,...,0.0,12.0,1.0,1.0,11.5,11.5,"[jquery.min.js, bootstrap.min.js, tutorial.css...","[jquery.min.js, bootstrap.min.js, tutorial.css...",33.0,33.0
160,feartheGru,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,-33.5,0.0,0.0,0.0,0.0,-111.0,[],[],0.0,0.0
161,Danielsv9207,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,[],[],0.0,0.0
162,JhonEmmanuelTorres,3.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,[],[],0.0,0.0
163,Januguerab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN